import { useLanguage } from '../contexts/LanguageContext';

const PREVIEW_COPY = {
  en: {
    'Loading...': 'Loading...',
    'Accounting dashboard': 'Accounting dashboard',
    Revenue: 'Revenue',
    Expenses: 'Expenses',
    'Net profit': 'Net profit',
    'Cash balance': 'Cash balance',
    '+4.8% vs previous month': '+4.8% vs previous month',
    'Tax position': 'Tax position',
    'GST/HST payable snapshot': 'GST/HST payable snapshot',
    'Financial status': 'Financial status',
    'Current ratio: 1.9': 'Current ratio: 1.9',
    'AR days: 31': 'AR days: 31',
    'AP days: 26': 'AP days: 26',
    'AI business insights': 'AI business insights',
    'Assistant active': 'Assistant active',
    'Sales prediction model': 'Sales prediction model',
    Confidence: 'Confidence',
    'Model based on current ERP transactions': 'Model based on current ERP transactions',
    'Revenue momentum': 'Revenue momentum',
    '+12.4% projected for next 30 days': '+12.4% projected for next 30 days',
    'Margin pressure': 'Margin pressure',
    'Raw material cost up 3.1% this week': 'Raw material cost up 3.1% this week',
    'Receivables risk': 'Receivables risk',
    '4 accounts likely to miss due date': '4 accounts likely to miss due date',
    success: 'success',
    warning: 'warning',
    danger: 'danger',
    'Expenses tracking': 'Expenses tracking',
    'Tax associated:': 'Tax associated:',
    'Month to date': 'Month to date',
    'Expenses posted': 'Expenses posted',
    'Recoverable tax': 'Recoverable tax',
    'GST/HST/PST/QST credits': 'GST/HST/PST/QST credits',
    'Policy variance': 'Policy variance',
    '3 flagged': '3 flagged',
    'Pending review': 'Pending review',
    'Inventory management': 'Inventory management',
    '2 low-stock alerts': '2 low-stock alerts',
    SKUs: 'SKUs',
    'On hand': 'On hand',
    'Inventory value': 'Inventory value',
    'Stock:': 'Stock:',
    'Min:': 'Min:',
    'Invoices module': 'Invoices module',
    '112 open': '112 open',
    Invoice: 'Invoice',
    Client: 'Client',
    Total: 'Total',
    Status: 'Status',
    Draft: 'Draft',
    Paid: 'Paid',
    Overdue: 'Overdue',
    'BOM summary': 'BOM summary',
    '12 components linked to cost rollup': '12 components linked to cost rollup',
    '8 components linked to lot traceability': '8 components linked to lot traceability',
    'Capacity usage': 'Capacity usage',
    '84% this shift': '84% this shift',
    'Production orders': 'Production orders',
    Running: 'Running',
    Queued: 'Queued',
    'Final check': 'Final check',
    'Purchases module': 'Purchases module',
    '6 vendors active': '6 vendors active',
    'Open POs': 'Open POs',
    'Approved value': 'Approved value',
    'Lead-time risk': 'Lead-time risk',
    Low: 'Low',
    'Status:': 'Status:',
    Approved: 'Approved',
    Received: 'Received',
    Pending: 'Pending',
    'Reports and analytics': 'Reports and analytics',
    'Profit and loss trend': 'Profit and loss trend',
    'Gross profit': 'Gross profit',
    Runway: 'Runway',
    Forecast: 'Forecast',
    'On track': 'On track',
    'Warehouse map': 'Warehouse map',
    Ready: 'Ready',
    Picking: 'Picking',
    Inbound: 'Inbound',
    'Picking queue': 'Picking queue',
    '24 tasks in progress': '24 tasks in progress',
    'Stock movement flow': 'Stock movement flow',
    units: 'units',
    'Today’s shift': 'Today’s shift',
    '3 clocked in': '3 clocked in',
    'On shift': 'On shift',
    'Open tasks': 'Open tasks',
    'Hours today': 'Hours today',
    'Front counter': 'Front counter',
    'Kitchen line': 'Kitchen line',
    'Shift lead': 'Shift lead',
    Delivery: 'Delivery',
    'Clocked in': 'Clocked in',
    'On break': 'On break',
    Scheduled: 'Scheduled',
  },
  fr: {
    'Loading...': 'Chargement...',
    'Accounting dashboard': 'Tableau de bord comptable',
    Revenue: 'Revenu',
    Expenses: 'Dépenses',
    'Net profit': 'Bénéfice net',
    'Cash balance': 'Solde de trésorerie',
    '+4.8% vs previous month': '+4,8% vs mois précédent',
    'Tax position': 'Situation fiscale',
    'GST/HST payable snapshot': 'Aperçu de la TPS/TVH à payer',
    'Financial status': 'Situation financière',
    'Current ratio: 1.9': 'Ratio de liquidité actuel : 1,9',
    'AR days: 31': 'Jours AR : 31',
    'AP days: 26': 'Jours AP : 26',
    'AI business insights': "Informations commerciales sur l'IA",
    'Assistant active': 'Assistant actif',
    'Sales prediction model': 'Modèle de prédiction des ventes',
    Confidence: 'Confiance',
    'Model based on current ERP transactions': 'Modèle basé sur les transactions ERP actuelles',
    'Revenue momentum': 'Dynamique des revenus',
    '+12.4% projected for next 30 days': '+12,4% prévu pour les 30 prochains jours',
    'Margin pressure': 'Pression sur les marges',
    'Raw material cost up 3.1% this week':
      'Le coût des matières premières en hausse de 3,1% cette semaine',
    'Receivables risk': 'Risque lié aux créances',
    '4 accounts likely to miss due date':
      "4 comptes susceptibles de ne pas respecter la date d'échéance",
    success: 'succès',
    warning: 'avertissement',
    danger: 'danger',
    'Expenses tracking': 'Suivi des dépenses',
    'Tax associated:': 'Taxe associée :',
    'Month to date': 'Le mois courant',
    'Expenses posted': 'Dépenses affichées',
    'Recoverable tax': 'Impôt récupérable',
    'GST/HST/PST/QST credits': 'Crédits TPS/TVH/TVP/TVQ',
    'Policy variance': 'Écart de politique',
    '3 flagged': '3 signalés',
    'Pending review': "En attente d'examen",
    'Inventory management': 'Gestion des stocks',
    '2 low-stock alerts': '2 alertes de rupture de stock',
    SKUs: 'SKU',
    'On hand': 'En stock',
    'Inventory value': "Valeur d'inventaire",
    'Stock:': 'Stock :',
    'Min:': 'Min :',
    'Invoices module': 'Module Factures',
    '112 open': '112 ouvertes',
    Invoice: 'Facture',
    Client: 'Client',
    Total: 'Total',
    Status: 'Statut',
    Draft: 'Brouillon',
    Paid: 'Payé',
    Overdue: 'En retard',
    'BOM summary': 'Résumé de la nomenclature',
    '12 components linked to cost rollup': '12 composants liés au cumul des coûts',
    '8 components linked to lot traceability': '8 composants liés à la traçabilité des lots',
    'Capacity usage': 'Utilisation de la capacité',
    '84% this shift': '84 % ce quart',
    'Production orders': 'Ordres de fabrication',
    Running: 'En cours',
    Queued: "En file d'attente",
    'Final check': 'Vérification finale',
    'Purchases module': 'Module Achats',
    '6 vendors active': '6 fournisseurs actifs',
    'Open POs': 'BC ouvertes',
    'Approved value': 'Valeur approuvée',
    'Lead-time risk': 'Risque de délai',
    Low: 'Faible',
    'Status:': 'Statut :',
    Approved: 'Approuvé',
    Received: 'Reçu',
    Pending: 'En attente',
    'Reports and analytics': 'Rapports et analyses',
    'Profit and loss trend': 'Tendance du résultat',
    'Gross profit': 'Marge brute',
    Runway: 'Piste',
    Forecast: 'Prévision',
    'On track': 'En bonne voie',
    'Warehouse map': "Plan de l'entrepôt",
    Ready: 'Prêt',
    Picking: 'Préparation',
    Inbound: 'Entrant',
    'Picking queue': 'File de préparation',
    '24 tasks in progress': '24 tâches en cours',
    'Stock movement flow': 'Flux de mouvements de stock',
    units: 'unités',
    'Today’s shift': "Le quart d'aujourd'hui",
    '3 clocked in': '3 pointés',
    'On shift': 'En service',
    'Open tasks': 'Tâches ouvertes',
    'Hours today': "Heures aujourd'hui",
    'Front counter': 'Comptoir',
    'Kitchen line': 'Cuisine',
    'Shift lead': 'Chef de quart',
    Delivery: 'Livraison',
    'Clocked in': 'Pointé',
    'On break': 'En pause',
    Scheduled: 'Planifié',
  },
  es: {
    'Loading...': 'Cargando...',
    'Accounting dashboard': 'Panel de contabilidad',
    Revenue: 'Ingresos',
    Expenses: 'Gastos',
    'Net profit': 'Beneficio neto',
    'Cash balance': 'Saldo de caja',
    '+4.8% vs previous month': '+4,8% respecto al mes anterior',
    'Tax position': 'Posición fiscal',
    'GST/HST payable snapshot': 'Resumen de GST/HST por pagar',
    'Financial status': 'Estado financiero',
    'Current ratio: 1.9': 'Razón corriente: 1,9',
    'AR days: 31': 'Días de CxC: 31',
    'AP days: 26': 'Días de CxP: 26',
    'AI business insights': 'Información empresarial de IA',
    'Assistant active': 'Asistente activo',
    'Sales prediction model': 'Modelo de predicción de ventas',
    Confidence: 'Confianza',
    'Model based on current ERP transactions': 'Modelo basado en transacciones actuales del ERP',
    'Revenue momentum': 'Impulso de ingresos',
    '+12.4% projected for next 30 days': '+12,4% proyectado para los próximos 30 días',
    'Margin pressure': 'Presión de margen',
    'Raw material cost up 3.1% this week': 'El coste de materias primas subió 3,1% esta semana',
    'Receivables risk': 'Riesgo de cuentas por cobrar',
    '4 accounts likely to miss due date':
      '4 cuentas probablemente incumplan la fecha de vencimiento',
    success: 'éxito',
    warning: 'advertencia',
    danger: 'peligro',
    'Expenses tracking': 'Seguimiento de gastos',
    'Tax associated:': 'Impuesto asociado:',
    'Month to date': 'Mes a la fecha',
    'Expenses posted': 'Gastos contabilizados',
    'Recoverable tax': 'Impuesto recuperable',
    'GST/HST/PST/QST credits': 'Créditos GST/HST/PST/QST',
    'Policy variance': 'Variación de política',
    '3 flagged': '3 marcados',
    'Pending review': 'Pendiente de revisión',
    'Inventory management': 'Gestión de inventario',
    '2 low-stock alerts': '2 alertas de stock bajo',
    SKUs: 'SKU',
    'On hand': 'Disponible',
    'Inventory value': 'Valor del inventario',
    'Stock:': 'Stock:',
    'Min:': 'Mín:',
    'Invoices module': 'Módulo de facturas',
    '112 open': '112 abiertas',
    Invoice: 'Factura',
    Client: 'Cliente',
    Total: 'Total',
    Status: 'Estado',
    Draft: 'Borrador',
    Paid: 'Pagado',
    Overdue: 'Vencido',
    'BOM summary': 'Resumen de BOM',
    '12 components linked to cost rollup': '12 componentes vinculados al cost rollup',
    '8 components linked to lot traceability':
      '8 componentes vinculados a la trazabilidad por lote',
    'Capacity usage': 'Uso de capacidad',
    '84% this shift': '84% en este turno',
    'Production orders': 'Órdenes de producción',
    Running: 'En ejecución',
    Queued: 'En cola',
    'Final check': 'Control final',
    'Purchases module': 'Módulo de compras',
    '6 vendors active': '6 proveedores activos',
    'Open POs': 'OC abiertas',
    'Approved value': 'Valor aprobado',
    'Lead-time risk': 'Riesgo de lead time',
    Low: 'Bajo',
    'Status:': 'Estado:',
    Approved: 'Aprobado',
    Received: 'Recibido',
    Pending: 'Pendiente',
    'Reports and analytics': 'Informes y analítica',
    'Profit and loss trend': 'Tendencia de pérdidas y ganancias',
    'Gross profit': 'Beneficio bruto',
    Runway: 'Runway',
    Forecast: 'Pronóstico',
    'On track': 'En camino',
    'Warehouse map': 'Mapa de almacén',
    Ready: 'Listo',
    Picking: 'Picking',
    Inbound: 'Entrante',
    'Picking queue': 'Cola de picking',
    '24 tasks in progress': '24 tareas en progreso',
    'Stock movement flow': 'Flujo de movimiento de stock',
    units: 'unidades',
  },
  zh: {
    'Loading...': '加载中...',
    'Accounting dashboard': '会计仪表板',
    Revenue: '收入',
    Expenses: '支出',
    'Net profit': '净利润',
    'Cash balance': '现金余额',
    '+4.8% vs previous month': '较上月增加 4.8%',
    'Tax position': '税务状况',
    'GST/HST payable snapshot': 'GST/HST 应付快照',
    'Financial status': '财务状况',
    'Current ratio: 1.9': '流动比率：1.9',
    'AR days: 31': '应收账款天数：31',
    'AP days: 26': '应付账款天数：26',
    'AI business insights': 'AI 商业洞察',
    'Assistant active': '助手已激活',
    'Sales prediction model': '销售预测模型',
    Confidence: '置信度',
    'Model based on current ERP transactions': '基于当前 ERP 交易的模型',
    'Revenue momentum': '收入动能',
    '+12.4% projected for next 30 days': '未来 30 天预计增长 12.4%',
    'Margin pressure': '利润率压力',
    'Raw material cost up 3.1% this week': '本周原材料成本上涨 3.1%',
    'Receivables risk': '应收账款风险',
    '4 accounts likely to miss due date': '4 个账户可能错过到期日',
    success: '成功',
    warning: '警告',
    danger: '风险',
    'Expenses tracking': '费用跟踪',
    'Tax associated:': '相关税费：',
    'Month to date': '本月至今',
    'Expenses posted': '已入账费用',
    'Recoverable tax': '可回收税额',
    'GST/HST/PST/QST credits': 'GST/HST/PST/QST 税额抵免',
    'Policy variance': '政策偏差',
    '3 flagged': '3 项已标记',
    'Pending review': '待审核',
    'Inventory management': '库存管理',
    '2 low-stock alerts': '2 个低库存警报',
    SKUs: 'SKU',
    'On hand': '现有',
    'Inventory value': '库存价值',
    'Stock:': '库存：',
    'Min:': '最低：',
    'Invoices module': '发票模块',
    '112 open': '112 张未结',
    Invoice: '发票',
    Client: '客户',
    Total: '总计',
    Status: '状态',
    Draft: '草稿',
    Paid: '已支付',
    Overdue: '逾期',
    'BOM summary': 'BOM 摘要',
    '12 components linked to cost rollup': '12 个组件关联到成本汇总',
    '8 components linked to lot traceability': '8 个组件关联到批次追溯',
    'Capacity usage': '产能使用率',
    '84% this shift': '本班次 84%',
    'Production orders': '生产工单',
    Running: '运行中',
    Queued: '排队中',
    'Final check': '最终检查',
    'Purchases module': '采购模块',
    '6 vendors active': '6 个活跃供应商',
    'Open POs': '未结采购单',
    'Approved value': '已批准金额',
    'Lead-time risk': '交期风险',
    Low: '低',
    'Status:': '状态：',
    Approved: '已批准',
    Received: '已接收',
    Pending: '待处理',
    'Reports and analytics': '报表与分析',
    'Profit and loss trend': '损益趋势',
    'Gross profit': '毛利润',
    Runway: '跑道',
    Forecast: '预测',
    'On track': '按计划进行',
    'Warehouse map': '仓库地图',
    Ready: '就绪',
    Picking: '拣货',
    Inbound: '入库',
    'Picking queue': '拣货队列',
    '24 tasks in progress': '24 项任务进行中',
    'Stock movement flow': '库存流动',
    units: '单位',
  },
  pa: {
    'Loading...': 'ਲੋਡ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    'Accounting dashboard': 'ਲੇਖਾਕਾਰੀ ਡੈਸ਼ਬੋਰਡ',
    Revenue: 'ਮਾਲੀਆ',
    Expenses: 'ਖਰਚੇ',
    'Net profit': 'ਸ਼ੁੱਧ ਲਾਭ',
    'Cash balance': 'ਨਕਦ ਬਕਾਇਆ',
    '+4.8% vs previous month': '+4.8% ਪਿਛਲੇ ਮਹੀਨੇ ਨਾਲੋਂ',
    'Tax position': 'ਟੈਕਸ ਸਥਿਤੀ',
    'GST/HST payable snapshot': 'GST/HST ਭੁਗਤਾਨਯੋਗ ਸਨੈਪਸ਼ਾਟ',
    'Financial status': 'ਵਿੱਤੀ ਸਥਿਤੀ',
    'Current ratio: 1.9': 'ਮੌਜੂਦਾ ਅਨੁਪਾਤ: 1.9',
    'AR days: 31': 'AR ਦਿਨ: 31',
    'AP days: 26': 'AP ਦਿਨ: 26',
    'AI business insights': 'AI ਕਾਰੋਬਾਰੀ ਸੂਝਾਂ',
    'Assistant active': 'ਸਹਾਇਕ ਸਰਗਰਮ',
    'Sales prediction model': 'ਵਿਕਰੀ ਪੂਰਵ ਅਨੁਮਾਨ ਮਾਡਲ',
    Confidence: 'ਭਰੋਸਾ',
    'Model based on current ERP transactions': 'ਮੌਜੂਦਾ ERP ਲੈਣ-ਦੇਣਾਂ ਅਧਾਰਿਤ ਮਾਡਲ',
    'Revenue momentum': 'ਮਾਲੀਆ ਗਤੀ',
    '+12.4% projected for next 30 days': 'ਅਗਲੇ 30 ਦਿਨਾਂ ਲਈ +12.4% ਅਨੁਮਾਨਿਤ',
    'Margin pressure': 'ਮਾਰਜਿਨ ਦਬਾਅ',
    'Raw material cost up 3.1% this week': 'ਇਸ ਹਫਤੇ ਕੱਚੇ ਮਾਲ ਦੀ ਲਾਗਤ 3.1% ਵਧੀ',
    'Receivables risk': 'ਪ੍ਰਾਪਤੀਆਂ ਦਾ ਜੋਖਮ',
    '4 accounts likely to miss due date': '4 ਖਾਤਿਆਂ ਵੱਲੋਂ ਮਿਆਦ ਗੁਆਉਣ ਦੀ ਸੰਭਾਵਨਾ',
    success: 'ਸਫਲਤਾ',
    warning: 'ਚੇਤਾਵਨੀ',
    danger: 'ਖ਼ਤਰਾ',
    'Expenses tracking': 'ਖਰਚਾ ਟ੍ਰੈਕਿੰਗ',
    'Tax associated:': 'ਸਬੰਧਿਤ ਟੈਕਸ:',
    'Month to date': 'ਇਸ ਮਹੀਨੇ ਤੱਕ',
    'Expenses posted': 'ਪੋਸਟ ਕੀਤੇ ਖਰਚੇ',
    'Recoverable tax': 'ਵਸੂਲਯੋਗ ਟੈਕਸ',
    'GST/HST/PST/QST credits': 'GST/HST/PST/QST ਕਰੈਡਿਟ',
    'Policy variance': 'ਨੀਤੀ ਅੰਤਰ',
    '3 flagged': '3 ਚਿੰਨ੍ਹਿਤ',
    'Pending review': 'ਸਮੀਖਿਆ ਬਕਾਇਆ',
    'Inventory management': 'ਇਨਵੈਂਟਰੀ ਪ੍ਰਬੰਧਨ',
    '2 low-stock alerts': '2 ਘੱਟ-ਸਟਾਕ ਚੇਤਾਵਨੀਆਂ',
    SKUs: 'SKU',
    'On hand': 'ਮੌਜੂਦ',
    'Inventory value': 'ਇਨਵੈਂਟਰੀ ਮੁੱਲ',
    'Stock:': 'ਸਟਾਕ:',
    'Min:': 'ਘੱਟੋ-ਘੱਟ:',
    'Invoices module': 'ਇਨਵੌਇਸ ਮੋਡੀਊਲ',
    '112 open': '112 ਖੁੱਲ੍ਹੀਆਂ',
    Invoice: 'ਇਨਵੌਇਸ',
    Client: 'ਕਲਾਇੰਟ',
    Total: 'ਕੁੱਲ',
    Status: 'ਸਥਿਤੀ',
    Draft: 'ਡਰਾਫਟ',
    Paid: 'ਭੁਗਤਾਨ ਕੀਤਾ',
    Overdue: 'ਮਿਆਦ ਤੋਂ ਪਾਰ',
    'BOM summary': 'BOM ਸੰਖੇਪ',
    '12 components linked to cost rollup': 'ਲਾਗਤ ਰੋਲਅਪ ਨਾਲ ਜੁੜੇ 12 ਹਿੱਸੇ',
    '8 components linked to lot traceability': 'ਲਾਟ ਟ੍ਰੇਸਬਿਲਟੀ ਨਾਲ ਜੁੜੇ 8 ਹਿੱਸੇ',
    'Capacity usage': 'ਸਮਰੱਥਾ ਦੀ ਵਰਤੋਂ',
    '84% this shift': 'ਇਸ ਸ਼ਿਫਟ ਵਿੱਚ 84%',
    'Production orders': 'ਉਤਪਾਦਨ ਆਰਡਰ',
    Running: 'ਚੱਲ ਰਿਹਾ',
    Queued: 'ਕਤਾਰ ਵਿੱਚ',
    'Final check': 'ਅੰਤਿਮ ਜਾਂਚ',
    'Purchases module': 'ਖਰੀਦ ਮੋਡੀਊਲ',
    '6 vendors active': '6 ਵਿਕਰੇਤਾ ਸਰਗਰਮ',
    'Open POs': 'ਖੁੱਲ੍ਹੇ PO',
    'Approved value': 'ਮੰਜ਼ੂਰ ਕੀਤੀ ਕੀਮਤ',
    'Lead-time risk': 'ਲੀਡ ਟਾਈਮ ਜੋਖਮ',
    Low: 'ਘੱਟ',
    'Status:': 'ਸਥਿਤੀ:',
    Approved: 'ਮੰਜ਼ੂਰਸ਼ੁਦਾ',
    Received: 'ਪ੍ਰਾਪਤ',
    Pending: 'ਬਕਾਇਆ',
    'Reports and analytics': 'ਰਿਪੋਰਟਾਂ ਅਤੇ ਵਿਸ਼ਲੇਸ਼ਣ',
    'Profit and loss trend': 'ਲਾਭ-ਨੁਕਸਾਨ ਰੁਝਾਨ',
    'Gross profit': 'ਕੁੱਲ ਲਾਭ',
    Runway: 'ਰਨਵੇ',
    Forecast: 'ਭਵਿੱਖਬਾਣੀ',
    'On track': 'ਟ੍ਰੈਕ ’ਤੇ',
    'Warehouse map': 'ਵੇਅਰਹਾਊਸ ਨਕਸ਼ਾ',
    Ready: 'ਤਿਆਰ',
    Picking: 'ਚੁਣਾਈ',
    Inbound: 'ਅੰਦਰ ਆਉਂਦਾ',
    'Picking queue': 'ਚੁਣਾਈ ਕਤਾਰ',
    '24 tasks in progress': '24 ਕੰਮ ਚੱਲ ਰਹੇ ਹਨ',
    'Stock movement flow': 'ਸਟਾਕ ਮੂਵਮੈਂਟ ਪ੍ਰਵਾਹ',
    units: 'ਇਕਾਈਆਂ',
  },
  ar: {
    'Loading...': 'جارٍ التحميل...',
    'Accounting dashboard': 'لوحة المحاسبة',
    Revenue: 'الإيرادات',
    Expenses: 'المصروفات',
    'Net profit': 'صافي الربح',
    'Cash balance': 'الرصيد النقدي',
    '+4.8% vs previous month': '+4.8% مقارنة بالشهر السابق',
    'Tax position': 'الوضع الضريبي',
    'GST/HST payable snapshot': 'ملخص ضريبة GST/HST المستحقة',
    'Financial status': 'الوضع المالي',
    'Current ratio: 1.9': 'النسبة الحالية: 1.9',
    'AR days: 31': 'أيام الذمم المدينة: 31',
    'AP days: 26': 'أيام الذمم الدائنة: 26',
    'AI business insights': 'رؤى أعمال الذكاء الاصطناعي',
    'Assistant active': 'المساعد نشط',
    'Sales prediction model': 'نموذج توقع المبيعات',
    Confidence: 'الثقة',
    'Model based on current ERP transactions': 'نموذج مبني على معاملات ERP الحالية',
    'Revenue momentum': 'زخم الإيرادات',
    '+12.4% projected for next 30 days': '+12.4% متوقعة خلال الثلاثين يومًا القادمة',
    'Margin pressure': 'ضغط الهوامش',
    'Raw material cost up 3.1% this week': 'ارتفعت تكلفة المواد الخام بنسبة 3.1% هذا الأسبوع',
    'Receivables risk': 'مخاطر الذمم المدينة',
    '4 accounts likely to miss due date': '4 حسابات يُحتمل أن تفوت تاريخ الاستحقاق',
    success: 'نجاح',
    warning: 'تحذير',
    danger: 'خطر',
    'Expenses tracking': 'تتبع المصروفات',
    'Tax associated:': 'الضريبة المرتبطة:',
    'Month to date': 'منذ بداية الشهر',
    'Expenses posted': 'المصروفات المرحلة',
    'Recoverable tax': 'ضريبة قابلة للاسترداد',
    'GST/HST/PST/QST credits': 'أرصدة GST/HST/PST/QST',
    'Policy variance': 'انحراف السياسة',
    '3 flagged': '3 حالات معلمة',
    'Pending review': 'بانتظار المراجعة',
    'Inventory management': 'إدارة المخزون',
    '2 low-stock alerts': '2 تنبيهات انخفاض مخزون',
    SKUs: 'SKU',
    'On hand': 'المتوفر',
    'Inventory value': 'قيمة المخزون',
    'Stock:': 'المخزون:',
    'Min:': 'الحد الأدنى:',
    'Invoices module': 'وحدة الفواتير',
    '112 open': '112 مفتوحة',
    Invoice: 'فاتورة',
    Client: 'عميل',
    Total: 'الإجمالي',
    Status: 'الحالة',
    Draft: 'مسودة',
    Paid: 'مدفوع',
    Overdue: 'متأخر',
    'BOM summary': 'ملخص BOM',
    '12 components linked to cost rollup': '12 مكونًا مرتبطة بتجميع التكلفة',
    '8 components linked to lot traceability': '8 مكونات مرتبطة بتتبع الدفعات',
    'Capacity usage': 'استخدام الطاقة',
    '84% this shift': '84% في هذه الوردية',
    'Production orders': 'أوامر الإنتاج',
    Running: 'قيد التشغيل',
    Queued: 'في قائمة الانتظار',
    'Final check': 'التحقق النهائي',
    'Purchases module': 'وحدة المشتريات',
    '6 vendors active': '6 موردين نشطين',
    'Open POs': 'أوامر شراء مفتوحة',
    'Approved value': 'القيمة المعتمدة',
    'Lead-time risk': 'مخاطر المهلة',
    Low: 'منخفض',
    'Status:': 'الحالة:',
    Approved: 'موافق عليه',
    Received: 'مستلم',
    Pending: 'قيد الانتظار',
    'Reports and analytics': 'التقارير والتحليلات',
    'Profit and loss trend': 'اتجاه الأرباح والخسائر',
    'Gross profit': 'إجمالي الربح',
    Runway: 'المدرج',
    Forecast: 'التوقع',
    'On track': 'على المسار',
    'Warehouse map': 'خريطة المستودع',
    Ready: 'جاهز',
    Picking: 'الالتقاط',
    Inbound: 'وارد',
    'Picking queue': 'قائمة الالتقاط',
    '24 tasks in progress': '24 مهمة قيد التنفيذ',
    'Stock movement flow': 'تدفق حركة المخزون',
    units: 'وحدات',
  },
  tl: {
    'Loading...': 'Naglo-load...',
    'Accounting dashboard': 'Dashboard ng accounting',
    Revenue: 'Kita',
    Expenses: 'Mga gastos',
    'Net profit': 'Netong kita',
    'Cash balance': 'Balanse ng cash',
    '+4.8% vs previous month': '+4.8% kumpara sa nakaraang buwan',
    'Tax position': 'Posisyon sa buwis',
    'GST/HST payable snapshot': 'Snapshot ng GST/HST payable',
    'Financial status': 'Katayuang pinansyal',
    'Current ratio: 1.9': 'Kasalukuyang ratio: 1.9',
    'AR days: 31': 'Mga araw sa AR: 31',
    'AP days: 26': 'Mga araw sa AP: 26',
    'AI business insights': 'Mga insight sa negosyo ng AI',
    'Assistant active': 'Aktibo ang assistant',
    'Sales prediction model': 'Modelo ng prediksyon sa benta',
    Confidence: 'Kumpiyansa',
    'Model based on current ERP transactions':
      'Modelong batay sa kasalukuyang mga transaksyon sa ERP',
    'Revenue momentum': 'Momentum ng kita',
    '+12.4% projected for next 30 days': '+12.4% na inaasahan sa susunod na 30 araw',
    'Margin pressure': 'Presyon sa margin',
    'Raw material cost up 3.1% this week':
      'Tumaas ng 3.1% ang halaga ng hilaw na materyales ngayong linggo',
    'Receivables risk': 'Panganib sa koleksyon',
    '4 accounts likely to miss due date': '4 na account ang malamang na lumampas sa due date',
    success: 'tagumpay',
    warning: 'babala',
    danger: 'panganib',
    'Expenses tracking': 'Pagsubaybay sa gastos',
    'Tax associated:': 'Kaugnay na buwis:',
    'Month to date': 'Buwan hanggang ngayon',
    'Expenses posted': 'Na-post na mga gastos',
    'Recoverable tax': 'Mababawing buwis',
    'GST/HST/PST/QST credits': 'Mga credit sa GST/HST/PST/QST',
    'Policy variance': 'Paglihis sa patakaran',
    '3 flagged': '3 na-flag',
    'Pending review': 'Nakabinbing pagsusuri',
    'Inventory management': 'Pamamahala ng imbentaryo',
    '2 low-stock alerts': '2 alerto sa mababang stock',
    SKUs: 'Mga SKU',
    'On hand': 'Naka-stock',
    'Inventory value': 'Halaga ng imbentaryo',
    'Stock:': 'Stock:',
    'Min:': 'Min:',
    'Invoices module': 'Module ng invoice',
    '112 open': '112 bukas',
    Invoice: 'Invoice',
    Client: 'Kliyente',
    Total: 'Kabuuan',
    Status: 'Katayuan',
    Draft: 'Draft',
    Paid: 'Bayad',
    Overdue: 'Lampas na sa due date',
    'BOM summary': 'Buod ng BOM',
    '12 components linked to cost rollup': '12 component na naka-link sa cost rollup',
    '8 components linked to lot traceability': '8 component na naka-link sa lot traceability',
    'Capacity usage': 'Paggamit ng kapasidad',
    '84% this shift': '84% sa shift na ito',
    'Production orders': 'Mga order sa produksyon',
    Running: 'Tumatakbo',
    Queued: 'Nakapila',
    'Final check': 'Panghuling pagsusuri',
    'Purchases module': 'Module ng pagbili',
    '6 vendors active': '6 na aktibong vendor',
    'Open POs': 'Bukas na mga PO',
    'Approved value': 'Naaprubahang halaga',
    'Lead-time risk': 'Panganib sa lead time',
    Low: 'Mababa',
    'Status:': 'Katayuan:',
    Approved: 'Naaprubahan',
    Received: 'Natanggap',
    Pending: 'Nakabinbin',
    'Reports and analytics': 'Mga ulat at analytics',
    'Profit and loss trend': 'Trend ng kita at lugi',
    'Gross profit': 'Kabuuang kita',
    Runway: 'Runway',
    Forecast: 'Pagtataya',
    'On track': 'Nasa tamang landas',
    'Warehouse map': 'Mapa ng bodega',
    Ready: 'Handa',
    Picking: 'Picking',
    Inbound: 'Papasok',
    'Picking queue': 'Pila ng picking',
    '24 tasks in progress': '24 na gawain ang isinasagawa',
    'Stock movement flow': 'Daloy ng paggalaw ng stock',
    units: 'mga yunit',
  },
};

export function usePreviewCopy() {
  const { language } = useLanguage();
  const locale = PREVIEW_COPY[language] ? language : 'en';
  const active = PREVIEW_COPY[locale];
  const fallback = PREVIEW_COPY.en;

  return (key) => active[key] || fallback[key] || key;
}
