const siteContentFr = {
  locale: 'fr',
  localeLabel: 'Francais',
  labels: {
    menu: 'Menu',
    bookDemo: 'Presentation guidee',
    tryDemo: 'Ouvrir l espace',
    getTechnicalBrief: 'Contacter l equipe',
    reviewResources: 'Voir les ressources',
    language: 'Langue',
    requestQuote: 'Parler aux ventes',
  },
  navItems: [
    { label: 'Accueil', path: '/' },
    { label: 'Produit', path: '/product' },
    { label: 'Tarifs', path: '/pricing' },
    { label: 'Ressources', path: '/resources' },
    { label: 'Securite', path: '/security' },
    { label: 'A propos', path: '/about' },
    { label: 'Contact', path: '/contact' },
  ],
  brand: {
    name: 'ZANVROX',
    tagline: 'Controle ERP integre pour les PME canadiennes',
    oneLiner: 'Finance, operations, conformite canadienne et paie dans une seule pile ERP controlee.',
  },
  pages: {
    home: {
      heroKicker: 'ERP canadien pour la finance, les operations et l auditabilite',
      heroTitle: 'Pilotez la finance et les operations dans un ERP maitrise au lieu de cinq outils deconnectes.',
      heroSubtitle:
        'ZANVROX aide les PME canadiennes a centraliser la comptabilite, la facturation, les achats, l inventaire, la production, les approbations et la conformite sans projet d implementation lourd.',
      heroPrimaryCta: { label: 'Voir l apercu produit', path: '/#product-overview' },
      heroSecondaryCta: { label: 'Ouvrir l espace d evaluation', path: '/resources#demo-environment' },
      heroPreview: {
        title: 'Apercu fiscal et controle',
        caption: 'En direct dans l ERP',
        callouts: [
          { status: 'ready', text: 'Reporting GST/HST + PST/QST' },
          { status: 'ready', text: 'Piste d audit et approbations' },
        ],
      },
      video: {
        title: 'Presentation produit avec un vrai contexte de workflow',
        subtitle: 'Un apercu rapide de la finance, des operations, des flux fiscaux canadiens et de la preparation de la paie.',
        windowLabel: 'Video produit',
        duration: '90 sec',
        overlayLabel: 'Voir la presentation produit',
        fallbackLabel: 'Apercu de l affiche disponible',
        hasRealVideo: true,
        chapters: [
          'Comptabilite et facturation',
          'Inventaire et entrepot',
          'Planification de la production',
          'Tableau de bord fiscal',
          'Espace paie',
          'Rapports et approbations',
        ],
        primaryCta: { label: 'Explorer le produit', path: '/product' },
        secondaryCta: { label: 'Ouvrir l espace d evaluation', path: '/resources#demo-environment' },
      },
      trustSignals: [
        'Les workflows officiels soutenus par les fournisseurs restent disponibles lorsque c est necessaire.',
        'Les changements sont gouvernes par des approbations et une piste d audit.',
        'Un parcours de configuration autonome existe pour les petites equipes avec une implementation guidee en option.',
        'Une posture de conformite canadienne sans surpromesse marketing.',
      ],
      statusBadges: [
        { status: 'ready', text: 'Comptabilite, facturation, depenses et reporting' },
        { status: 'ready', text: 'Inventaire, entrepot et workflows BOM' },
        { status: 'ready', text: 'Support des workflows fiscaux canadiens' },
        { status: 'ready', text: 'Add-on paie avec espace de fin d annee' },
        { status: 'locked', text: 'Controles de gouvernance et d auditabilite' },
        { status: 'ready', text: 'Parcours d onboarding autonome' },
      ],
      evaluationPath: {
        eyebrow: 'Tunnel axe produit',
        title: 'Evaluez sans reserver une reunion d abord',
        subtitle: 'Le site est concu pour reduire les appels inutiles et permettre aux equipes de se qualifier seules.',
        cards: [
          {
            title: '1. Voir l apercu',
            body: 'Commencez par la video produit pour comprendre comment la finance, les operations, la fiscalite et la paie s articulent.',
          },
          {
            title: '2. Explorer le produit',
            body: 'Passez en revue les groupes fonctionnels, les captures et les controles de gouvernance par module et par processus metier.',
          },
          {
            title: '3. Ouvrir l espace d evaluation',
            body: 'Utilisez l espace navigateur avec des donnees fictives pour valider la navigation, l adequation des roles et la couverture des workflows.',
          },
          {
            title: '4. Demander de l aide seulement si necessaire',
            body: 'Utilisez le formulaire de contact ou de demo en option uniquement si votre equipe a une question d evaluation concrete.',
          },
        ],
      },
      screenshots: {
        eyebrow: 'Ecrans et workflows',
        title: 'Des ecrans concus pour montrer une vraie couverture operationnelle',
        subtitle:
          'Chaque section ci-dessous est prete pour de vraies captures et utilise des apercus produit lorsqu une capture finale n est pas encore disponible.',
        items: [
          {
            title: 'Tableau de bord fiscal canadien',
            body: 'Suivez l etat de preparation des depots, les familles de taxes et les controles de cloture depuis une seule vue finance.',
            previewType: 'reports',
            imageKey: 'taxDashboard',
            imageAlt: 'Tableau de bord fiscal canadien dans ZANVROX ERP',
          },
          {
            title: 'Gestion des stocks',
            body: 'Consultez les positions de stock, les mouvements d entrepot et la visibilite par lot sans quitter l ERP.',
            previewType: 'inventory',
          },
          {
            title: 'Planification de la production',
            body: 'Consultez les ordres de production lies au BOM, la consommation matiere et l avancement de l execution dans une seule surface.',
            previewType: 'production',
          },
          {
            title: 'Reporting financier',
            body: 'Passez de l activite operationnelle au reporting de gestion sans recoller plusieurs outils.',
            previewType: 'accounting',
          },
        ],
      },
      howItWorks: {
        eyebrow: 'Onboarding autonome',
        title: 'Demarrez en six etapes guidees',
        subtitle: 'Le produit est concu pour qu une equipe dirigee par ses fondateurs puisse se repérer sans projet d onboarding lourd.',
        steps: [
          { icon: '1', title: 'Creer l organisation', bullets: ['Demarrer votre espace', 'Definir les bases de l entite legale'] },
          { icon: '2', title: 'Selectionner le pays', bullets: ['Choisir le Canada', 'Charger les valeurs par defaut specifiques au pays'] },
          { icon: '3', title: 'Choisir un modele sectoriel', bullets: ['Choisir un modele de depart', 'Reduire la friction de configuration'] },
          { icon: '4', title: 'Configurer les taxes', bullets: ['Definir les familles de taxes', 'Confirmer la logique provinciale et les valeurs par defaut'] },
          { icon: '5', title: 'Importer clients et fournisseurs', bullets: ['Importer les donnees maitres', 'Utiliser des modeles et la validation'] },
          { icon: '6', title: 'Creer la premiere facture', bullets: ['Valider le flux operationnel', 'Passer a l utilisation quotidienne'] },
        ],
      },
      compliance: {
        eyebrow: 'Posture canadienne',
        title: 'Concu pour la credibilite, pas pour l effet d annonce',
        subtitle: 'Le site explique ce qui est controle, ce qui est automatise et ce qui exige encore une revue.',
        bullets: [
          'Les workflows fiscaux canadiens sont presentes avec une posture explicite de depot et d auditabilite.',
          'La paie est positionnee comme un add-on separe avec un perimetre clair et un niveau de preparation precise par juridiction.',
          'Les approbations, la gouvernance et les attentes de support sont affirmees directement au lieu d etre enterrees dans des appels commerciaux.',
        ],
        coverageLabel: 'Posture commerciale actuelle',
        coverage: 'Meilleur fit pour les PME canadiennes de 10 a 50 employes',
        note: 'Les workflows officiels soutenus par les fournisseurs restent disponibles lorsqu une promesse de niveau entreprise plus forte ne serait pas justifiee.',
        provinces: ['ON', 'QC', 'AB', 'BC', 'MB', 'SK', 'NS', 'NB'],
      },
      included: {
        eyebrow: 'Ce qui est integre',
        title: 'Une seule pile pour la finance et les operations',
        subtitle: 'L enjeu n est pas d afficher plus de fonctions sur le papier. L enjeu est d avoir moins de workflows fractures dans la pratique.',
        items: [
          'Comptabilite, facturation, depenses et reporting financier',
          'Achats, inventaire, entrepot et bases de production',
          'Approbations, gouvernance et piste d audit operationnelle',
          'Workflows de conformite canadienne et support de l add-on paie',
          'Multi-company et gouvernance avancee pour le perimetre d entreprise',
          'Intelligence ERP et assistance AI avec posture controlee',
        ],
      },
      executiveSnapshot: {
        badge: 'Modele operationnel',
        title: 'Concu pour l autoevaluation d abord, l aide humaine ensuite',
        subtitle: 'C est un site axe produit pour un ERP serieux, pas une brochure qui force chaque prospect a prendre un appel.',
        metrics: [
          { label: 'ICP principal', value: '10-50', note: 'Employes de PME canadiennes' },
          { label: 'Posture de support', value: 'Priorite a l email', note: 'Delais de reponse clairs par plan' },
          { label: 'Posture d onboarding', value: 'Configuration autonome', note: 'Implementation guidee disponible en option' },
        ],
      },
      positioning: {
        eyebrow: 'Pourquoi les equipes changent',
        title: 'Reduire la fragmentation entre finance, operations et conformite',
        subtitle: 'La proposition de valeur repose sur le controle, la visibilite et moins de transferts entre systemes.',
        cards: [
          {
            role: 'Finance',
            headline: 'Cloturez avec moins de systemes deconnectes.',
            points: [
              'Comptabilite, facturation, depenses et rapports dans un seul systeme.',
              'Limites de support claires et controles lies aux periodes.',
              'Posture de conformite canadienne sans surpromettre l automatisation.',
            ],
          },
          {
            role: 'Operations',
            headline: 'Gardez le stock, les achats et la production synchronises.',
            points: [
              'Les workflows d inventaire et d entrepot sont relies a la finance.',
              'Les bases BOM et production existent sans middleware supplementaire.',
              'Des signaux de revue operationnelle et de gouvernance existent la ou c est necessaire.',
            ],
          },
          {
            role: 'Management',
            headline: 'Obtenez un meilleur support a la decision.',
            points: [
              'Moins de rapprochements manuels entre outils.',
              'Les attentes de support et le perimetre d onboarding sont explicites.',
              'Une meilleure qualification des leads avant de mobiliser du temps interne.',
            ],
          },
          {
            role: 'IT / Ops',
            headline: 'Adoptez avec un perimetre discipline.',
            points: [
              'Un sequencement clair d implementation pour les petites equipes.',
              'Des changements gouvernes et des workflows auditables.',
              'Une couche marketing compatible site statique avec des metadonnees structurees.',
            ],
          },
        ],
      },
      technical: {
        eyebrow: 'Modele de support et d onboarding',
        title: 'Self-service par defaut, aide guidee quand elle compte',
        subtitle: 'Le site fixe les attentes en amont pour que les petites equipes sachent ce qui se passe apres l inscription.',
        items: [
          'Finance Core inclut un onboarding autonome et un support email avec reponse sous 48 h.',
          'Operations ajoute un support email prioritaire avec reponse sous 24 h.',
          'Enterprise inclut une assistance d onboarding et un canal de support direct.',
        ],
      },
      supportModel: {
        title: 'Attentes de support par plan',
        subtitle: 'Le support est defini directement afin que l evaluation reste realiste.',
        tiers: [
          { name: 'Finance Core', body: 'Support email, reponse sous 48 h, accompagnement d onboarding autonome.' },
          { name: 'Operations', body: 'Support email prioritaire, reponse sous 24 h, accompagnement operationnel renforce.' },
          { name: 'Enterprise', body: 'Onboarding dedie, canal de support direct et assistance de deploiement cadree.' },
        ],
      },
      demoEnvironment: {
        title: 'Ouvrir l espace d evaluation ZANVROX',
        subtitle: 'Utilisez un espace navigateur avec des donnees fictives avant de demander une presentation guidee.',
        emailLabel: 'Utilisateur de demo',
        emailValue: 'Use your work email',
        passwordLabel: 'Mot de passe',
        passwordValue: 'Set during signup',
        note: 'Evaluation navigateur uniquement. Cet espace reste separe de la planification d implementation et des attentes de production.',
        cta: { label: 'Ouvrir l espace d evaluation', path: '/resources#demo-environment' },
      },
      faq: {
        eyebrow: 'FAQ',
        title: 'Les questions que les equipes posent avant d y consacrer du temps',
        items: [
          {
            question: 'Peut-on evaluer ZANVROX sans reserver une demo d abord ?',
            answer: 'Oui. Le parcours prevu est de voir l apercu, d explorer le produit, d ouvrir l espace d evaluation et de demander de l aide seulement si votre equipe en a besoin.',
          },
          {
            question: 'La paie est-elle incluse dans les plans de base ?',
            answer: 'Non. La paie est un add-on separe avec une tarification distincte afin que les equipes centrees sur la finance ne la paient pas par defaut.',
          },
          {
            question: 'Faut-il un projet d onboarding payant ?',
            answer: 'Non. La configuration autonome est le parcours par defaut. Guided Implementation est disponible comme package payant optionnel lorsque votre equipe veut de l aide pour la configuration et l import des donnees.',
          },
          {
            question: 'Quel support faut-il attendre ?',
            answer: 'Finance Core inclut un support email sous 48 h, Operations inclut un support email prioritaire sous 24 h et Enterprise inclut une aide d onboarding ainsi qu un canal de support direct.',
          },
        ],
      },
      cta: {
        title: 'Commencez par le produit, pas par un appel commercial',
        subtitle: 'Explorez d abord le produit et les tarifs. Contactez l equipe lorsque vous avez une question concrete de deploiement, de paie ou d integration.',
        primary: { label: 'Explorer le produit', path: '/product' },
        secondary: { label: 'Voir les tarifs', path: '/pricing' },
      },
    },
    product: {
      heroKicker: 'Perimetre produit integre',
      heroTitle: 'Couverture produit pour la finance, les operations, la conformite et la paie.',
      heroSubtitle:
        'ZANVROX est positionne comme une pile ERP controlee pour les PME canadiennes qui ont besoin de visibilite operationnelle sans theatre d entreprise.',
      heroPrimaryCta: { label: 'Voir les tarifs', path: '/pricing' },
      heroSecondaryCta: { label: 'Ouvrir l espace d evaluation', path: '/resources#demo-environment' },
      heroPreview: {
        title: 'Apercu operations',
        type: 'inventory',
        caption: 'Une seule couche de donnees operationnelles',
        callouts: [
          { status: 'ready', text: 'Inventaire, entrepot, BOM, production' },
          { status: 'ready', text: 'Gouvernance et approbations' },
        ],
      },
      pillars: {
        title: 'Quatre piliers produit',
        subtitle: 'Le site explique le produit autour des workflows, pas de puces de fonctions deconnectees.',
        items: [
          { title: 'Noyau finance', body: 'Comptabilite, facturation, depenses, visibilite bancaire et reporting.' },
          { title: 'Operations', body: 'Inventaire, entrepot, BOM, bases de production et approbations.' },
          { title: 'Conformite canadienne', body: 'Workflows fiscaux, add-on paie, support des remises et posture de fin d annee.' },
          { title: 'Gouvernance', body: 'Auditabilite, approbations, limites de controle et chemin d expansion multi-company.' },
        ],
      },
      showcase: {
        title: 'Zones produit a evaluer visuellement',
        subtitle: 'Ce sont les ecrans que la plupart des equipes veulent inspecter avant d investir plus de temps dans des conversations commerciales approfondies.',
        items: [
          {
            title: 'Tableau de bord fiscal',
            body: 'Montre la posture de depot, l avancement de la conformite et la visibilite des workflows de support.',
            previewType: 'reports',
            imageKey: 'taxDashboard',
            imageAlt: 'Tableau de bord fiscal dans ZANVROX ERP',
          },
          {
            title: 'Controle des stocks',
            body: 'Montre la visibilite du stock, le routage d entrepot et les signaux de preparation operationnelle.',
            previewType: 'inventory',
          },
          {
            title: 'Planification de la production',
            body: 'Montre la planification operationnelle liee au BOM et l avancement de l execution.',
            previewType: 'production',
          },
          {
            title: 'Reporting financier',
            body: 'Montre un reporting connecte de l activite operationnelle vers la finance.',
            previewType: 'reports',
          },
        ],
      },
      stacks: [
        {
          title: 'Finance et operations integrees',
          subtitle: 'Concu pour reduire les transferts entre outils dans le segment des 10-50 employes.',
          items: [
            'La comptabilite et la facturation vivent dans le meme systeme que les achats et les depenses.',
            'Les donnees d inventaire, d entrepot et de BOM restent liees a l ecriture financiere.',
            'Les approbations et la gouvernance peuvent etre ajoutees sans outils operationnels distincts.',
          ],
        },
        {
          title: 'Posture de controle canadienne',
          subtitle: 'Concu pour etre credible dans un contexte operationnel canadien.',
          items: [
            'Le support fiscal canadien est explique avec un langage de workflow concret.',
            'La paie reste un add-on avec un perimetre et une tarification explicites.',
            'Les promesses sont alignees sur la posture reelle de gouvernance, de preparation et de revue.',
          ],
        },
      ],
      onboarding: {
        title: 'Comment la configuration autonome fonctionne en pratique',
        subtitle: 'La page produit rappelle que l onboarding est guide dans le produit, pas masque derriere du conseil par defaut.',
        steps: [
          { number: '1', title: 'Creer l organisation', body: 'Creez votre espace et partez d une base operationnelle propre.' },
          { number: '2', title: 'Selectionner le Canada', body: 'Appliquez les valeurs par defaut specifiques au pays et les hypotheses de conformite.' },
          { number: '3', title: 'Choisir un modele sectoriel', body: 'Partez d une base pratique au lieu de tout configurer a zero.' },
          { number: '4', title: 'Configurer les taxes', body: 'Confirmez le routage fiscal, les enregistrements et les controles financiers.' },
          { number: '5', title: 'Importer les donnees maitres', body: 'Importez clients, fournisseurs et enregistrements operationnels cles.' },
          { number: '6', title: 'Executer la premiere transaction', body: 'Creez la premiere facture et validez le flux operationnel de bout en bout.' },
        ],
        note: 'Guided Implementation est disponible lorsque votre equipe souhaite de l aide pour la configuration, la revue du chart of accounts, l import des donnees et la formation.',
      },
      cta: {
        title: 'Verifiez si le perimetre produit correspond a votre entreprise aujourd hui',
        subtitle: 'Utilisez les tarifs et les ressources pour decider si vous avez besoin d une configuration autonome, d une implementation guidee ou d une conversation d entreprise.',
        primary: { label: 'Voir les tarifs', path: '/pricing' },
        secondary: { label: 'Contacter l equipe', path: '/contact' },
      },
    },
    pricing: {
      heroTitle: 'Tarifs pour des operations structurees et une expansion maitrisee.',
      heroSubtitle:
        'Commencez par un noyau de controle financier, etendez-vous aux operations lorsque la complexite augmente, puis passez a un deploiement personnalise seulement lorsque la structure multi-site, les approbations avancees, le support onboarding, les integrations ou la revue securite deviennent necessaires.',
      packagesTitle: 'Tarifs publics pour la finance, les operations et un deploiement guide',
      packagesSubtitle: 'Une tarification CAD transparente pour les equipes SMB canadiennes qui ont besoin de workflows structures aujourd hui et d un chemin credible vers un controle operationnel plus large avec le temps.',
      launchBadge: 'Facturation annuelle disponible',
      launchOfferLabel: 'Les abonnements annuels de base incluent un mois offert en facturation annuelle.',
      launchOfferNote: 'La tarification de la paie reste a l usage, et Guided Implementation est disponible lorsqu un deploiement plus structure est necessaire.',
      popularLabel: 'Bon fit pour 10-50 employes',
      priceSuffixMonthly: '/mois',
      billedMonthlyLabel: 'Facturation mensuelle',
      billedAnnuallyLabel: 'Facturation annuelle',
      fromLabel: 'A partir de',
      customLabel: 'Personnalise',
      includesLabel: 'Inclus',
      entitiesIncludedLabel: 'Perimetre commercial',
      usersIncludedLabel: 'Utilisateurs inclus',
      billingToggle: {
        monthly: 'Mensuel',
        annual: 'Annuel',
        annualBadge: '1 mois offert',
        helper: 'La facturation annuelle modifie seulement la duree de l abonnement de base. La paie reste facturee selon un forfait de base plus le nombre d employes.',
      },
      pricingNote:
        'Tous les prix sont en CAD. La paie est un add-on distinct. Les plans sont concus autour d operations structurees, de workflows controles, d auditabilite et d une conception produit attentive a la securite sans imposer trop tot un perimetre d entreprise. ZANVROX aide a organiser les workflows financiers, de paie et fiscaux, mais ne remplace pas les conseils comptables, juridiques ou fiscaux.',
      tiers: [
        {
          slug: 'finance-core',
          name: 'Finance Core',
          summary: 'Pour les entreprises qui ont besoin d une base finance disciplinee avec comptabilite, facturation, depenses, reporting et un chemin clair de configuration autonome.',
          entitiesLabel: 'Perimetre mono-societe',
          usersLabel: 'Jusqu a 3 utilisateurs',
          monthly: {
            kind: 'fixed',
            amount: 179,
            note: 'Inclut l accompagnement de configuration autonome, des workflows financiers controles et un support email avec reponse sous 48 h.',
          },
          annual: {
            kind: 'fixed',
            amount: 179,
            badge: '1 mois offert',
            note: 'Facture annuellement à CAD 1,969 pour l abonnement de base.',
            secondaryNote: 'La paie et un perimetre operationnel plus large restent distincts lorsque c est necessaire.',
          },
          included: [
            'Workflows comptables',
            'Facturation',
            'Capture des depenses',
            'Reporting financier',
            'Accompagnement de configuration autonome',
            'Support email (48 h)',
          ],
          ctaLabel: 'Consulter Finance Core',
        },
        {
          slug: 'operations',
          name: 'Operations',
          isPopular: true,
          summary: 'Pour les equipes qui ont besoin que la finance et les operations fonctionnent ensemble sur l inventaire, l entrepot, les bases de production et les approbations controlees.',
          entitiesLabel: 'Perimetre mono-societe',
          usersLabel: 'Jusqu a 10 utilisateurs',
          monthly: {
            kind: 'fixed',
            amount: 649,
            note: 'Inclut un support email prioritaire avec reponse sous 24 h pour les equipes avec une activite operationnelle plus forte.',
          },
          annual: {
            kind: 'fixed',
            amount: 649,
            badge: '1 mois offert',
            note: 'Facture annuellement à CAD 7,139 pour l abonnement de base.',
            secondaryNote: 'Recommande lorsque les operations demandent un controle plus strict sur le stock, les mouvements d entrepot, le BOM et les workflows de production.',
          },
          included: [
            'Tout ce qui est inclus dans Finance Core',
            'Controle des stocks',
            'Workflows d entrepot',
            'Production (BOM)',
            'Approbations et gouvernance',
            'Support email prioritaire (24 h)',
          ],
          ctaLabel: 'Consulter Operations',
        },
        {
          slug: 'enterprise',
          name: 'Personnalise',
          summary: 'Pour les equipes multi-sites qui ont besoin d approbations avancees, de revues securite, d onboarding personnalise, d integrations, de support dedie ou d un deploiement plus structure.',
          entitiesLabel: 'Perimetre multi-site ou personnalise',
          usersLabel: 'Perimetre utilisateurs personnalise',
          monthly: {
            kind: 'custom',
            label: 'Personnalise',
            note: 'Revue cadree pour un deploiement multi-site, une configuration guidee, des integrations, des besoins de gouvernance et une revue securite.',
          },
          annual: {
            kind: 'custom',
            label: 'Personnalise',
            note: 'Le tarif personnalise est defini directement selon la structure operationnelle, les besoins de deploiement et le contexte d implementation.',
          },
          included: [
            'Deploiement multi-site',
            'Gouvernance avancee',
            'Integrations',
            'Parcours de revue securite',
            'Implementation guidee et support de deploiement',
          ],
          ctaLabel: 'Demander une revue personnalisee',
        },
      ],
      payrollAddon: {
        title: 'Add-on paie',
        summary: 'Une tarification paie distincte garde l ERP de base commercialement clair tout en preservant le support de la paie canadienne pour les equipes qui en ont besoin.',
        priceLabel: 'CAD 59 / mois + CAD 6 / employe / mois',
        annualPriceLabel: 'CAD 59 / mois + CAD 6 / employe / mois',
        monthlyNote: 'Inclut les executions de paie canadiennes, le support des workflows de remises, les bulletins de paie, les dossiers et exports pour appuyer la revue de fin d annee, ainsi que l integration comptable. Un minimum mensuel peut s appliquer pendant le deploiement.',
        annualNote: 'L add-on paie conserve la meme structure tarifaire de base plus employe en annuel, sauf cadrage different.',
        included: [
          'Executions de paie canadiennes',
          'Support des workflows de remises',
          'Bulletins de paie',
          'Dossiers et exports pour appuyer la revue',
          'Integration comptable',
        ],
        ctaLabel: 'Poser une question sur la paie',
      },
      onboardingPackage: {
        title: 'Guided Implementation',
        summary: 'Configuration guidee optionnelle en une seule fois pour les equipes qui veulent un alignement operationnel, un deploiement assiste et un demarrage d implementation plus structure.',
        priceLabel: 'CAD 3,500 à 7,500 en une fois',
        included: [
          'Configuration systeme guidee',
          'Revue d alignement operationnel',
          'Revue du chart of accounts',
          'Configuration des taxes',
          'Accompagnement a l import des donnees',
          'Session de formation pour deploiement assiste',
        ],
        note: 'Optionnel. Les plans standard peuvent toujours commencer par une configuration autonome lorsqu un deploiement plus leger est approprie.',
        ctaLabel: 'Demander une configuration guidee',
      },
      supportTiers: {
        title: 'Structure de support',
        subtitle: 'Le support est indique publiquement afin que les equipes puissent evaluer la couverture operationnelle, les delais de reponse et la posture de deploiement en amont.',
        items: [
          { name: 'Finance Core', body: 'Support email avec reponse sous 48 h.' },
          { name: 'Operations', body: 'Support email prioritaire avec reponse sous 24 h.' },
          { name: 'Personnalise', body: 'Support au deploiement guide, canal direct et discussion d implementation cadree.' },
        ],
      },
      comparison: {
        title: 'Comparaison des plans',
        subtitle: 'Utilisez ce tableau pour decider si vous avez besoin d un controle financier structure, d operations connectees ou d un deploiement d entreprise personnalise.',
        featureLabel: 'Capacite',
        rows: [
          { label: 'Comptabilite', values: [true, true, true] },
          { label: 'Facturation', values: [true, true, true] },
          { label: 'Depenses', values: [true, true, true] },
          { label: 'Rapports financiers', values: [true, true, true] },
          { label: 'Inventaire', values: [false, true, true] },
          { label: 'Entrepot', values: [false, true, true] },
          { label: 'Production (BOM)', values: [false, true, true] },
          { label: 'Approbations et gouvernance', values: [false, true, true] },
          { label: 'Deploiement multi-site', values: [false, false, true] },
          { label: 'Approbations avancees', values: [false, true, true] },
          { label: 'Integrations', values: [false, false, true] },
          { label: 'Niveau de support', values: ['Email / 48 h', 'Email prioritaire / 24 h', 'Canal direct'] },
          { label: 'Assistance onboarding', values: ['Autonome', 'Autonome', 'Inclus'] },
          { label: 'Utilisateurs inclus', values: ['3', '10', 'Personnalise'] },
        ],
        notesTitle: 'Notes commerciales',
        notes: [
          'La paie est un add-on distinct.',
          'Guided Implementation est optionnel et facture a part pour les equipes qui veulent un deploiement plus structure.',
          'Personnalise est le bon parcours pour le perimetre multi-site, les integrations, la revue securite et le contexte d implementation guidee.',
          'Le modele commercial est concu pour preserver la transparence tout en soutenant des workflows controles et l auditabilite a mesure que les exigences augmentent.',
        ],
        annualNote: 'Les plans annuels de base incluent un mois offert.',
      },
      faq: {
        title: 'FAQ tarifs',
        subtitle: 'Reponses pour les equipes qui veulent se qualifier seules avant un appel.',
        items: [
          {
            question: 'Faut-il une demo avant de pouvoir commencer ?',
            answer: 'Non. Le parcours prevu est l autoevaluation d abord : voir l apercu, explorer le produit, consulter les tarifs et utiliser l espace d evaluation navigateur avant de demander une session guidee.',
          },
          {
            question: 'La paie est-elle incluse dans les plans ERP de base ?',
            answer: 'Non. La paie est vendue comme un add-on distinct avec un forfait mensuel de base plus un tarif par employe.',
          },
          {
            question: 'Guided Implementation est-il obligatoire ?',
            answer: 'Non. C est optionnel. Finance Core et Operations peuvent commencer avec une configuration autonome, tandis que Guided Implementation reste disponible pour les equipes qui veulent un deploiement plus structure.',
          },
          {
            question: 'Quel support est inclus avec chaque plan ?',
            answer: 'Finance Core inclut un support email sous 48 h, Operations inclut un support email prioritaire sous 24 h et Personnalise inclut une discussion de deploiement guidee ainsi qu un canal de support direct.',
          },
        ],
      },
      ctaPrimary: { label: 'Ouvrir l espace d evaluation', path: '/resources#demo-environment' },
      ctaSecondary: { label: 'Contacter pour un deploiement personnalise', path: '/contact' },
    },
    resources: {
      heroTitle: 'Ressources pour l evaluation produit, la revue securite et la planification du deploiement.',
      heroSubtitle:
        'Utilisez ces materiaux publics pour evaluer l adequation produit, la posture securite et les options d evaluation avant de demander une discussion plus approfondie.',
      sections: [
        {
          title: 'Apercu produit et ressources d evaluation',
          description: 'Consultez l apercu produit, la couverture des workflows et le modele d onboarding avant d investir du temps dans une evaluation plus poussée.',
          cta: 'Consulter le produit',
          path: '/product',
        },
        {
          title: 'Apercu securite',
          description: 'Consultez l isolation entre organisations, les controles d acces, les sous-traitants et les limites actuelles dans un seul apercu public.',
          cta: 'Consulter la securite',
          path: '/security',
        },
        {
          title: 'Espace d evaluation et revue produit guidee',
          description: 'Commencez par l espace d evaluation partage pour une premiere revue, puis contactez l equipe si vous avez besoin d une discussion produit plus structuree.',
          cta: 'Ouvrir l espace d evaluation',
          path: '/resources#demo-environment',
        },
        {
          title: 'Contact et documentation complementaire',
          description: 'Utilisez le parcours de contact pour les demandes securite ou compliance, les demandes de revue guidee ou des details supplementaires d evaluation.',
          cta: 'Contacter l equipe',
          path: '/contact',
        },
      ],
      demoEnvironment: {
        title: 'Espace d evaluation',
        subtitle: 'Un espace navigateur pour une premiere revue produit avec des donnees d exemple fictives.',
        accessTitle: 'Acces d evaluation partage',
        accessIntro: 'Un acces partage est disponible pour une premiere revue produit. Les equipes qui ont besoin d une evaluation plus profonde ou plus structuree peuvent contacter ZANVROX.',
        emailLabel: 'Utilisateur de l espace',
        emailValue: 'Use your work email',
        passwordLabel: 'Code d acces',
        passwordValue: 'Set during signup',
        note: 'Aucune installation n est requise. Cet espace est reserve a l evaluation, utilise des donnees d exemple fictives et n est pas destine a des donnees reelles d entreprise, d employes, de clients, de paie ou de finance.',
        guidance: [
          'Utilisez cet espace pour une premiere revue de la navigation, de la couverture des workflows et de l adequation generale du produit.',
          'Traitez cet environnement comme une surface d evaluation partagee et non comme un espace de production, de pilote ou de migration de donnees.',
          'Pour une revue plus approfondie, des questions securite/compliance ou une documentation complementaire, utilisez le parcours de contact apres l evaluation initiale.',
        ],
        cta: { label: 'Ouvrir l espace d evaluation', path: '/resources#demo-environment' },
      },
      sitemap: {
        title: 'Materiaux d evaluation',
        subtitle: 'Le site public est volontairement compact et concentre sur les materiaux les plus utiles pendant l evaluation initiale.',
        items: [
          'Apercu produit et couverture des workflows',
          'Tarification publique et modele d onboarding',
          'Apercu securite et posture actuelle des controles',
          'Espace d evaluation avec des donnees d exemple fictives',
          'Parcours de contact pour revue guidee et questions de suivi',
          'Informations legales de confidentialite et de conditions',
        ],
      },
      design: {
        title: 'Comment utiliser ces ressources',
        subtitle: 'Un parcours d evaluation simple pour les equipes qui veulent d abord verifier l adequation produit et n impliquer l equipe que lorsque plus de details sont necessaires.',
        directionTitle: 'Premiere revue produit',
        componentsTitle: 'Revue securite et compliance',
        statesTitle: 'Quand contacter l equipe',
        direction: [
          'Commencez par Produit, Tarifs et Ressources pour comprendre le perimetre, la posture d onboarding et l adequation commerciale.',
          'Utilisez l espace d evaluation pour une premiere revue pratique avec des donnees fictives uniquement.',
          'Considerez les materiaux publics comme une couche initiale de qualification avant de demander une discussion plus approfondie.',
        ],
        components: [
          'Utilisez l Apercu securite pour l isolation entre organisations, le controle d acces, les sous-traitants et les limites actuelles.',
          'Utilisez le parcours de contact pour les demandes securite/compliance ou pour demander une documentation complementaire.',
          'Gardez les questions d evaluation alignees avec le perimetre et les promesses actuellement publies.',
        ],
        states: [
          'Demandez une revue guidee du produit lorsque votre equipe a des questions concretes de workflow ou de deploiement.',
          'Contactez l equipe si vous avez besoin de plus de details que ceux fournis par les materiaux publics.',
          'Utilisez le parcours de contact existant pour demander un apercu securite et un suivi securite/compliance.',
        ],
      },
    },
    security: {
      heroTitle: 'Securite et architecture par conception.',
      heroSubtitle: 'Isolation entre organisations, acces de moindre privilege et comportement transactionnel auditable.',
      overview: {
        title: 'Apercu securite',
        subtitle: 'Un resume conservateur des controles actuellement visibles dans le produit et dans le flux de livraison.',
        description:
          'ZANVROX repose sur l isolation entre organisations, l acces selon les roles et une gestion imposee cote serveur pour les operations sensibles. Les declarations publiques de securite sont limitees aux controles effectivement en place aujourd hui et evitent toute promesse de certification ou de couverture qui n existe pas encore.',
        bullets: [
          'La posture securite est centree sur le moindre privilege, le cadrage par organisation et un comportement operationnel auditable.',
          'Les zones sensibles peuvent exiger une authentification renforcee avant l acces.',
          'L infrastructure et la livraison reposent sur des plateformes gerees plutot que sur une exploitation interne des serveurs.',
        ],
      },
      matrix: {
        title: 'Matrice de controles',
        subtitle: 'Chaque affirmation de controle est rattachee a un mecanisme d implementation.',
      },
      controls: [
        { control: 'Isolation entre organisations', support: 'Politiques PostgreSQL RLS scopees par org_id sur les tables operationnelles.' },
        { control: 'Controle d acces', support: 'Appartenance a l organisation et chemins d ecriture limites par role pour les operations critiques.' },
        { control: 'Tracabilite des changements', support: 'Identifiants transactionnels, horodatages et enregistrements de confirmation de depot.' },
        { control: 'Execution cote serveur', support: 'Actions comptables et fiscales critiques executees via des controles SQL/Edge.' },
      ],
      sections: [
        {
          title: 'Controle d acces et authentification',
          items: [
            'Le controle d acces par role est applique via l appartenance a l organisation, les permissions par module et les chemins d ecriture limites par role.',
            'MFA est disponible via des facteurs TOTP d application d authentification.',
            'Les zones sensibles de l ERP peuvent exiger une authentification de step-up en AAL2 avant l acces.',
          ],
        },
        {
          title: 'Isolation des donnees',
          items: [
            'L isolation entre organisations est scopee par identifiants d organisation et politiques de securite base de donnees.',
            'Les lectures et ecritures operationnelles sont liees au contexte de l organisation active.',
            'La separation des donnees est logique dans l environnement applicatif partage et non basee sur des piles applicatives par organisation.',
          ],
        },
        {
          title: 'Hebergement et infrastructure',
          items: [
            'Les services backend sont geres via Supabase.',
            'Le frontend public est diffuse via Vercel.',
            'Le chiffrement en transit utilise HTTPS/TLS.',
            'L infrastructure cloud sous-jacente est geree par les fournisseurs et non exploitee directement par ZANVROX.',
          ],
        },
        {
          title: 'Securite operationnelle',
          items: [
            'Les gates de release incluent lint, tests unitaires, tests web, builds et scripts de validation avant toute decision de deploiement.',
            'La couverture Playwright E2E et les smoke checks heberges servent a valider les workflows critiques.',
            'La surveillance des dependances inclut npm audit en CI pour l examen des packages de severite elevee.',
            'Les logs applicatifs sont assainis pour reduire l exposition accidentelle des emails, tokens et autres champs sensibles.',
          ],
        },
      ],
      subprocessors: {
        title: 'Sous-traitants',
        subtitle: 'Resume public actuel des prestataires tiers utilises pour exploiter le service.',
        items: [
          {
            name: 'Supabase',
            support: 'Plateforme backend geree pour la base de donnees, l authentification, le stockage et les workflows cote serveur.',
          },
          {
            name: 'Vercel',
            support: 'Hebergement et diffusion frontend geres pour l experience web publique.',
          },
          {
            name: 'Resend',
            support: 'Envoi transactionnel d emails pour une communication limitee et le routage des leads du site.',
          },
        ],
        note: 'Ces prestataires sont utilises uniquement lorsque c est necessaire pour l exploitation du service, sa diffusion ou la communication transactionnelle.',
      },
      disclosures: {
        title: 'Transparence et limites actuelles',
        subtitle: 'Des declarations conservatrices qui refletent les controles actuellement disponibles.',
        items: [
          'Aucune promesse d auto-filing : uniquement un support de workflow portal-ready.',
          'Aucun feature flag cache pour des capacites publiques.',
          'Le comportement de production est soutenu par des logs auditables et des snapshots.',
          'MFA repose actuellement sur un TOTP d application d authentification et n est pas resistant au phishing.',
          'L authentification de step-up est imposee sur les routes sensibles plutot que comme exigence globale de chaque session.',
          'WebAuthn et l authentification par passkeys ne sont pas encore disponibles.',
        ],
      },
      cta: {
        title: 'Contact securite',
        subtitle: 'Utilisez le parcours de contact existant pour les demandes d apercu securite ou les suivis securite/compliance.',
        primary: { label: 'Demander un apercu securite', path: '/contact' },
        secondary: { label: 'Contacter pour des demandes securite/compliance', path: '/contact' },
      },
    },
    about: {
      heroKicker: 'A propos de ZANVROX',
      heroTitle: 'Un ERP pratique positionne pour un deploiement credible, pas pour le theatre d entreprise.',
      heroSubtitle:
        'ZANVROX est presente comme un ERP moderne pour les PME canadiennes qui veulent un controle operationnel plus ferme, moins de systemes deconnectes et un parcours de support plus clair.',
      heroPrimaryCta: { label: 'Explorer le produit', path: '/product' },
      heroSecondaryCta: { label: 'Contacter l equipe', path: '/contact' },
      heroPreview: {
        title: 'Synthese de positionnement',
        type: 'reports',
        caption: 'Controle operationnel face a la proliferation logicielle',
        callouts: [
          { status: 'ready', text: 'Posture de support claire' },
          { status: 'ready', text: 'Parcours d evaluation axe produit' },
        ],
      },
      principles: {
        title: 'Trois principes derriere le site',
        subtitle: 'Le positionnement public est optimise pour une realite operationnelle dirigee par les fondateurs sans abaisser le niveau du produit.',
        items: [
          { title: 'Clarite', body: 'Dire ce que fait le produit, ce qu il supporte et ou une revue reste necessaire.' },
          { title: 'Controle', body: 'Mettre en avant l auditabilite, la gouvernance et la visibilite operationnelle plutot qu un discours SaaS gonfle.' },
          { title: 'Deploiement pratique', body: 'Rendre la configuration autonome viable tout en gardant une aide experte en option lorsque la complexite augmente.' },
        ],
      },
      operatingModel: [
        {
          title: 'Concu pour les PME canadiennes',
          subtitle: 'Le site public vise les entreprises qui ont besoin d un controle ERP credible sans surcharge de conseil de niveau entreprise des le premier jour.',
          items: [
            'Meilleur fit autour de 10-50 employes',
            'Valeur forte lorsque la finance et les operations sont eparpillees entre trop d outils',
            'Parcours clair du noyau finance vers les operations et l add-on paie',
          ],
        },
        {
          title: 'Discipline commerciale',
          subtitle: 'Le site est concu pour reduire les reunions de faible qualite et rendre les attentes explicites avant la premiere conversation.',
          items: [
            'Demo optionnelle au lieu d un tunnel demo-first',
            'Tarification publique avec niveaux de support et attentes d onboarding',
            'Promesses de securite et de gouvernance alignees sur la posture reelle du produit',
          ],
        },
      ],
      cta: {
        title: 'Verifiez si le modele operationnel convient a votre equipe',
        subtitle: 'Utilisez Produit, Tarifs et Ressources pour qualifier l adequation avant de nous contacter.',
        primary: { label: 'Voir les tarifs', path: '/pricing' },
        secondary: { label: 'Aller au contact', path: '/contact' },
      },
    },
    contact: {
      heroTitle: 'Contactez l equipe seulement lorsque vous avez besoin d aide pour une vraie question d evaluation.',
      heroSubtitle:
        'Le parcours prevu est apercu produit, exploration du produit, revue des tarifs, evaluation dans le navigateur, puis contact optionnel ou demande de presentation guidee.',
      conversion: {
        title: 'Parcours d evaluation recommande',
        subtitle: 'Cela reduit les reunions inutiles et fournit un meilleur contexte lorsqu une personne prend finalement contact.',
        cards: [
          { title: 'Voir l apercu produit', body: 'Commencez par la video pour comprendre le modele operationnel et la posture du produit.' },
          { title: 'Explorer les fonctionnalites', body: 'Utilisez les pages Produit, Tarifs et Securite pour evaluer la pile sans appel.' },
          { title: 'Ouvrir l espace d evaluation', body: 'Validez l interface avec des donnees fictives avant de demander une session guidee.' },
          { title: 'Demander de l aide si necessaire', body: 'Utilisez les formulaires ci-dessous pour une demo optionnelle ou une question produit ciblee.' },
        ],
      },
      supportBlock: {
        title: 'Attentes de support',
        subtitle: 'Tous les flux de contact du site arrivent sur support@zanvrox.com.',
        items: [
          'Finance Core : support email avec reponse sous 48 h',
          'Operations : support email prioritaire avec reponse sous 24 h',
          'Enterprise : canal de support direct plus assistance d onboarding',
        ],
      },
      pricingContext: {
        title: 'Contexte tarifaire selectionne',
        subtitle: 'Le contexte tarifaire reste rattache a votre demande afin que le suivi demeure ancre dans la configuration choisie.',
        labels: {
          plan: 'Plan',
          billing: 'Facturation',
          payroll: 'Paie',
          offer: 'Offre',
          notSelected: 'Non selectionne',
          payrollInterested: 'Add-on paie selectionne',
          payrollNotSelected: 'Aucun add-on paie selectionne',
        },
      },
      demoForm: {
        title: 'Demander une presentation guidee',
        helper: 'Utilisez ce formulaire apres que votre equipe a consulte le produit et souhaite une presentation guidee.',
        confirmation: 'Votre demande de presentation guidee a ete envoyee avec succes. Nous assurerons le suivi par email.',
        submittingCta: 'Envoi...',
        submitError: 'Nous n avons pas pu envoyer votre demande. Veuillez reessayer.',
        messageHint: 'Optionnel. Utilisez ce champ pour decrire votre pile actuelle, votre calendrier de deploiement ou une question de paie.',
        fields: {
          name: 'Nom*',
          company: 'Entreprise*',
          email: 'Email professionnel*',
          companySize: 'Taille de l entreprise*',
          interestArea: 'Domaine d interet*',
          message: 'Message optionnel',
          consent:
            'J accepte d etre contacte par ZANVROX au sujet de cette demande commerciale. Nous utilisons ces donnees uniquement pour repondre a la demande.',
        },
        placeholders: {
          email: 'nom@entreprise.com',
          companySize: 'Selectionnez la taille de l entreprise',
          interestArea: 'Selectionnez le domaine d interet',
          message: 'Que souhaitez-vous valider lors d une presentation guidee ?',
        },
        options: {
          companySizes: ['1-10 employes', '10-50 employes', '50-100 employes', '100+ employes'],
          interestAreas: [
            'Finance Core',
            'Operations',
            'Add-on paie',
            'Guided Implementation',
            'Deploiement enterprise',
            'Integrations / API',
          ],
        },
        errors: {
          name: 'Saisissez votre nom.',
          company: 'Saisissez le nom de votre entreprise.',
          email: 'Saisissez un email professionnel valide.',
          companySize: 'Selectionnez la taille de l entreprise.',
          interestArea: 'Selectionnez un domaine d interet.',
          message: 'Gardez le message sous 2000 caracteres.',
          consent: 'Le consentement est requis pour envoyer ce formulaire.',
          startedAt: 'Veuillez patienter un instant avant d envoyer.',
          website: 'La protection anti-spam a ete declenchee.',
        },
        cta: 'Demander une presentation guidee',
      },
      briefForm: {
        title: 'Poser une question produit',
        helper: 'Utilisez ce formulaire pour des questions sur l adequation produit, le support, l onboarding, l implementation ou le perimetre paie.',
        confirmation: 'Votre message a ete envoye avec succes. Nous repondrons par email.',
        submittingCta: 'Envoi...',
        submitError: 'Nous n avons pas pu envoyer votre demande. Veuillez reessayer.',
        messageHint: 'Optionnel. Utilisez ce champ si vous souhaitez decrire votre workflow, votre besoin de support ou votre question d implementation.',
        fields: {
          name: 'Nom*',
          company: 'Entreprise*',
          email: 'Email professionnel*',
          companySize: 'Taille de l entreprise*',
          interestArea: 'Domaine d interet*',
          message: 'Message optionnel',
          consent: 'J accepte de recevoir le suivi demande de la part de ZANVROX.',
        },
        placeholders: {
          email: 'nom@entreprise.com',
          companySize: 'Selectionnez la taille de l entreprise',
          interestArea: 'Selectionnez le domaine d interet',
          message: 'Que souhaitez-vous clarifier avant que votre equipe investisse plus de temps dans l evaluation ?',
        },
        options: {
          companySizes: ['1-10 employes', '10-50 employes', '50-100 employes', '100+ employes'],
          interestAreas: [
            'Adequation produit',
            'Tarifs et support',
            'Acces sandbox',
            'Import des donnees',
            'Add-on paie',
            'Guided Implementation',
          ],
        },
        errors: {
          name: 'Saisissez votre nom.',
          company: 'Saisissez le nom de votre entreprise.',
          email: 'Saisissez un email professionnel valide.',
          companySize: 'Selectionnez la taille de l entreprise.',
          interestArea: 'Selectionnez un domaine d interet.',
          message: 'Gardez le message sous 2000 caracteres.',
          consent: 'Le consentement est requis pour envoyer ce formulaire.',
          startedAt: 'Veuillez patienter un instant avant d envoyer.',
          website: 'La protection anti-spam a ete declenchee.',
        },
        cta: 'Envoyer la question',
      },
    },
    legal: {
      privacy: {
        title: 'Politique de confidentialite',
        updated: '5 mars 2026',
        updatedLabel: 'Derniere mise a jour',
        paragraphs: [
          'ZANVROX collecte les informations de contact professionnelles soumises via ce site pour l evaluation produit, la planification de demos et les demandes de documentation.',
          'Nous traitons les donnees soumises uniquement a des fins de qualification commerciale et produit.',
          'Vous pouvez demander l acces, la correction ou la suppression des donnees soumises en contactant support@zanvrox.com.',
        ],
      },
      terms: {
        title: 'Conditions d utilisation',
        updated: '5 mars 2026',
        updatedLabel: 'Derniere mise a jour',
        paragraphs: [
          'Ce site fournit des informations produit et des formulaires de prise de contact pour l evaluation commerciale de ZANVROX ERP.',
          'Le contenu du site est informatif et ne constitue pas un engagement produit contraignant.',
          'Le perimetre produit et les conditions commerciales sont finalises dans des accords signes.',
        ],
      },
    },
    notFound: {
      title: 'Page introuvable',
      subtitle: 'L URL ne correspond pas a la structure publiee du site ZANVROX.',
      cta: 'Retour a l accueil',
    },
  },
  footer: {
    companyDescription: 'ERP integre pour les PME canadiennes qui ont besoin de finance, d operations, de conformite et de paie dans une seule pile controlee.',
    headquarters: 'Toronto, Ontario, Canada',
    email: 'support@zanvrox.com',
    sections: [
      {
        title: 'Produit',
        links: [
          { label: 'Apercu produit', path: '/product' },
          { label: 'Tarifs', path: '/pricing' },
          { label: 'Ressources', path: '/resources' },
          { label: 'Contact', path: '/contact' },
        ],
      },
      {
        title: 'Confiance et juridique',
        links: [
          { label: 'Securite', path: '/security' },
          { label: 'Securite / Compliance', path: '/security' },
          { label: 'Demander des informations de securite', path: '/contact' },
          { label: 'Confidentialite', path: '/legal/privacy' },
          { label: 'Conditions', path: '/legal/terms' },
        ],
      },
    ],
    links: [
      { label: 'Produit', path: '/product' },
      { label: 'Tarifs', path: '/pricing' },
      { label: 'Ressources', path: '/resources' },
      { label: 'Securite', path: '/security' },
      { label: 'A propos', path: '/about' },
      { label: 'Contact', path: '/contact' },
      { label: 'Confidentialite', path: '/legal/privacy' },
      { label: 'Conditions', path: '/legal/terms' },
    ],
  },
  seo: {
    home: {
      title: 'ZANVROX | ERP canadien pour la finance, les operations et le controle',
      description:
        'ERP integre pour les PME canadiennes avec comptabilite, facturation, inventaire, entrepot, production, gouvernance, workflows fiscaux et support de l add-on paie.',
      path: '/',
    },
    product: {
      title: 'Produit | ZANVROX',
      description:
        'Explorez la couverture finance, operations, conformite canadienne, gouvernance et add-on paie dans la pile ERP ZANVROX.',
      path: '/product',
    },
    security: {
      title: 'Securite | ZANVROX',
      description: 'Consultez l isolation entre organisations, les controles par role, les approbations, la gouvernance et les protections d architecture derriere ZANVROX.',
      path: '/security',
    },
    pricing: {
      title: 'Tarifs | ZANVROX',
      description:
        'Consultez les tarifs publics en CAD pour Finance Core, Operations, le deploiement personnalise, l add-on paie et Guided Implementation en option.',
      path: '/pricing',
    },
    resources: {
      title: 'Ressources | ZANVROX',
      description: 'Utilisez les ressources produit, le guide de l espace d evaluation et l apercu securite pour autoevaluer ZANVROX.',
      path: '/resources',
    },
    about: {
      title: 'A propos | ZANVROX',
      description: 'Decouvrez comment ZANVROX positionne la finance, les operations, la gouvernance et la discipline de deploiement pour les PME canadiennes.',
      path: '/about',
    },
    contact: {
      title: 'Contact | ZANVROX',
      description: 'Demandez une demo optionnelle ou posez une question ciblee sur le produit, la paie, l onboarding ou l implementation.',
      path: '/contact',
    },
    privacy: {
      title: 'Politique de confidentialite | ZANVROX',
      description: 'Politique de confidentialite du site ZANVROX et du traitement associe des leads.',
      path: '/legal/privacy',
    },
    terms: {
      title: 'Conditions d utilisation | ZANVROX',
      description: 'Conditions d utilisation regissant le site ZANVROX et ses contenus.',
      path: '/legal/terms',
    },
  },
}

export default siteContentFr
