import siteContentEn from './siteContent.en'

const base = siteContentEn

const siteContentTl = {
  ...base,
  locale: 'tl',
  localeLabel: 'Filipino',
  labels: {
    ...base.labels,
    menu: 'Talaan',
    bookDemo: 'May gabay na pagpapakita',
    tryDemo: 'Buksan ang kapaligiran',
    getTechnicalBrief: 'Makipag-ugnayan sa pangkat',
    reviewResources: 'Tingnan ang mga sanggunian',
    language: 'Wika',
    requestQuote: 'Makipag-usap sa benta',
  },
  navItems: [
    { label: 'Simula', path: '/' },
    { label: 'Produkto', path: '/product' },
    { label: 'Presyo', path: '/pricing' },
    { label: 'Sanggunian', path: '/resources' },
    { label: 'Seguridad', path: '/security' },
    { label: 'Tungkol', path: '/about' },
    { label: 'Ugnayan', path: '/contact' },
  ],
  brand: {
    ...base.brand,
    tagline: 'Pinagsamang kontrol sa ERP para sa maliliit at katamtamang negosyo sa Canada',
    oneLiner: 'Pananalapi, operasyon, pagsunod sa mga patakaran sa Canada, at pasahod sa iisang kontroladong ERP.',
  },
  pages: {
    home: {
      ...base.pages.home,
      heroKicker: 'ERP sa Canada para sa pananalapi, operasyon, at kakayahang masuri',
      heroTitle: 'Patakbuhin ang pananalapi at operasyon sa iisang kontroladong ERP sa halip na limang magkakahiwalay na kasangkapan.',
      heroSubtitle: 'Tinutulungan ng ZANVROX ang maliliit at katamtamang negosyo sa Canada na pagsamahin ang pagkuwenta, pagsingil, pagbili, imbentaryo, produksyon, pag-apruba, at pagsunod sa patakaran nang walang mabigat na proyekto sa pagpapatupad.',
      heroPrimaryCta: { label: 'Tingnan ang buod ng produkto', path: '/#product-overview' },
      heroSecondaryCta: { label: 'Buksan ang kapaligiran ng pagsusuri', path: '/resources#demo-environment' },
      heroPreview: {
        ...base.pages.home.heroPreview,
        title: 'Paunang tanaw sa buwis at kontrol',
        caption: 'Aktibo sa loob ng ERP',
        callouts: [
          { status: 'ready', text: 'Ulat para sa GST/HST + PST/QST' },
          { status: 'ready', text: 'Bakas ng pagsusuri at pag-apruba' },
        ],
      },
      video: {
        ...base.pages.home.video,
        title: 'Gabay na pagpapakita ng produkto sa totoong daloy ng trabaho',
        subtitle: 'Maikling pagpapakita ng pananalapi, operasyon, daloy ng buwis sa Canada, at kahandaan sa pasahod.',
        windowLabel: 'Video ng produkto',
        duration: '90 sec',
        overlayLabel: 'Tingnan ang gabay na pagpapakita',
        fallbackLabel: 'May paunang tanaw na larawan',
        chapters: ['Pagkuwenta at pagsingil', 'Imbentaryo at bodega', 'Pagpaplano ng produksyon', 'Tanawan ng buwis', 'Lugar-gawaan ng pasahod', 'Mga ulat at pag-apruba'],
        primaryCta: { label: 'Suriin ang produkto', path: '/product' },
        secondaryCta: { label: 'Buksan ang kapaligiran ng pagsusuri', path: '/resources#demo-environment' },
      },
      trustSignals: [
        'Nananatili ang opisyal na daloy mula sa tagapagbigay kung saan kailangan.',
        'May pinamamahalaang pagbabago, pag-apruba, at bakas ng pagsusuri.',
        'May sariling landas ng pagsasaayos para sa mas maliliit na pangkat, na may opsyonal na gabay sa pagpapatupad.',
        'May malinaw na paninindigan sa pagsunod sa Canada nang walang sobra-sobrang pangako sa benta.',
      ],
      statusBadges: [
        { status: 'ready', text: 'Pagkuwenta, pagsingil, gastos, at ulat' },
        { status: 'ready', text: 'Imbentaryo, bodega, at daloy ng BOM' },
        { status: 'ready', text: 'Suporta sa daloy ng buwis sa Canada' },
        { status: 'ready', text: 'Dagdag na pasahod na may lugar-gawaan para sa pagtatapos ng taon' },
        { status: 'locked', text: 'Pamamahala at kontrol na nasusuri' },
        { status: 'ready', text: 'Landas ng sariling paunang pagsasaayos' },
      ],
      evaluationPath: {
        eyebrow: 'Pagsusuring pinangungunahan ng produkto',
        title: 'Magsuri nang hindi muna nagtatakda ng pulong',
        subtitle: 'Ginawa ang pook na ito para bawasan ang hindi kailangang tawag at hayaan ang mga pangkat na suriin muna ang sarili nilang tugma.',
        cards: [
          { title: '1. Panoorin ang buod', body: 'Magsimula sa video ng produkto para maunawaan kung paano nagsasama ang pananalapi, operasyon, buwis, at pasahod.' },
          { title: '2. Suriin ang produkto', body: 'Suriin ang mga pangkat ng kakayahan, larawan ng mga screen, at kontrol sa pamamahala ayon sa bahagi at proseso ng negosyo.' },
          { title: '3. Buksan ang kapaligiran ng pagsusuri', body: 'Gamitin ang kapaligirang gumagana sa browser na may kathang-isip na datos para patunayan ang pag-navigate, tugma ng tungkulin, at saklaw ng daloy ng trabaho.' },
          { title: '4. Humingi lang ng tulong kung kailangan', body: 'Gamitin ang opsyonal na form sa ugnayan o pagpapakita kapag may malinaw nang tanong sa pagsusuri ang iyong pangkat.' },
        ],
      },
      screenshots: {
        ...base.pages.home.screenshots,
        eyebrow: 'Mga screen at daloy ng trabaho',
        title: 'Mga screen na ginawa para ipakita ang tunay na saklaw ng operasyon',
        subtitle: 'Handa ang bawat seksyon sa ibaba para sa totoong larawan ng screen at gumagamit ng paunang tanaw ng produkto kapag wala pang huling larawan.',
        items: [
          { title: 'Tanawan ng buwis sa Canada', body: 'Subaybayan ang kahandaan sa paghahain, mga uri ng buwis, at kontrol sa pagsasara mula sa iisang tanaw ng pananalapi.', previewType: 'reports', imageKey: 'taxDashboard', imageAlt: 'Tanawan ng buwis sa Canada sa loob ng ZANVROX ERP' },
          { title: 'Pamamahala ng imbentaryo', body: 'Tingnan ang posisyon ng paninda, paggalaw sa bodega, at nakikitang datos ayon sa pangkat ng paninda nang hindi umaalis sa ERP.', previewType: 'inventory' },
          { title: 'Pagpaplano ng produksyon', body: 'Suriin ang mga kautusan sa produksyon na nakaugnay sa BOM, paggamit ng materyales, at progreso ng pagpapatupad sa iisang tanaw.', previewType: 'production' },
          { title: 'Mga ulat sa pananalapi', body: 'Lumipat mula sa gawaing pang-operasyon patungo sa ulat para sa pamamahala nang hindi pinagtatagni ang maraming kasangkapan.', previewType: 'accounting' },
        ],
      },
      howItWorks: {
        ...base.pages.home.howItWorks,
        eyebrow: 'Sariling paunang pagsasaayos',
        title: 'Magsimula sa anim na may-gabay na hakbang',
        subtitle: 'Dinisenyo ang produkto para makapagsimula ang pangkat na pinamumunuan ng tagapagtatag nang hindi kailangan ng mabigat na proyekto sa paunang pagsasaayos.',
        steps: [
          { icon: '1', title: 'Gumawa ng samahan', bullets: ['Simulan ang iyong kapaligiran', 'Itakda ang pangunahing detalye ng legal na entidad'] },
          { icon: '2', title: 'Piliin ang bansa', bullets: ['Piliin ang Canada', 'Ipasok ang mga paunang halaga ayon sa bansa'] },
          { icon: '3', title: 'Pumili ng hulma para sa industriya', bullets: ['Magsimula sa praktikal na modelo', 'Bawasan ang hadlang sa pagsasaayos'] },
          { icon: '4', title: 'Isaayos ang mga buwis', bullets: ['Itakda ang mga uri ng buwis', 'Kumpirmahin ang lohika at paunang halaga ng lalawigan'] },
          { icon: '5', title: 'Ipasok ang mga kliyente at tagapagtustos', bullets: ['Dalhin ang pangunahing datos', 'Gumamit ng mga hulma at pagsusuri'] },
          { icon: '6', title: 'Gawin ang unang singil', bullets: ['Patunayan ang daloy ng operasyon', 'Lumipat sa pang-araw-araw na paggamit'] },
        ],
      },
      compliance: {
        ...base.pages.home.compliance,
        eyebrow: 'Paninindigan sa Canada',
        title: 'Binuo para sa kredibilidad, hindi sa ingay',
        subtitle: 'Ipinaliliwanag ng pook-sapot kung ano ang kontrolado, ano ang awtomatiko, at ano pa ang nangangailangan ng pagsusuri.',
        bullets: [
          'Ang mga daloy ng buwis sa Canada ay inilalarawan gamit ang malinaw na paninindigan sa paghahain at kakayahang masuri.',
          'Ang pasahod ay inilalagay bilang hiwalay na dagdag na may malinaw na saklaw at kahandaan ayon sa nasasakupan.',
          'Direktang sinasabi ang mga pag-apruba, pamamahala, at inaasahang tulong sa halip na itago sa tawag sa benta.',
        ],
        coverageLabel: 'Kasalukuyang paninindigang pangkomersyo',
        coverage: 'Pinakamainam para sa maliliit at katamtamang negosyo sa Canada na may 10-50 empleyado',
        note: 'Nananatiling magagamit ang opisyal na daloy mula sa tagapagbigay kung saan hindi angkop ang opisyal na pahayag para sa malalaking organisasyon.',
      },
      included: {
        ...base.pages.home.included,
        eyebrow: 'Ano ang pinagsama',
        title: 'Iisang salansan para sa pananalapi at operasyon',
        subtitle: 'Hindi ang punto ay mas maraming kakayahan sa papel. Ang punto ay mas kaunting pira-pirasong daloy ng trabaho sa aktuwal na paggamit.',
        items: [
          'Pagkuwenta, pagsingil, gastos, at ulat sa pananalapi',
          'Pagbili, imbentaryo, bodega, at pangunahing produksyon',
          'Pag-apruba, pamamahala, at bakas ng pagsusuring pang-operasyon',
          'Mga daloy para sa pagsunod sa buwis sa Canada at dagdag na tulong sa pasahod',
          'Maramihang kumpanya at mas mataas na pamamahala para sa saklaw ng malalaking organisasyon',
          'Katalinuhan sa ERP at tulong ng AI na may kontroladong paninindigan',
        ],
      },
      executiveSnapshot: {
        ...base.pages.home.executiveSnapshot,
        badge: 'Paraan ng pagpapatakbo',
        title: 'Dinisenyo para sa sariling pagsusuri muna, tulong ng tao pagkatapos',
        subtitle: 'Ito ay pook na pinangungunahan ng produkto para sa seryosong ERP, hindi polyeto na nagtutulak sa bawat potensyal na kliyente sa tawag.',
        metrics: [
          { label: 'Pangunahing kliyente', value: '10-50', note: 'empleyado sa maliit at katamtamang negosyo sa Canada' },
          { label: 'Paninindigan sa tulong', value: 'Una ang elektronikong liham', note: 'Malinaw na oras ng tugon ayon sa plano' },
          { label: 'Paninindigan sa paunang pagsasaayos', value: 'Sariling pagsasaayos', note: 'May opsyonal na gabay sa pagpapatupad' },
        ],
      },
      positioning: {
        ...base.pages.home.positioning,
        eyebrow: 'Bakit lumilipat ang mga pangkat',
        title: 'Bawasan ang pagkakapira-piraso sa pananalapi, operasyon, at pagsunod',
        subtitle: 'Ang halaga nito ay kontrol, linaw ng tanaw, at mas kaunting lipat-lipat sa mga sistema.',
        cards: [
          { role: 'Pananalapi', headline: 'Magsara ng panahon gamit ang mas kaunting magkakahiwalay na sistema.', points: ['Pagkuwenta, pagsingil, gastos, at ulat sa iisang sistema.', 'Malinaw na hangganan ng tulong at kontrol na nakabatay sa panahon.', 'Paninindigan sa pagsunod sa Canada nang hindi sobra ang pangako sa awtomasyon.'] },
          { role: 'Operasyon', headline: 'Panatilihing magkakasabay ang paninda, pagbili, at produksyon.', points: ['Mga daloy ng imbentaryo at bodega na konektado sa pananalapi.', 'Pangunahing BOM at produksyon nang walang dagdag na tagapamagitan.', 'Mga hudyat sa pagsusuri ng operasyon at pamamahala kung saan kailangan.'] },
          { role: 'Pamunuan', headline: 'Makakuha ng mas malinaw na tulong sa pagpapasya.', points: ['Mas kaunting manwal na pagtutugma sa pagitan ng mga kasangkapan.', 'Malinaw na inaasahang tulong at saklaw ng paunang pagsasaayos.', 'Mas maayos na paunang pagsusuri bago gumastos ng panloob na oras.'] },
          { role: 'Teknolohiya / Operasyon', headline: 'Magpatibay nang may disiplinadong saklaw.', points: ['Malinaw na pagkakasunod-sunod ng pagpapatupad para sa maliliit na pangkat.', 'Pinamamahalaang pagbabago at mga daloy na nasusuri.', 'Patong ng pagpapakilala sa pook-sapot na may nakabalangkas na datos.'] },
        ],
      },
      technical: {
        ...base.pages.home.technical,
        eyebrow: 'Paraan ng tulong at paunang pagsasaayos',
        title: 'Sariling serbisyo bilang karaniwan, may gabay kapag mahalaga',
        subtitle: 'Nagtatakda ang pook ng inaasahan nang maaga para alam ng maliliit na pangkat ang mangyayari pagkatapos magpatala.',
        items: [
          'Kasama sa Pundasyong Pinansyal ang sariling paunang pagsasaayos at tulong sa elektronikong liham na may tugon sa loob ng 48h.',
          'Nagdadagdag ang Operasyon ng pangunahing tulong sa elektronikong liham na may tugon sa loob ng 24h.',
          'Kasama sa Malaking Organisasyon ang tulong sa paunang pagsasaayos at tuwirang daan ng suporta.',
        ],
      },
      supportModel: {
        ...base.pages.home.supportModel,
        title: 'Inaasahang tulong ayon sa plano',
        subtitle: 'Direktang ipinapakita ang tulong para manatiling makatotohanan ang pagsusuri.',
        tiers: [
          { name: 'Pundasyong Pinansyal', body: 'Tulong sa elektronikong liham, tugon sa 48h, at gabay sa sariling paunang pagsasaayos.' },
          { name: 'Operasyon', body: 'Pangunahing tulong sa elektronikong liham, tugon sa 24h, at mas malakas na gabay sa operasyon.' },
          { name: 'Malaking Organisasyon', body: 'Nakalaang paunang pagsasaayos, tuwirang daan ng suporta, at tulong sa nakatakdang paglulunsad.' },
        ],
      },
      demoEnvironment: {
        ...base.pages.home.demoEnvironment,
        title: 'Buksan ang kapaligiran ng pagsusuri ng ZANVROX',
        subtitle: 'Gamitin ang kapaligirang gumagana sa browser na may kathang-isip na datos bago humiling ng may-gabay na pagpapakita.',
        emailLabel: 'Gumagamit sa pagpapakita',
        passwordLabel: 'Salitang-pasok',
        note: 'Para lamang sa pagsusuri sa browser. Hiwalay ang kapaligirang ito sa pagpaplano ng pagpapatupad at inaasahang paggamit sa produksyon.',
        cta: { label: 'Buksan ang kapaligiran ng pagsusuri', path: '/resources#demo-environment' },
      },
      faq: {
        ...base.pages.home.faq,
        eyebrow: 'FAQ',
        title: 'Mga tanong bago maglaan ng oras ang mga pangkat',
        items: [
          { question: 'Maaari ba naming suriin ang ZANVROX nang hindi muna nagtatakda ng pagpapakita?', answer: 'Oo. Ang nilalayong landas ay panoorin ang buod, suriin ang produkto, buksan ang kapaligiran ng pagsusuri, at humingi lang ng tulong kung kailangan ng iyong pangkat.' },
          { question: 'Kasama ba ang pasahod sa mga batayang plano?', answer: 'Hindi. Ang pasahod ay hiwalay na dagdag na may sariling presyo para hindi ito awtomatikong bayaran ng mga pangkat na pananalapi lamang ang kailangan.' },
          { question: 'Kailangan ba namin ng bayad na proyekto sa paunang pagsasaayos?', answer: 'Hindi. Sariling pagsasaayos ang karaniwang landas. Magagamit ang May-gabay na Pagpapatupad bilang opsyonal na bayad na pakete kapag gusto ng iyong pangkat ng tulong sa pagsasaayos at pagpasok ng datos.' },
          { question: 'Anong tulong ang dapat naming asahan?', answer: 'Kasama sa Pundasyong Pinansyal ang tulong sa elektronikong liham sa loob ng 48h, sa Operasyon ang pangunahing tulong sa elektronikong liham sa loob ng 24h, at sa Malaking Organisasyon ang tulong sa paunang pagsasaayos kasama ang tuwirang daan ng suporta.' },
        ],
      },
      cta: {
        ...base.pages.home.cta,
        title: 'Magsimula sa produkto, hindi sa tawag sa benta',
        subtitle: 'Suriin muna ang produkto at presyo. Makipag-ugnayan lang sa pangkat kapag may malinaw kang tanong sa paglulunsad, pasahod, o pagsasama.',
        primary: { label: 'Suriin ang produkto', path: '/product' },
        secondary: { label: 'Tingnan ang presyo', path: '/pricing' },
      },
    },
    product: {
      ...base.pages.product,
      heroKicker: 'Pinagsamang saklaw ng produkto',
      heroTitle: 'Saklaw ng produkto para sa pananalapi, operasyon, pagsunod, at pasahod.',
      heroSubtitle: 'Inilalagay ang ZANVROX bilang kontroladong ERP para sa maliliit at katamtamang negosyo sa Canada na nangangailangan ng tanaw sa operasyon nang walang palabas para sa malalaking organisasyon.',
      heroPrimaryCta: { label: 'Tingnan ang presyo', path: '/pricing' },
      heroSecondaryCta: { label: 'Buksan ang kapaligiran ng pagsusuri', path: '/resources#demo-environment' },
      heroPreview: {
        ...base.pages.product.heroPreview,
        title: 'Paunang tanaw sa operasyon',
        caption: 'Iisang patong ng datos sa operasyon',
        callouts: [
          { status: 'ready', text: 'Imbentaryo, bodega, BOM, at produksyon' },
          { status: 'ready', text: 'Pamamahala at pag-apruba' },
        ],
      },
      pillars: {
        title: 'Apat na haligi ng produkto',
        subtitle: 'Ipinaliliwanag ng pook-sapot ang produkto sa paligid ng daloy ng trabaho, hindi sa magkakahiwalay na tala ng kakayahan.',
        items: [
          { title: 'Pundasyong pinansyal', body: 'Pagkuwenta, pagsingil, gastos, tanaw sa bangko, at ulat.' },
          { title: 'Operasyon', body: 'Imbentaryo, bodega, BOM, pangunahing produksyon, at pag-apruba.' },
          { title: 'Pagsunod sa Canada', body: 'Mga daloy ng buwis, dagdag na pasahod, tulong sa pagpapadala ng bayad, at paninindigan sa pagtatapos ng taon.' },
          { title: 'Pamamahala', body: 'Kakayahang masuri, pag-apruba, hangganan ng kontrol, at landas ng pagpapalawak sa maraming kumpanya.' },
        ],
      },
      showcase: {
        title: 'Mga bahagi ng produkto na mahalagang makita',
        subtitle: 'Ito ang mga screen na karaniwang gustong suriin ng mga pangkat bago maglaan ng mas malalim na oras sa usapang benta.',
        items: [
          { title: 'Tanawan ng buwis', body: 'Ipinapakita ang paninindigan sa paghahain, progreso sa pagsunod, at tanaw sa sumusuportang daloy ng trabaho.', previewType: 'reports', imageKey: 'taxDashboard', imageAlt: 'Tanawan ng buwis sa ZANVROX ERP' },
          { title: 'Kontrol sa imbentaryo', body: 'Ipinapakita ang tanaw sa paninda, ruta sa bodega, at mga hudyat ng kahandaan sa operasyon.', previewType: 'inventory' },
          { title: 'Pagpaplano ng produksyon', body: 'Ipinapakita ang pagpaplano ng operasyon na nakaugnay sa BOM at progreso ng pagpapatupad.', previewType: 'production' },
          { title: 'Ulat sa pananalapi', body: 'Ipinapakita ang magkakaugnay na ulat mula sa gawaing pang-operasyon pabalik sa pananalapi.', previewType: 'reports' },
        ],
      },
      stacks: [
        {
          title: 'Pinagsamang pananalapi at operasyon',
          subtitle: 'Dinisenyo para bawasan ang lipat-lipat sa mga kasangkapan sa pangkat na may 10-50 empleyado.',
          items: [
            'Nasa iisang sistema ang pagkuwenta at pagsingil kasama ang pagbili at gastos.',
            'Nananatiling nakaugnay sa talaang pinansyal ang datos ng imbentaryo, bodega, at BOM.',
            'Maaaring idagdag ang pag-apruba at pamamahala nang walang hiwalay na kasangkapan sa operasyon.',
          ],
        },
        {
          title: 'Paninindigan sa kontrol sa Canada',
          subtitle: 'Dinisenyo para maging kapani-paniwala sa konteksto ng pagpapatakbo sa Canada.',
          items: [
            'Ipinapaliwanag ang tulong sa buwis sa Canada gamit ang praktikal na wika ng daloy ng trabaho.',
            'Nananatiling dagdag ang pasahod na may malinaw na saklaw ng tulong at presyo.',
            'Nakaayon ang mga pahayag sa tunay na pamamahala, kahandaan, at paninindigan sa pagsusuri.',
          ],
        },
      ],
      onboarding: {
        title: 'Paano gumagana ang sariling pagsasaayos sa praktika',
        subtitle: 'Pinapalakas ng pahina ng produkto ang ideyang ang paunang pagsasaayos ay ginagabayan sa loob ng produkto, hindi nakatago sa likod ng pagkonsulta bilang karaniwan.',
        steps: [
          { number: '1', title: 'Gumawa ng samahan', body: 'Gumawa ng kapaligiran at magsimula mula sa malinis na batayan ng pagpapatakbo.' },
          { number: '2', title: 'Piliin ang Canada', body: 'Ilapat ang mga paunang halaga ayon sa bansa at palagay sa pagsunod.' },
          { number: '3', title: 'Pumili ng hulma para sa industriya', body: 'Magsimula sa praktikal na batayan sa halip na magsaayos mula sa wala.' },
          { number: '4', title: 'Isaayos ang mga buwis', body: 'Kumpirmahin ang ruta ng buwis, mga rehistro, at kontrol sa pananalapi.' },
          { number: '5', title: 'Ipasok ang pangunahing datos', body: 'Ipasok ang mga kliyente, tagapagtustos, at mahahalagang talaang pang-operasyon.' },
          { number: '6', title: 'Patakbuhin ang unang transaksyon', body: 'Gumawa ng unang singil at patunayan ang landas ng operasyon mula simula hanggang dulo.' },
        ],
        note: 'Magagamit ang May-gabay na Pagpapatupad kapag gusto ng iyong pangkat ng tulong sa pagsasaayos, pagsusuri ng talaan ng mga account, pagpasok ng datos, at pagsasanay.',
      },
      cta: {
        title: 'Tingnan kung tumutugma ang saklaw ng produkto sa kumpanya mo ngayon',
        subtitle: 'Gamitin ang presyo at mga sanggunian para magpasya kung kailangan mo ng sariling pagsasaayos, may-gabay na pagpapatupad, o usapan para sa malaking organisasyon.',
        primary: { label: 'Tingnan ang presyo', path: '/pricing' },
        secondary: { label: 'Makipag-ugnayan sa pangkat', path: '/contact' },
      },
    },
    platform: {
      heroTitle: 'Arkitektura ng plataporma para sa kontroladong paglaki.',
      availableLabel: 'Magagamit na ngayon',
      heroSubtitle: 'Modular na pundasyon ng ERP na nagpapanatiling magkasabay ang pananalapi at operasyon.',
      heading: {
        title: 'Mga patong ng plataporma',
        subtitle: 'Dinisenyo ang bawat patong para sa kakayahang masuri, mapalawak, at magamit sa maraming kumpanya.',
      },
      sections: [
        { title: 'Modelo ng datos sa operasyon', status: 'available', statusLabel: 'Magagamit na ngayon', points: ['Pangunahing entidad para sa mga singil, item, pangkat ng paninda, pagbili, gastos, at kliyente.', 'Mga hangganan at kontrol sa pagkuwenta na nakaugnay sa talaan.', 'Daloy sa paggawa ng dokumento para sa mga output na nakikita ng kostumer.'] },
        { title: 'Arkitektura ng aplikasyon', status: 'available', statusLabel: 'Magagamit na ngayon', points: ['React + Vite na harapan para sa mabilis na pakikipag-ugnayan.', 'Supabase/PostgreSQL na likuran na may lohikang nauuna ang SQL.', 'Edge functions para sa ligtas na pagsasaayos ng mga daloy.'] },
        { title: 'Kontrol para sa malalaking organisasyon', status: 'available', statusLabel: 'Magagamit na ngayon', points: ['Mga kontrol sa pagsasara ng panahon at tala ng pagsusuri.', 'Mga snapshot ng pagbabalik ng buwis at kumpirmasyon sa paghahain.', 'Pagpasok ayon sa tungkulin na may paghihiwalay ng samahan.'] },
      ],
    },
    solutions: {
      kicker: 'Mga Solusyon',
      manufacturing: {
        title: 'Paggawa',
        subtitle: 'Mula BOM hanggang output ng produksyon na may tanaw sa bawat transaksyon.',
        scopeTitle: 'Saklaw ng paggawa',
        scopeSubtitle: 'Mga kakayahang handa sa produksyon na magagamit na ngayon.',
        included: ['BOM at pagpapatupad ng produksyon na nakaugnay sa paggalaw ng imbentaryo.', 'Pagsubaybay ayon sa pangkat ng paninda sa papasok at palabas na stock.', 'Mga pangyayari sa operasyon na nakaayon sa pagkuwenta para sa pagtutugma.'],
        cta: 'Magpatakda ng pagpapakita para sa paggawa',
        secondaryCta: { label: 'Pamamahagi ng Pagkain', path: '/solutions/food-distribution' },
      },
      foodDistribution: {
        title: 'Pamamahagi ng Pagkain',
        subtitle: 'Mga daloy ng pamamahagi ayon sa pangkat ng paninda para sa operasyong mataas ang pangangailangan sa pagsubaybay.',
        scopeTitle: 'Saklaw ng pamamahagi',
        scopeSubtitle: 'Saklaw ng operasyon na magagamit na ngayon.',
        included: ['Kontrol sa imbentaryo at pangkat ng paninda para sa operasyong mabigat sa pagsubaybay.', 'Pagbili, pag-update ng stock, at pagsingil sa iisang kadena ng operasyon.', 'Suporta sa ulat sa buwis na handa para sa portal para sa pagsunod sa Canada.'],
        cta: 'Magpatakda ng pagpapakita para sa pamamahagi',
        secondaryCta: { label: 'Paggawa', path: '/solutions/manufacturing' },
      },
    },
    modules: {
      heroTitle: 'Mga bahagi na gumagana bilang iisang sistema.',
      heroSubtitle: 'Maaaring gamitin nang hiwalay ang bawat bahagi at magkakaugnay sa iisang kontroladong pundasyon ng datos.',
      activeLabel: 'Aktibo',
      includedTitle: 'Kasama',
      modules: [
        { name: 'Pananalapi', included: ['Mga kontrol sa talaan', 'Pagkuha ng gastos', 'Mga pangyayari sa pagkuwenta na nakaugnay sa singil'] },
        { name: 'Imbentaryo', included: ['Pagsubaybay ng pangkat ng paninda', 'Mga lokasyon ng stock', 'Mga pagsasaayos sa imbentaryo'] },
        { name: 'Bodega', included: ['Mga padala', 'Tulong sa pagpili ng paninda', 'Daloy ng paggalaw na handa sa paghahatid'] },
        { name: 'BOM', included: ['Pagsasaayos ng talaan ng materyales', 'Pag-uugnay ng materyales sa produksyon'] },
        { name: 'Produksyon', included: ['Mga transaksyon sa produksyon', 'Pagsubaybay sa epekto sa imbentaryo'] },
        { name: 'Pagsingil', included: ['Paggawa at pag-edit ng singil', 'Pasadyang PDF output', 'Mga paunang halaga ng pagsingil ayon sa kliyente'] },
        { name: 'Pagbili', included: ['Mga daloy ng pagbili mula sa tagapagtustos', 'Pagkuha ng gastos na nakatali sa imbentaryo'] },
        { name: 'Mga buwis', included: ['Ulat para sa GST/HST + PST/QST', 'Mga snapshot ng pagbabalik', 'Daloy ng paghahain na handa sa portal'] },
      ],
    },
    security: {
      ...base.pages.security,
      heroTitle: 'Seguridad at arkitektura mula sa disenyo.',
      heroSubtitle: 'Hangganan ng nangungupahang kapaligiran, pinakamababang pahintulot, at kilos ng transaksyon na nasusuri.',
      overview: {
        title: 'Buod ng seguridad',
        subtitle: 'Konserbatibong buod ng mga kontrol na kasalukuyang nakikita sa produkto at daloy ng paghahatid.',
        description: 'Ang ZANVROX ay binuo sa paligid ng paghihiwalay ng kapaligiran, pagpasok ayon sa tungkulin, at pagpapatupad ng server para sa sensitibong operasyon. Ang mga pampublikong pahayag sa seguridad ay limitado sa mga kontrol na ipinatutupad ngayon at umiiwas sa mga pahayag sa sertipikasyon o saklaw na wala pa.',
        bullets: ['Nakatuon ang paninindigan sa seguridad sa pinakamababang pahintulot, saklaw ayon sa samahan, at kilos ng operasyon na nasusuri.', 'Maaaring kailanganin ang mas matibay na pagpapatunay bago makapasok sa sensitibong bahagi.', 'Umaasa ang imprastraktura at paghahatid sa pinamamahalaang mga tagapagbigay ng plataporma sa halip na sariling pinatatakbong server.'],
      },
      matrix: { title: 'Talaan ng kontrol', subtitle: 'Bawat pahayag ng kontrol ay may katumbas na mekanismo ng pagpapatupad.' },
      controls: [
        { control: 'Paghihiwalay ng kapaligiran', support: 'Mga patakaran ng PostgreSQL RLS na nakasaklaw sa org_id sa mga talaang pang-operasyon.' },
        { control: 'Kontrol sa pagpasok', support: 'Kasapian sa samahan at mga landas ng pagsulat ayon sa tungkulin para sa kritikal na operasyon.' },
        { control: 'Pagsubaybay sa pagbabago', support: 'Mga ID sa antas ng transaksyon, tatak ng oras, at tala ng kumpirmasyon sa paghahain.' },
        { control: 'Pagpapatupad sa panig ng server', support: 'Kritikal na gawain sa pagkuwenta at buwis na isinasagawa sa pamamagitan ng kontrol sa SQL/Edge.' },
      ],
      sections: [
        { title: 'Kontrol sa Pagpasok at Pagpapatunay', items: ['Ipinapatupad ang kontrol sa pagpasok ayon sa tungkulin sa pamamagitan ng kasapian sa samahan, pahintulot sa bahagi, at mga landas ng pagsulat ayon sa tungkulin.', 'Magagamit ang MFA sa pamamagitan ng mga TOTP factor mula sa app na nagpapatunay.', 'Maaaring mangailangan ang sensitibong bahagi ng ERP ng mas mataas na pagpapatunay sa AAL2 bago payagang makapasok.'] },
        { title: 'Paghihiwalay ng Datos', items: ['Nakasaklaw ang paghihiwalay sa antas ng kapaligiran ayon sa mga pagkakakilanlan ng samahan at patakaran sa seguridad ng database.', 'Nakatali ang pagbasa at pagsulat sa operasyon sa aktibong konteksto ng samahan.', 'Lohikal ang paghihiwalay ng datos sa pinagsasaluhang kapaligiran ng aplikasyon at hindi nakabatay sa hiwalay na salansan ng aplikasyon bawat kapaligiran.'] },
        { title: 'Pagho-host at Imprastraktura', items: ['Pinamamahalaan ang mga serbisyo sa likod ng sistema sa pamamagitan ng Supabase.', 'Inihahatid ang pampublikong harapan sa pamamagitan ng Vercel.', 'Gumagamit ng HTTPS/TLS para sa pag-encrypt habang ipinapadala.', 'Pinamamahalaan ng tagapagbigay ang pinagbabatayang imprastraktura sa ulap at hindi ito direktang pinatatakbo ng ZANVROX.'] },
        { title: 'Seguridad sa Operasyon', items: ['Kasama sa mga tarangkahan ng paglabas ang pagsusuri ng lint, unit test, web test, build, at mga script sa pagpapatunay bago ang pasya sa paglabas.', 'Ginagamit ang Playwright E2E coverage at naka-host na smoke check para sa pagpapatunay ng kritikal na daloy ng trabaho.', 'Kasama sa pagbabantay ng dependency ang npm audit sa CI para sa pagsusuri ng mga pakete na may mataas na panganib.', 'Nililinis ang mga tala ng aplikasyon para mabawasan ang hindi sinasadyang paglantad ng elektronikong liham, token, at iba pang sensitibong patlang.'] },
      ],
      subprocessors: {
        title: 'Mga subprocessor',
        subtitle: 'Kasalukuyang pampublikong buod ng mga tagapagbigay ng ikatlong panig na ginagamit sa pagpapatakbo ng serbisyo.',
        items: [
          { name: 'Supabase', support: 'Pinamamahalaang plataporma sa likod ng sistema para sa database, pagpapatunay, imbakan, at daloy sa panig ng server.' },
          { name: 'Vercel', support: 'Pinamamahalaang pagho-host at paghahatid ng harapan para sa pampublikong karanasan sa web.' },
          { name: 'Resend', support: 'Paghahatid ng transaksyonal na elektronikong liham para sa limitadong komunikasyon at pagruruta ng mga potensyal na kliyente mula sa pook-sapot.' },
        ],
        note: 'Ginagamit lang ang mga tagapagbigay na ito kung kinakailangan para sa pagpapatakbo ng serbisyo, paghahatid, o transaksyonal na komunikasyon.',
      },
      disclosures: {
        title: 'Pagiging malinaw at kasalukuyang limitasyon',
        subtitle: 'Mga konserbatibong pahayag na tumutugma sa mga kontrol na magagamit ngayon.',
        items: ['Walang pahayag ng awtomatikong paghahain: suporta lamang sa daloy na handa para sa portal.', 'Walang nakatagong bandila ng kakayahan para sa pampublikong kakayahan.', 'May mga tala at snapshot na nasusuri upang suportahan ang kilos sa produksyon.', 'Umaasa ang kasalukuyang MFA sa TOTP mula sa app na nagpapatunay at hindi ito lumalaban sa phishing.', 'Ipinapatupad ang mas mataas na pagpapatunay sa sensitibong ruta sa halip na gawing pangkalahatang kahilingan sa bawat sesyon.', 'Hindi pa magagamit ang WebAuthn at pagpapatunay na batay sa passkey.'],
      },
      cta: { title: 'Ugnayan para sa seguridad', subtitle: 'Gamitin ang kasalukuyang landas ng ugnayan para humiling ng buod ng seguridad o para sa kasunod na tanong sa seguridad/pagsunod.', primary: { label: 'Humiling ng buod ng seguridad', path: '/contact' }, secondary: { label: 'Makipag-ugnayan para sa seguridad/pagsunod', path: '/contact' } },
    },
    integrations: {
      heroTitle: 'Pagsasama at API para sa kontroladong pakikipag-ugnayan.',
      heroSubtitle: 'Ilabas ang datos at mga daloy nang hindi nilalaktawan ang tuntunin ng negosyo.',
      posture: {
        title: 'Paninindigan sa pagsasama',
        subtitle: 'Kasalukuyang kakayahan sa pakikipag-ugnayan.',
        items: ['PostgREST API surface sa ibabaw ng kontroladong schema.', 'Edge functions para sa pinag-ugnay na daloy ng pagsasama.', 'SQL functions para sa atomikong pagsusulat na mataas ang panganib.'],
      },
      publication: {
        title: 'Mga pamantayan sa pagsasama',
        subtitle: 'Pampublikong paninindigan sa pagpapatupad para sa kahandaan sa paglulunsad.',
        items: ['Istruktura na inuuna ang API na may malinaw na pagmamay-ari ng ruta.', 'Mga hangganan ng pagpasok na may kaalaman sa kapaligiran para sa lahat ng daloy ng pagsasama.', 'Mga pagluluwas ng operasyon sa CSV/PDF para sa portal at daloy ng pagsusuri.'],
      },
    },
    ai: {
      heroTitle: 'AI sa operasyon na may pananggalang para sa malalaking organisasyon.',
      heroSubtitle: 'Magagamit ang tulong ng AI para sa mga daloy ng pag-alalay na may kontrol ng tao.',
      scope: {
        title: 'Saklaw ng AI',
        subtitle: 'Magagamit na ngayon para sa kontroladong mga gamit sa pag-alalay.',
        items: ['Tulong ng AI batay sa konteksto sa mga interface ng operasyon.', 'Panloob na tulong sa pakikipagtulungan sa pamamagitan ng mga daloy ng usapan.', 'Nananatili ang pagsusuri ng tao para sa mga aksyong sensitibo sa pagsunod.'],
      },
      note: 'Pang-alalay ang mga rekomendasyon ng AI. Ang huling aksyong pang-operasyon at pang-pagsunod ay nananatiling kinukumpirma ng gumagamit.',
    },
    pricing: {
      ...base.pages.pricing,
      heroTitle: 'Presyo para sa nakabalangkas na operasyon at kontroladong pagpapalawak.',
      heroSubtitle: 'Magsimula sa pangunahing kontrol sa pananalapi, palawakin patungo sa operasyon habang tumataas ang kumplikasyon, at lumipat lang sa pasadyang paglulunsad kapag kailangan na ang istruktura sa maraming lokasyon, mas mataas na pag-apruba, tulong sa paunang pagsasaayos, pagsasama, o pagsusuri sa seguridad.',
      packagesTitle: 'Pampublikong presyo para sa pananalapi, operasyon, at may-gabay na paglulunsad',
      packagesSubtitle: 'Malinaw na presyo sa CAD para sa maliliit at katamtamang negosyo sa Canada na kailangan ng nakabalangkas na daloy ng trabaho ngayon at kapani-paniwalang landas patungo sa mas malawak na kontrol sa operasyon sa paglipas ng panahon.',
      launchBadge: 'May taunang pagsingil',
      launchOfferLabel: 'Kasama sa taunang batayang subscription ang isang buwang libre kapag siningil taun-taon.',
      launchOfferNote: 'Nakabatay pa rin sa paggamit ang presyo ng pasahod, at magagamit ang May-gabay na Pagpapatupad kapag kailangan ang mas nakabalangkas na paglulunsad.',
      popularLabel: 'Malakas na tugma para sa 10-50 empleyado',
      priceSuffixMonthly: '/buwan',
      billedMonthlyLabel: 'Buwanang pagsingil',
      billedAnnuallyLabel: 'Taunang pagsingil',
      fromLabel: 'Mula',
      customLabel: 'Pasadya',
      includesLabel: 'Kasama',
      entitiesIncludedLabel: 'Saklaw sa komersyo',
      usersIncludedLabel: 'Kasamang gumagamit',
      billingToggle: { monthly: 'Buwanan', annual: 'Taunan', annualBadge: '1 buwang libre', helper: 'Binabago lang ng taunang pagsingil ang termino ng batayang subscription. Nananatiling batayang bayad kasama ang bilang ng empleyado ang presyo ng pasahod.' },
      pricingNote: 'Lahat ng presyo ay nasa CAD. Hiwalay na dagdag ang pasahod. Dinisenyo ang mga plano sa paligid ng nakabalangkas na operasyon, kontroladong daloy ng trabaho, kakayahang masuri, at disenyo ng produktong maingat sa seguridad nang hindi masyadong maagang itinutulak ang saklaw para sa malalaking organisasyon. Tumutulong ang ZANVROX na ayusin ang mga daloy ng pananalapi, pasahod, at buwis, ngunit hindi nito pinapalitan ang payo sa pagkuwenta, batas, o buwis.',
      tiers: [
        { slug: 'finance-core', name: 'Pundasyong Pinansyal', summary: 'Para sa mga kumpanyang nangangailangan ng disiplinadong pundasyong pinansyal na may pagkuwenta, pagsingil, gastos, ulat, at malinaw na landas ng sariling pagsasaayos.', entitiesLabel: 'Saklaw ng iisang kumpanya', usersLabel: 'Hanggang 3 gumagamit', monthly: { kind: 'fixed', amount: 179, note: 'Kasama ang gabay sa sariling pagsasaayos, kontroladong daloy ng pananalapi, at tulong sa elektronikong liham na may tugon sa 48h.' }, annual: { kind: 'fixed', amount: 179, badge: '1 buwang libre', note: 'Siningil taun-taon sa CAD 1,969 para sa batayang subscription.', secondaryNote: 'Hiwalay pa rin ang pasahod at mas malawak na saklaw ng operasyon kapag kailangan.' }, included: ['Mga daloy ng pagkuwenta', 'Pagsingil', 'Pagkuha ng gastos', 'Ulat sa pananalapi', 'Gabay sa sariling pagsasaayos', 'Tulong sa elektronikong liham (tugon sa 48h)'], ctaLabel: 'Suriin ang Pundasyong Pinansyal' },
        { slug: 'operations', name: 'Operasyon', isPopular: true, summary: 'Para sa mga pangkat na kailangang sabay gumana ang pananalapi at operasyon sa imbentaryo, bodega, pangunahing produksyon, at kontroladong pag-apruba.', entitiesLabel: 'Saklaw ng iisang kumpanya', usersLabel: 'Hanggang 10 gumagamit', monthly: { kind: 'fixed', amount: 649, note: 'Kasama ang pangunahing tulong sa elektronikong liham na may tugon sa 24h para sa mas aktibong pangkat sa operasyon.' }, annual: { kind: 'fixed', amount: 649, badge: '1 buwang libre', note: 'Siningil taun-taon sa CAD 7,139 para sa batayang subscription.', secondaryNote: 'Inirerekomenda kapag kailangan ng operasyon ng mas mahigpit na kontrol sa paninda, paggalaw sa bodega, BOM, at mga daloy ng produksyon.' }, included: ['Lahat ng nasa Pundasyong Pinansyal', 'Kontrol sa imbentaryo', 'Mga daloy sa bodega', 'Produksyon (BOM)', 'Pag-apruba at pamamahala', 'Pangunahing tulong sa elektronikong liham (tugon sa 24h)'], ctaLabel: 'Suriin ang Operasyon' },
        { slug: 'enterprise', name: 'Pasadya', summary: 'Para sa mga pangkat sa maraming lokasyon na nangangailangan ng mas mataas na pag-apruba, pagsusuri sa seguridad, pasadyang paunang pagsasaayos, pagsasama, nakalaang tulong, o mas nakabalangkas na paglulunsad.', entitiesLabel: 'Maraming lokasyon o pasadyang saklaw', usersLabel: 'Pasadyang saklaw ng gumagamit', monthly: { kind: 'custom', label: 'Pasadya', note: 'Nakasaklaw na pagsusuri para sa paglulunsad sa maraming lokasyon, may-gabay na pagsasaayos, pagsasama, pangangailangan sa pamamahala, at pagsusuri sa seguridad.' }, annual: { kind: 'custom', label: 'Pasadya', note: 'Direktang itinatakda ang pasadyang presyo ayon sa istruktura ng pagpapatakbo, pangangailangan sa paglulunsad, at konteksto ng pagpapatupad.' }, included: ['Paglulunsad sa maraming lokasyon', 'Mas mataas na pamamahala', 'Pagsasama', 'Landas ng pagsusuri sa seguridad', 'May-gabay na pagpapatupad at tulong sa paglulunsad'], ctaLabel: 'Humiling ng pasadyang pagsusuri' },
      ],
      payrollAddon: { title: 'Dagdag na pasahod', summary: 'Pinananatiling malinaw sa komersyal na usapan ang hiwalay na presyo ng pasahod habang pinapanatili ang suporta sa daloy ng pasahod sa Canada para sa mga pangkat na nangangailangan nito.', priceLabel: 'CAD 59 / buwan + CAD 6 / empleyado / buwan', annualPriceLabel: 'CAD 59 / buwan + CAD 6 / empleyado / buwan', monthlyNote: 'Kasama ang pagpapatakbo ng pasahod sa Canada, suporta sa daloy ng pagpapadala ng bayad, pay stub, mga tala at pagluluwas para suportahan ang pagsusuri sa pagtatapos ng taon, at pagsasama sa pagkuwenta. Maaaring may buwanang pinakamababa habang nasa paglulunsad.', annualNote: 'Pinananatili ng dagdag na pasahod ang parehong istruktura ng batayang bayad kasama ang presyo ayon sa empleyado kahit taunang pagsingil maliban kung may ibang nakatakdang ayos.', included: ['Pagpapatakbo ng pasahod sa Canada', 'Suporta sa daloy ng pagpapadala ng bayad', 'Mga pay stub', 'Mga tala at pagluluwas para sa pagsusuri', 'Pagsasama sa pagkuwenta'], ctaLabel: 'Magtanong tungkol sa pasahod' },
      onboardingPackage: { title: 'May-gabay na Pagpapatupad', summary: 'Opsyonal na isang-beses na may-gabay na pagsasaayos para sa mga pangkat na gusto ng pagkakaayon sa operasyon, tinutulungang paglulunsad, at mas nakabalangkas na simula ng pagpapatupad.', priceLabel: 'CAD 3,500 hanggang 7,500 isang beses', included: ['May-gabay na pagsasaayos ng sistema', 'Pagsusuri ng pagkakaayon sa operasyon', 'Pagsusuri ng talaan ng mga account', 'Pagsasaayos ng buwis', 'Gabay sa pagpasok ng datos', 'Tinutulungang sesyon ng pagsasanay sa paglulunsad'], note: 'Opsyonal. Maaari pa ring magsimula ang karaniwang mga plano sa sariling pagsasaayos kapag sapat ang mas magaan na paglulunsad.', ctaLabel: 'Humiling ng may-gabay na pagsasaayos' },
      supportTiers: { title: 'Istruktura ng tulong', subtitle: 'Direktang ipinapakita ang tulong para masuri ng mga pangkat ang saklaw ng pagpapatakbo, inaasahang tugon, at paninindigan sa paglulunsad.', items: [{ name: 'Pundasyong Pinansyal', body: 'Tulong sa elektronikong liham na may tugon sa loob ng 48h.' }, { name: 'Operasyon', body: 'Pangunahing tulong sa elektronikong liham na may tugon sa loob ng 24h.' }, { name: 'Pasadya', body: 'May-gabay na tulong sa paglulunsad, tuwirang daan ng suporta, at nakatakdang usapan sa pagpapatupad.' }] },
      comparison: { title: 'Paghahambing ng mga plano', subtitle: 'Gamitin ito para magpasya kung kailangan mo ng nakabalangkas na kontrol sa pananalapi, konektadong operasyon, o pasadyang paglulunsad.', featureLabel: 'Kakayahan', rows: [{ label: 'Pagkuwenta', values: [true, true, true] }, { label: 'Pagsingil', values: [true, true, true] }, { label: 'Gastos', values: [true, true, true] }, { label: 'Mga ulat sa pananalapi', values: [true, true, true] }, { label: 'Imbentaryo', values: [false, true, true] }, { label: 'Bodega', values: [false, true, true] }, { label: 'Produksyon (BOM)', values: [false, true, true] }, { label: 'Pag-apruba at pamamahala', values: [false, true, true] }, { label: 'Paglulunsad sa maraming lokasyon', values: [false, false, true] }, { label: 'Mas mataas na pag-apruba', values: [false, true, true] }, { label: 'Pagsasama', values: [false, false, true] }, { label: 'Antas ng tulong', values: ['Elektronikong liham / 48h', 'Pangunahing elektronikong liham / 24h', 'Tuwirang daan'] }, { label: 'Tulong sa paunang pagsasaayos', values: ['Sariling pagsasaayos', 'Sariling pagsasaayos', 'Kasama'] }, { label: 'Kasamang gumagamit', values: ['3', '10', 'Pasadya'] }], notesTitle: 'Mga tala sa komersyo', notes: ['Hiwalay na dagdag ang pasahod.', 'Opsyonal at hiwalay ang presyo ng May-gabay na Pagpapatupad para sa mga pangkat na gusto ng mas nakabalangkas na paglulunsad.', 'Ang Pasadya ang landas para sa saklaw sa maraming lokasyon, pagsasama, pagsusuri sa seguridad, at konteksto ng may-gabay na pagpapatupad.', 'Dinisenyo ang komersyal na modelo para panatilihin ang pagiging malinaw habang sinusuportahan ang kontroladong daloy ng trabaho at kakayahang masuri habang lumalaki ang pangangailangan.'], annualNote: 'Kasama sa taunang batayang mga plano ang isang buwang libre.' },
      faq: { title: 'Mga tanong sa presyo', subtitle: 'Mga sagot para sa mga pangkat na gustong magsuri muna bago tumawag.', items: [{ question: 'Kailangan ko ba ng pagpapakita bago magsimula?', answer: 'Hindi. Ang nilalayong landas ay sariling pagsusuri muna: panoorin ang buod, suriin ang produkto, tingnan ang presyo, at gamitin ang kapaligiran ng pagsusuri sa browser bago humiling ng may-gabay na sesyon.' }, { question: 'Kasama ba ang pasahod sa batayang mga plano sa ERP?', answer: 'Hindi. Ibinebenta ang pasahod bilang hiwalay na dagdag na may buwanang batayang bayad at presyo kada empleyado.' }, { question: 'Kailangan ba ang May-gabay na Pagpapatupad?', answer: 'Hindi. Opsyonal ito. Puwedeng magsimula ang Pundasyong Pinansyal at Operasyon sa sariling pagsasaayos, habang magagamit ang May-gabay na Pagpapatupad para sa mga pangkat na gusto ng mas nakabalangkas na paglulunsad.' }, { question: 'Anong tulong ang kasama sa bawat plano?', answer: 'Kasama sa Pundasyong Pinansyal ang tulong sa elektronikong liham sa loob ng 48h, sa Operasyon ang pangunahing tulong sa elektronikong liham sa loob ng 24h, at sa Pasadya ang may-gabay na usapan sa paglulunsad kasama ang tuwirang daan ng suporta.' }] },
      ctaPrimary: { label: 'Buksan ang kapaligiran ng pagsusuri', path: '/resources#demo-environment' },
      ctaSecondary: { label: 'Makipag-ugnayan para sa pasadyang paglulunsad', path: '/contact' },
    },
    resources: {
      ...base.pages.resources,
      heroTitle: 'Mga sanggunian para sa pagsusuri ng produkto, pagsusuri sa seguridad, at pagpaplano ng paglulunsad.',
      heroSubtitle: 'Gamitin ang mga pampublikong materyal na ito para suriin ang tugma ng produkto, paninindigan sa seguridad, at mga pagpipilian sa pagsusuri bago humiling ng mas malalim na usapan.',
      sections: [
        { title: 'Buod ng produkto at mga sanggunian sa pagsusuri', description: 'Suriin ang buod ng produkto, saklaw ng daloy ng trabaho, at paraan ng paunang pagsasaayos bago maglaan ng mas malalim na oras sa pagsusuri.', cta: 'Suriin ang produkto', path: '/product' },
        { title: 'Buod ng seguridad', description: 'Suriin ang paghihiwalay ng kapaligiran, kontrol sa pagpasok, mga subprocessor, at kasalukuyang limitasyon sa seguridad sa iisang pampublikong buod.', cta: 'Suriin ang seguridad', path: '/security' },
        { title: 'Kapaligiran ng pagsusuri at may-gabay na pagsusuri ng produkto', description: 'Magsimula sa pinagsasaluhang kapaligiran ng pagsusuri para sa paunang pagsusuri, saka makipag-ugnayan sa pangkat kung kailangan mo ng mas nakabalangkas na usapan sa produkto.', cta: 'Buksan ang kapaligiran ng pagsusuri', path: '/resources#demo-environment' },
        { title: 'Ugnayan at karagdagang dokumentasyon', description: 'Gamitin ang landas ng ugnayan para sa mga tanong sa seguridad o pagsunod, kahilingan sa may-gabay na pagsusuri, o karagdagang detalye sa pagsusuri.', cta: 'Makipag-ugnayan sa pangkat', path: '/contact' },
      ],
      demoEnvironment: { title: 'Kapaligiran ng pagsusuri', subtitle: 'Kapaligirang gumagana sa browser para sa paunang pagsusuri ng produkto gamit ang kathang-isip na halimbawang datos.', accessTitle: 'Pinagsasaluhang pagpasok sa pagsusuri', accessIntro: 'May pinagsasaluhang pagpasok para sa maagang pagsusuri ng produkto. Maaaring makipag-ugnayan sa ZANVROX ang mga pangkat na nangangailangan ng mas malalim o mas nakabalangkas na pagsusuri.', emailLabel: 'Gumagamit ng kapaligiran', emailValue: 'Use your work email', passwordLabel: 'Kodigo sa pagpasok', passwordValue: 'Set during signup', note: 'Walang kailangang i-install. Para lang sa pagsusuri ang kapaligirang ito, gumagamit ng kathang-isip na halimbawang datos, at hindi para sa tunay na datos ng kumpanya, empleyado, kostumer, pasahod, o pananalapi.', guidance: ['Gamitin ang kapaligiran para sa paunang pagsusuri ng pag-navigate, saklaw ng daloy ng trabaho, at pangkalahatang tugma ng produkto.', 'Ituring ang kapaligiran bilang pinagsasaluhang tanaw sa pagsusuri at hindi bilang produksyon, piloto, o kapaligiran para sa paglipat ng datos.', 'Para sa mas malalim na pagsusuri, tanong sa seguridad/pagsunod, o karagdagang dokumentasyon, gamitin ang landas ng ugnayan pagkatapos ng paunang pagsusuri.'], cta: { label: 'Buksan ang kapaligiran ng pagsusuri', path: '/resources#demo-environment' } },
      sitemap: { title: 'Mga materyal sa pagsusuri', subtitle: 'Sadyang maikli ang pampublikong pook at nakatuon sa mga materyal na pinakamahalaga sa maagang pagsusuri.', items: ['Buod ng produkto at saklaw ng daloy ng trabaho', 'Pampublikong presyo at paraan ng paunang pagsasaayos', 'Buod ng seguridad at kasalukuyang paninindigan sa kontrol', 'Kapaligiran ng pagsusuri na may kathang-isip na halimbawang datos', 'Landas ng ugnayan para sa may-gabay na pagsusuri at kasunod na mga tanong', 'Mga tuntuning legal at impormasyon sa pagkapribado'] },
      design: { title: 'Paano gamitin ang mga sangguniang ito', subtitle: 'Isang simpleng landas ng pagsusuri para sa mga pangkat na gustong suriin muna ang tugma ng produkto at isali lang ang pangkat kapag kailangan na ng mas maraming detalye.', directionTitle: 'Paunang pagsusuri ng produkto', componentsTitle: 'Pagsusuri sa seguridad at pagsunod', statesTitle: 'Kailan makikipag-ugnayan sa pangkat', direction: ['Magsimula sa Produkto, Presyo, at Mga Sanggunian para maunawaan ang saklaw, paninindigan sa paunang pagsasaayos, at tugmang pangkomersyo.', 'Gamitin ang kapaligiran ng pagsusuri para sa maagang aktuwal na pagsusuri gamit lamang ang kathang-isip na datos.', 'Ituring ang mga pampublikong materyal bilang unang patong ng pagsusuri bago humiling ng mas malalim na usapan.'], components: ['Gamitin ang Buod ng Seguridad para sa paghihiwalay ng kapaligiran, kontrol sa pagpasok, mga subprocessor, at kasalukuyang limitasyon.', 'Gamitin ang landas ng ugnayan para sa mga tanong sa seguridad/pagsunod o para humiling ng karagdagang dokumentasyon.', 'Panatilihing nakaangkla ang mga tanong sa pagsusuri sa kasalukuyang inilathalang saklaw at pahayag.'], states: ['Humiling ng may-gabay na pagsusuri ng produkto kapag may konkretong tanong ang iyong pangkat tungkol sa daloy ng trabaho o paglulunsad.', 'Makipag-ugnayan sa pangkat kung kailangan mo ng mas maraming detalye kaysa sa nasa pampublikong materyal sa pagsusuri.', 'Gamitin ang kasalukuyang landas ng ugnayan para humiling ng buod ng seguridad at kasunod na tanong sa seguridad/pagsunod.'] },
    },
    about: {
      ...base.pages.about,
      heroKicker: 'Tungkol sa ZANVROX',
      heroTitle: 'Praktikal na ERP na nakapuwesto para sa kapani-paniwalang paglulunsad, hindi para sa palabas ng malalaking organisasyon.',
      heroSubtitle: 'Inilalahad ang ZANVROX bilang modernong ERP para sa maliliit at katamtamang negosyo sa Canada na gusto ng mas mahigpit na kontrol sa operasyon, mas kaunting magkakahiwalay na sistema, at mas malinaw na landas ng tulong.',
      heroPrimaryCta: { label: 'Suriin ang produkto', path: '/product' },
      heroSecondaryCta: { label: 'Makipag-ugnayan sa pangkat', path: '/contact' },
      heroPreview: { ...base.pages.about.heroPreview, title: 'Maikling tanaw sa pagpoposisyon', caption: 'Kontrol sa operasyon laban sa pagkalat ng software', callouts: [{ status: 'ready', text: 'Malinaw na paninindigan sa tulong' }, { status: 'ready', text: 'Landas ng pagsusuring pinangungunahan ng produkto' }] },
      principles: { title: 'Tatlong prinsipyong nasa likod ng pook', subtitle: 'Inayos ang pampublikong pagpoposisyon para sa realidad ng pagpapatakbong pinamumunuan ng tagapagtatag nang hindi ibinababa ang pamantayan ng produkto.', items: [{ title: 'Kalinawan', body: 'Sabihin nang diretso kung ano ang ginagawa ng produkto, ano ang sinusuportahan nito, at saan kailangan pa rin ang pagsusuri.' }, { title: 'Kontrol', body: 'Tumutok sa kakayahang masuri, pamamahala, at tanaw sa operasyon sa halip na pinalobong ingay ng SaaS.' }, { title: 'Praktikal na paglulunsad', body: 'Gawing posible ang sariling pagsasaayos habang may opsyonal na tulong ng eksperto kapag tumataas ang kumplikasyon.' }] },
      operatingModel: [{ title: 'Ginawa para sa maliliit at katamtamang negosyo sa Canada', subtitle: 'Target ng pampublikong pook-sapot ang mga kumpanyang nangangailangan ng kapani-paniwalang kontrol sa ERP nang walang gastos sa pagkonsulta para sa malalaking organisasyon sa unang araw.', items: ['Pinakamainam sa humigit-kumulang 10-50 empleyado', 'Malakas ang halaga kapag hati sa napakaraming kasangkapan ang pananalapi at operasyon', 'Malinaw na landas mula sa pundasyong pinansyal patungo sa operasyon at saklaw ng dagdag na pasahod'] }, { title: 'May disiplinang pangkomersyo', subtitle: 'Dinisenyo ang pook para bawasan ang mababang kalidad na pulong at gawing malinaw ang inaasahan bago ang unang usapan.', items: ['Opsyonal na pagpapakita sa halip na landas na nagsisimula agad sa pagpapakita', 'Pampublikong presyo na may antas ng tulong at inaasahan sa paunang pagsasaayos', 'Mga pahayag sa seguridad at pamamahala na nakaayon sa tunay na paninindigan ng produkto'] }],
      cta: { title: 'Tingnan kung bagay ang paraan ng pagpapatakbo sa iyong pangkat', subtitle: 'Gamitin ang Produkto, Presyo, at Mga Sanggunian para suriin ang tugma bago makipag-ugnayan.', primary: { label: 'Tingnan ang presyo', path: '/pricing' }, secondary: { label: 'Pumunta sa ugnayan', path: '/contact' } },
    },
    contact: {
      ...base.pages.contact,
      heroTitle: 'Makipag-ugnayan lang sa pangkat kapag kailangan mo ng tulong sa totoong tanong sa pagsusuri.',
      heroSubtitle: 'Ang nilalayong daloy ay buod ng produkto, pagsusuri ng produkto, pagsusuri ng presyo, pagsusuri sa browser, at pagkatapos ay opsyonal na ugnayan o kahilingan sa may-gabay na pagpapakita.',
      conversion: { title: 'Inirerekomendang daloy ng pagsusuri', subtitle: 'Binabawasan nito ang hindi kailangang mga pulong at nagbibigay ng mas magandang konteksto kapag may nakipag-ugnayan na.', cards: [{ title: 'Panoorin ang buod ng produkto', body: 'Magsimula sa video para maunawaan ang paraan ng pagpapatakbo at paninindigan ng produkto.' }, { title: 'Suriin ang mga kakayahan', body: 'Gamitin ang mga pahina ng Produkto, Presyo, at Seguridad para suriin ang salansan nang walang tawag.' }, { title: 'Buksan ang kapaligiran ng pagsusuri', body: 'Patunayan ang UI gamit ang kathang-isip na datos bago humiling ng may-gabay na sesyon.' }, { title: 'Humingi ng tulong kung kailangan', body: 'Gamitin ang mga form sa ibaba para sa opsyonal na pagpapakita o nakatutok na tanong sa produkto.' }] },
      supportBlock: { title: 'Inaasahang tulong', subtitle: 'Lahat ng daloy ng ugnayan sa pook-sapot ay dumadaan sa support@zanvrox.com.', items: ['Pundasyong Pinansyal: tulong sa elektronikong liham na may tugon sa 48h', 'Operasyon: pangunahing tulong sa elektronikong liham na may tugon sa 24h', 'Malaking Organisasyon: tuwirang daan ng suporta kasama ang tulong sa paunang pagsasaayos'] },
      pricingContext: { title: 'Napiling konteksto ng presyo', subtitle: 'Nakadikit ang konteksto ng presyo sa iyong kahilingan para manatiling nakaangkla ang kasunod na sagot sa napili mong pagsasaayos.', labels: { plan: 'Plano', billing: 'Pagsingil', payroll: 'Pasahod', offer: 'Alok', notSelected: 'Hindi napili', payrollInterested: 'Napili ang dagdag na pasahod', payrollNotSelected: 'Walang napiling dagdag na pasahod' } },
      demoForm: { title: 'Humiling ng may-gabay na pagpapakita', helper: 'Gamitin ito kapag nasuri na ng iyong pangkat ang produkto at gusto ninyo ng may-gabay na pagpapakita.', confirmation: 'Matagumpay na naipadala ang kahilingan mo para sa may-gabay na pagpapakita. Sasagot kami sa elektronikong liham.', submittingCta: 'Ipinapadala...', submitError: 'Hindi namin naisumite ang kahilingan mo. Pakisubukang muli.', messageHint: 'Opsyonal. Gamitin ito para ilarawan ang kasalukuyan mong salansan, panahon ng paglulunsad, o tanong sa pasahod.', fields: { name: 'Pangalan*', company: 'Kumpanya*', email: 'Elektronikong liham sa trabaho*', companySize: 'Laki ng kumpanya*', interestArea: 'Larangan ng interes*', message: 'Opsyonal na mensahe', consent: 'Sumasang-ayon akong makontak ng ZANVROX tungkol sa kahilingang pangnegosyo na ito. Gagamitin lang namin ang datos para tumugon sa tanong.' }, placeholders: { email: 'name@company.com', companySize: 'Piliin ang laki ng kumpanya', interestArea: 'Piliin ang larangan ng interes', message: 'Ano ang gusto mong patunayan sa may-gabay na sesyon?' }, options: { companySizes: ['1-10 empleyado', '10-50 empleyado', '50-100 empleyado', '100+ empleyado'], interestAreas: ['Pundasyong Pinansyal', 'Operasyon', 'Dagdag na pasahod', 'May-gabay na Pagpapatupad', 'Paglulunsad para sa malaking organisasyon', 'Pagsasama / API'] }, errors: { name: 'Ilagay ang pangalan mo.', company: 'Ilagay ang pangalan ng kumpanya mo.', email: 'Maglagay ng wastong elektronikong liham sa trabaho.', companySize: 'Piliin ang laki ng kumpanya.', interestArea: 'Piliin ang larangan ng interes.', message: 'Panatilihing mas maikli sa 2000 character ang mensahe.', consent: 'Kailangan ang pahintulot para maisumite ang form na ito.', startedAt: 'Maghintay sandali bago magsumite.', website: 'Na-trigger ang proteksyon laban sa spam.' }, cta: 'Humiling ng may-gabay na pagpapakita' },
      briefForm: { title: 'Magtanong tungkol sa produkto', helper: 'Gamitin ito para sa mga tanong tungkol sa tugma ng produkto, tulong, paunang pagsasaayos, pagpapatupad, o saklaw ng pasahod.', confirmation: 'Matagumpay na naipadala ang mensahe mo. Sasagot kami sa elektronikong liham.', submittingCta: 'Ipinapadala...', submitError: 'Hindi namin naisumite ang kahilingan mo. Pakisubukang muli.', messageHint: 'Opsyonal. Gamitin ito kung gusto mong ilarawan ang daloy ng trabaho, pangangailangan sa tulong, o tanong sa pagpapatupad.', fields: { name: 'Pangalan*', company: 'Kumpanya*', email: 'Elektronikong liham sa trabaho*', companySize: 'Laki ng kumpanya*', interestArea: 'Larangan ng interes*', message: 'Opsyonal na mensahe', consent: 'Sumasang-ayon akong makatanggap ng hiniling na kasunod na sagot mula sa ZANVROX.' }, placeholders: { email: 'name@company.com', companySize: 'Piliin ang laki ng kumpanya', interestArea: 'Piliin ang larangan ng interes', message: 'Ano ang gusto mong malinawan bago gumastos ng mas maraming oras sa pagsusuri ang iyong pangkat?' }, options: { companySizes: ['1-10 empleyado', '10-50 empleyado', '50-100 empleyado', '100+ empleyado'], interestAreas: ['Tugma ng produkto', 'Presyo at tulong', 'Pagpasok sa kapaligiran ng pagsubok', 'Pagpasok ng datos', 'Dagdag na pasahod', 'May-gabay na Pagpapatupad'] }, errors: { name: 'Ilagay ang pangalan mo.', company: 'Ilagay ang pangalan ng kumpanya mo.', email: 'Maglagay ng wastong elektronikong liham sa trabaho.', companySize: 'Piliin ang laki ng kumpanya.', interestArea: 'Piliin ang larangan ng interes.', message: 'Panatilihing mas maikli sa 2000 character ang mensahe.', consent: 'Kailangan ang pahintulot para maisumite ang form na ito.', startedAt: 'Maghintay sandali bago magsumite.', website: 'Na-trigger ang proteksyon laban sa spam.' }, cta: 'Ipadala ang tanong' },
    },
    legal: {
      privacy: { title: 'Patakaran sa Pagkapribado', updated: 'Marso 5, 2026', updatedLabel: 'Huling in-update', paragraphs: ['Kinokolekta ng ZANVROX ang impormasyong pang-ugnayan sa negosyo na ipinapasa sa pook-sapot na ito para sa pagsusuri ng produkto, pagtatakda ng pagpapakita, at kahilingan sa dokumentasyon.', 'Pinoproseso namin ang ipinadalang datos para lamang sa benta at paunang pagsusuri ng produkto.', 'Maaari kang humiling ng pagtingin, pagwawasto, o pagbura ng ipinadalang datos sa pamamagitan ng support@zanvrox.com.'] },
      terms: { title: 'Mga Tuntunin ng Serbisyo', updated: 'Marso 5, 2026', updatedLabel: 'Huling in-update', paragraphs: ['Nagbibigay ang pook na ito ng impormasyon sa produkto at mga form sa pagtanggap ng potensyal na kliyente para sa komersyal na pagsusuri ng ZANVROX ERP.', 'Pang-impormasyon lamang ang laman ng pook-sapot at hindi ito bumubuo ng nakabibigkis na pangako sa produkto.', 'Pinal ang saklaw ng produkto at mga tuntuning pangkomersyo sa mga pinirmahang kasunduan.'] },
    },
    notFound: { title: 'Hindi nakita ang pahina', subtitle: 'Hindi tumutugma ang URL sa inilathalang istruktura ng pook ng ZANVROX.', cta: 'Pumunta sa simula' },
  },
  footer: {
    ...base.footer,
    companyDescription: 'Pinagsamang ERP para sa maliliit at katamtamang negosyo sa Canada na nangangailangan ng pananalapi, operasyon, pagsunod, at pasahod sa iisang kontroladong salansan.',
    headquarters: 'Toronto, Ontario, Canada',
    sections: [
      { title: 'Produkto', links: [{ label: 'Buod ng produkto', path: '/product' }, { label: 'Presyo', path: '/pricing' }, { label: 'Sanggunian', path: '/resources' }, { label: 'Ugnayan', path: '/contact' }] },
      { title: 'Tiwala at Legal', links: [{ label: 'Seguridad', path: '/security' }, { label: 'Seguridad / Pagsunod', path: '/security' }, { label: 'Humiling ng impormasyon sa seguridad', path: '/contact' }, { label: 'Pagkapribado', path: '/legal/privacy' }, { label: 'Mga Tuntunin', path: '/legal/terms' }] },
    ],
    links: [
      { label: 'Produkto', path: '/product' },
      { label: 'Presyo', path: '/pricing' },
      { label: 'Sanggunian', path: '/resources' },
      { label: 'Seguridad', path: '/security' },
      { label: 'Tungkol', path: '/about' },
      { label: 'Ugnayan', path: '/contact' },
      { label: 'Pagkapribado', path: '/legal/privacy' },
      { label: 'Mga Tuntunin', path: '/legal/terms' },
    ],
  },
  seo: {
    home: { title: 'ZANVROX | ERP sa Canada para sa Pananalapi, Operasyon, at Kontrol', description: 'Pinagsamang ERP para sa maliliit at katamtamang negosyo sa Canada na may pagkuwenta, pagsingil, imbentaryo, bodega, produksyon, pamamahala, daloy ng buwis, at dagdag na tulong sa pasahod.', path: '/' },
    product: { title: 'Produkto | ZANVROX', description: 'Suriin ang pananalapi, operasyon, pagsunod sa Canada, pamamahala, at saklaw ng dagdag na pasahod sa loob ng ZANVROX ERP.', path: '/product' },
    security: { title: 'Seguridad | ZANVROX', description: 'Suriin ang paghihiwalay ng kapaligiran, kontrol sa tungkulin, pag-apruba, pamamahala, at pananggalang sa arkitektura sa likod ng ZANVROX.', path: '/security' },
    pricing: { title: 'Presyo | ZANVROX', description: 'Suriin ang pampublikong presyo sa CAD para sa Pundasyong Pinansyal, Operasyon, pasadyang paglulunsad, dagdag na pasahod, at opsyonal na May-gabay na Pagpapatupad.', path: '/pricing' },
    resources: { title: 'Sanggunian | ZANVROX', description: 'Gamitin ang mga sanggunian ng produkto, gabay sa kapaligiran ng pagsusuri, at materyal sa buod ng seguridad para sariling suriin ang ZANVROX.', path: '/resources' },
    about: { title: 'Tungkol | ZANVROX', description: 'Alamin kung paano ipinoposisyon ng ZANVROX ang pananalapi, operasyon, pamamahala, at disiplina sa paglulunsad para sa maliliit at katamtamang negosyo sa Canada.', path: '/about' },
    contact: { title: 'Ugnayan | ZANVROX', description: 'Humiling ng opsyonal na pagpapakita o magtanong ng nakatutok na tanong tungkol sa produkto, pasahod, paunang pagsasaayos, o pagpapatupad.', path: '/contact' },
    privacy: { title: 'Patakaran sa Pagkapribado | ZANVROX', description: 'Patakaran sa pagkapribado para sa pook-sapot ng ZANVROX at kaugnay na pagproseso ng potensyal na kliyente.', path: '/legal/privacy' },
    terms: { title: 'Mga Tuntunin ng Serbisyo | ZANVROX', description: 'Mga tuntunin ng serbisyo na namamahala sa paggamit ng pook-sapot at materyal ng ZANVROX.', path: '/legal/terms' },
  },
}

export default siteContentTl
