import siteContentEn from './siteContent.en'

const base = siteContentEn

const siteContentEs = {
  ...base,
  locale: 'es',
  localeLabel: 'Español',
  labels: {
    menu: 'Menú',
    bookDemo: 'Recorrido guiado',
    tryDemo: 'Abrir espacio de trabajo',
    getTechnicalBrief: 'Contactar al equipo',
    reviewResources: 'Ver recursos',
    language: 'Idioma',
    requestQuote: 'Hablar con ventas',
  },
  navItems: [
    { label: 'Inicio', path: '/' },
    { label: 'Producto', path: '/product' },
    { label: 'Precios', path: '/pricing' },
    { label: 'Recursos', path: '/resources' },
    { label: 'Seguridad', path: '/security' },
    { label: 'Acerca de', path: '/about' },
    { label: 'Contacto', path: '/contact' },
  ],
  brand: {
    name: 'ZANVROX',
    tagline: 'Control ERP integrado para equipos pyme canadienses',
    oneLiner: 'Finanzas, operaciones, cumplimiento canadiense y nómina en una sola plataforma ERP controlada.',
  },
  pages: {
    home: {
      heroKicker: 'ERP canadiense para finanzas, operaciones y auditabilidad',
      heroTitle: 'Gestiona finanzas y operaciones en un único ERP controlado en lugar de cinco herramientas desconectadas.',
      heroSubtitle:
        'ZANVROX ayuda a los equipos pyme canadienses a centralizar contabilidad, facturación, compras, inventario, producción, aprobaciones y cumplimiento sin un proyecto de implementación pesado.',
      heroPrimaryCta: { label: 'Ver resumen del producto', path: '/#product-overview' },
      heroSecondaryCta: { label: 'Abrir espacio de evaluación', path: '/resources#demo-environment' },
      heroPreview: {
        title: 'Vista previa fiscal y de control',
        caption: 'En vivo dentro del ERP',
        callouts: [
          { status: 'ready', text: 'Informes GST/HST + PST/QST' },
          { status: 'ready', text: 'Rastro de auditoría y aprobaciones' },
        ],
      },
      video: {
        title: 'Recorrido del producto con contexto real de trabajo',
        subtitle: 'Un breve recorrido por finanzas, operaciones, flujos fiscales canadienses y preparación de nómina.',
        windowLabel: 'Video del producto',
        duration: '90 s',
        overlayLabel: 'Ver recorrido del producto',
        fallbackLabel: 'Vista previa del póster disponible',
        hasRealVideo: true,
        chapters: [
          'Contabilidad y facturación',
          'Inventario y almacén',
          'Planificación de producción',
          'Panel fiscal',
          'Mesa de trabajo de nómina',
          'Informes y aprobaciones',
        ],
        primaryCta: { label: 'Explorar producto', path: '/product' },
        secondaryCta: { label: 'Abrir espacio de evaluación', path: '/resources#demo-environment' },
      },
      trustSignals: [
        'Los flujos oficiales respaldados por proveedores se mantienen intactos donde se requieren.',
        'Cambios gobernados con aprobaciones y rastros de auditoría.',
        'Ruta de configuración autónoma para equipos pequeños con implementación guiada opcional.',
        'Postura de cumplimiento canadiense sin exageraciones de marketing.',
      ],
      statusBadges: [
        { status: 'ready', text: 'Contabilidad, facturación, gastos e informes' },
        { status: 'ready', text: 'Inventario, almacén y flujos BOM' },
        { status: 'ready', text: 'Soporte para flujos fiscales canadienses' },
        { status: 'ready', text: 'Complemento de nómina con mesa de trabajo de cierre anual' },
        { status: 'locked', text: 'Controles de gobernanza y auditabilidad' },
        { status: 'ready', text: 'Ruta de incorporación autónoma' },
      ],
      evaluationPath: {
        eyebrow: 'Embudo orientado al producto',
        title: 'Evalúa sin reservar una reunión primero',
        subtitle: 'El sitio está diseñado para reducir llamadas innecesarias y permitir que los equipos se autoevalúen.',
        cards: [
          {
            title: '1. Mira el resumen',
            body: 'Empieza con el video del producto para entender cómo encajan finanzas, operaciones, impuestos y nómina.',
          },
          {
            title: '2. Explora el producto',
            body: 'Revisa grupos funcionales, capturas y controles de gobernanza por módulo y proceso de negocio.',
          },
          {
            title: '3. Abre el espacio de evaluación',
            body: 'Usa el espacio basado en navegador con datos ficticios para validar navegación, ajuste de roles y cobertura de flujos.',
          },
          {
            title: '4. Solicita ayuda solo si la necesitas',
            body: 'Usa el formulario opcional de contacto o demo cuando tu equipo tenga una pregunta concreta de evaluación.',
          },
        ],
      },
      screenshots: {
        eyebrow: 'Pantallas y flujos',
        title: 'Pantallas diseñadas para mostrar cobertura operativa real',
        subtitle: 'Cada sección inferior está preparada para capturas reales y usa vistas previas del producto cuando una captura final todavía no está disponible.',
        items: [
          {
            title: 'Panel fiscal canadiense',
            body: 'Haz seguimiento de la preparación para presentar, familias fiscales y controles de cierre desde una sola vista financiera.',
            previewType: 'reports',
            imageKey: 'taxDashboard',
            imageAlt: 'Panel fiscal canadiense dentro de ZANVROX ERP',
          },
          {
            title: 'Gestión de inventario',
            body: 'Consulta posiciones de stock, movimiento de almacén y visibilidad por lotes sin salir del ERP.',
            previewType: 'inventory',
          },
          {
            title: 'Planificación de producción',
            body: 'Revisa órdenes de producción ligadas a BOM, consumo de materiales y progreso de ejecución en una sola superficie.',
            previewType: 'production',
          },
          {
            title: 'Informes financieros',
            body: 'Pasa de la actividad operativa a los informes de gestión sin unir herramientas por separado.',
            previewType: 'accounting',
          },
        ],
      },
      howItWorks: {
        eyebrow: 'Incorporación autónoma',
        title: 'Empieza en seis pasos guiados',
        subtitle: 'El producto está diseñado para que un equipo liderado por fundadores pueda orientarse sin un proyecto de incorporación pesado.',
        steps: [
          { icon: '1', title: 'Crear organización', bullets: ['Inicia tu espacio de trabajo', 'Define los datos básicos de la entidad legal'] },
          { icon: '2', title: 'Seleccionar país', bullets: ['Elegir Canadá', 'Cargar valores predeterminados específicos del país'] },
          { icon: '3', title: 'Elegir plantilla sectorial', bullets: ['Elegir un modelo de partida', 'Reducir la fricción de configuración'] },
          { icon: '4', title: 'Configurar impuestos', bullets: ['Definir familias fiscales', 'Confirmar la lógica provincial y los valores predeterminados'] },
          { icon: '5', title: 'Importar clientes y proveedores', bullets: ['Incorporar datos maestros', 'Usar plantillas y validación'] },
          { icon: '6', title: 'Crear la primera factura', bullets: ['Validar el flujo operativo', 'Pasar al uso diario'] },
        ],
      },
      compliance: {
        eyebrow: 'Postura canadiense',
        title: 'Construido para credibilidad, no para exageración',
        subtitle: 'El sitio explica qué está controlado, qué está automatizado y qué todavía requiere revisión.',
        bullets: [
          'Los flujos fiscales canadienses se gestionan con una postura explícita de presentación y auditabilidad.',
          'La nómina se presenta como un complemento separado con alcance y nivel de preparación claros por jurisdicción.',
          'Aprobaciones, gobernanza y expectativas de soporte se expresan directamente en lugar de ocultarse en llamadas comerciales.',
        ],
        coverageLabel: 'Postura comercial actual',
        coverage: 'Mejor encaje para equipos pyme canadienses con 10-50 empleados',
        note: 'Los flujos oficiales respaldados por proveedores siguen disponibles cuando una postura oficial de nivel empresarial no sería la afirmación correcta.',
        provinces: ['ON', 'QC', 'AB', 'BC', 'MB', 'SK', 'NS', 'NB'],
      },
      included: {
        eyebrow: 'Qué está integrado',
        title: 'Una sola plataforma entre finanzas y operaciones',
        subtitle: 'La clave no es tener más funciones sobre el papel. La clave es tener menos flujos fragmentados en la práctica.',
        items: [
          'Contabilidad, facturación, gastos e informes financieros',
          'Compras, inventario, almacén y fundamentos de producción',
          'Aprobaciones, gobernanza y rastro operativo de auditoría',
          'Flujos de cumplimiento fiscal canadiense y soporte para el complemento de nómina',
          'Multisociedad y gobernanza avanzada para alcance empresarial',
          'Inteligencia ERP y asistencia de IA con una postura controlada',
        ],
      },
      executiveSnapshot: {
        badge: 'Modelo operativo',
        title: 'Diseñado para autoevaluación primero y ayuda humana después',
        subtitle: 'Este es un sitio orientado al producto para un ERP serio, no un folleto que obliga a cada prospecto a reservar una llamada.',
        metrics: [
          { label: 'Perfil ideal principal', value: '10-50', note: 'Empleados de pymes canadienses' },
          { label: 'Postura de soporte', value: 'Correo primero', note: 'Tiempos de respuesta claros por plan' },
          { label: 'Postura de incorporación', value: 'Configuración autónoma', note: 'Implementación guiada opcional disponible' },
        ],
      },
      positioning: {
        eyebrow: 'Por qué cambian los equipos',
        title: 'Reduce la fragmentación entre finanzas, operaciones y cumplimiento',
        subtitle: 'La propuesta de valor es control, visibilidad y menos traspasos entre sistemas.',
        cards: [
          {
            role: 'Finanzas',
            headline: 'Cierra con menos sistemas desconectados.',
            points: [
              'Contabilidad, facturación, gastos e informes en un solo sistema.',
              'Límites de soporte claros y controles conscientes del período.',
              'Postura de cumplimiento canadiense sin exagerar la automatización.',
            ],
          },
          {
            role: 'Operaciones',
            headline: 'Mantén stock, compras y producción en sincronía.',
            points: [
              'Los flujos de inventario y almacén están conectados con finanzas.',
              'Fundamentos de BOM y producción sin middleware adicional.',
              'Señales de revisión operativa y gobernanza donde hacen falta.',
            ],
          },
          {
            role: 'Dirección',
            headline: 'Obtén un apoyo más claro para decidir.',
            points: [
              'Menos conciliaciones manuales entre herramientas.',
              'Expectativas de soporte y alcance de incorporación expresados con claridad.',
              'Mejor calificación de prospectos antes de dedicar tiempo interno.',
            ],
          },
          {
            role: 'TI / Operaciones',
            headline: 'Adopta con un alcance disciplinado.',
            points: [
              'Secuencia de implementación clara para equipos pequeños.',
              'Cambios gobernados y flujos auditables.',
              'Capa de marketing compatible con sitios estáticos y metadatos estructurados.',
            ],
          },
        ],
      },
      technical: {
        eyebrow: 'Modelo de soporte e incorporación',
        title: 'Autoservicio por defecto, ayuda guiada cuando importa',
        subtitle: 'El sitio fija expectativas desde el inicio para que los equipos pequeños sepan qué ocurre después del registro.',
        items: [
          'Núcleo financiero incluye incorporación autónoma y soporte por correo con respuesta en 48 h.',
          'Operaciones añade soporte prioritario por correo con respuesta en 24 h.',
          'Empresarial incluye ayuda de incorporación y canal directo de soporte.',
        ],
      },
      supportModel: {
        title: 'Expectativas de soporte por plan',
        subtitle: 'El soporte se define directamente para que la evaluación se mantenga realista.',
        tiers: [
          { name: 'Núcleo financiero', body: 'Soporte por correo, respuesta en 48 h y guía de incorporación autónoma.' },
          { name: 'Operaciones', body: 'Soporte prioritario por correo, respuesta en 24 h y orientación operativa reforzada.' },
          { name: 'Empresarial', body: 'Incorporación dedicada, canal directo de soporte y ayuda acotada para el despliegue.' },
        ],
      },
      demoEnvironment: {
        title: 'Abrir el espacio de evaluación',
        subtitle: 'Usa un espacio basado en navegador con datos ficticios antes de solicitar un recorrido guiado.',
        emailLabel: 'Usuario demo',
        emailValue: 'Use your work email',
        passwordLabel: 'Contraseña',
        passwordValue: 'Set during signup',
        note: 'Solo para evaluación en navegador. Este espacio permanece separado de la planificación de implementación y de las expectativas de producción.',
        cta: { label: 'Abrir espacio de evaluación', path: '/resources#demo-environment' },
      },
      faq: {
        eyebrow: 'Preguntas frecuentes',
        title: 'Preguntas que los equipos hacen antes de comprometer tiempo',
        items: [
          {
            question: '¿Podemos evaluar ZANVROX sin reservar una demo primero?',
            answer: 'Sí. La ruta prevista es ver el resumen, explorar el producto, abrir el espacio de evaluación y solicitar ayuda solo si tu equipo la necesita.',
          },
          {
            question: '¿La nómina está incluida en los planes base?',
            answer: 'No. La nómina es un complemento separado con precio independiente para que los equipos centrados solo en finanzas no paguen por ella por defecto.',
          },
          {
            question: '¿Necesitamos un proyecto de incorporación de pago?',
            answer: 'No. La configuración autónoma es la ruta por defecto. La implementación guiada está disponible como paquete opcional de pago cuando tu equipo quiere ayuda con la configuración y la importación de datos.',
          },
          {
            question: '¿Qué soporte deberíamos esperar?',
            answer: 'Núcleo financiero incluye soporte por correo en 48 h, Operaciones incluye soporte prioritario por correo en 24 h y Empresarial incluye ayuda de incorporación más un canal directo de soporte.',
          },
        ],
      },
      cta: {
        title: 'Empieza por el producto, no por una llamada comercial',
        subtitle: 'Explora primero el producto y los precios. Contacta al equipo cuando tengas una pregunta concreta sobre despliegue, nómina o integración.',
        primary: { label: 'Explorar producto', path: '/product' },
        secondary: { label: 'Ver precios', path: '/pricing' },
      },
    },
    product: {
      heroKicker: 'Cobertura integrada del producto',
      heroTitle: 'Cobertura del producto para finanzas, operaciones, cumplimiento y nómina.',
      heroSubtitle:
        'ZANVROX se presenta como una plataforma ERP controlada para equipos pyme canadienses que necesitan visibilidad operativa sin teatralidad empresarial.',
      heroPrimaryCta: { label: 'Ver precios', path: '/pricing' },
      heroSecondaryCta: { label: 'Abrir espacio de evaluación', path: '/resources#demo-environment' },
      heroPreview: {
        title: 'Vista previa operativa',
        type: 'inventory',
        caption: 'Una sola capa de datos operativos',
        callouts: [
          { status: 'ready', text: 'Inventario, almacén, BOM y producción' },
          { status: 'ready', text: 'Gobernanza y aprobaciones' },
        ],
      },
      pillars: {
        title: 'Cuatro pilares del producto',
        subtitle: 'El sitio explica el producto en torno a flujos de trabajo, no a listas desconectadas de funciones.',
        items: [
          { title: 'Núcleo financiero', body: 'Contabilidad, facturación, gastos, visibilidad bancaria e informes.' },
          { title: 'Operaciones', body: 'Inventario, almacén, BOM, fundamentos de producción y aprobaciones.' },
          { title: 'Cumplimiento canadiense', body: 'Flujos fiscales, complemento de nómina, soporte de remesas y postura de cierre anual.' },
          { title: 'Gobernanza', body: 'Auditabilidad, aprobaciones, límites de control y ruta de expansión multisociedad.' },
        ],
      },
      showcase: {
        title: 'Áreas del producto que vale la pena evaluar visualmente',
        subtitle: 'Estas son las pantallas que la mayoría de los equipos quiere inspeccionar antes de invertir tiempo en conversaciones comerciales más profundas.',
        items: [
          {
            title: 'Panel fiscal',
            body: 'Muestra la postura de presentación, el progreso de cumplimiento y la visibilidad del flujo de soporte.',
            previewType: 'reports',
            imageKey: 'taxDashboard',
            imageAlt: 'Panel fiscal en ZANVROX ERP',
          },
          {
            title: 'Control de inventario',
            body: 'Muestra visibilidad de stock, rutas de almacén y señales de preparación operativa.',
            previewType: 'inventory',
          },
          {
            title: 'Planificación de producción',
            body: 'Muestra planificación operativa vinculada a BOM y progreso de ejecución.',
            previewType: 'production',
          },
          {
            title: 'Informes financieros',
            body: 'Muestra informes conectados desde la actividad operativa de vuelta a finanzas.',
            previewType: 'reports',
          },
        ],
      },
      stacks: [
        {
          title: 'Finanzas y operaciones integradas',
          subtitle: 'Diseñado para reducir traspasos entre herramientas en el segmento de 10-50 empleados.',
          items: [
            'Contabilidad y facturación viven en el mismo sistema que compras y gastos.',
            'Los datos de inventario, almacén y BOM permanecen vinculados al registro financiero.',
            'Aprobaciones y gobernanza pueden añadirse sin herramientas operativas separadas.',
          ],
        },
        {
          title: 'Postura canadiense de control',
          subtitle: 'Diseñado para resultar creíble dentro de un contexto operativo canadiense.',
          items: [
            'El soporte fiscal canadiense se explica con lenguaje práctico de flujo de trabajo.',
            'La nómina sigue siendo un complemento con alcance de soporte y precio explícitos.',
            'Las afirmaciones están alineadas con la postura real de gobernanza, preparación y revisión.',
          ],
        },
      ],
      onboarding: {
        title: 'Cómo funciona la configuración autónoma en la práctica',
        subtitle: 'La página de producto refuerza que la incorporación se guía dentro del producto y no se oculta detrás de consultoría por defecto.',
        steps: [
          { number: '1', title: 'Crear organización', body: 'Crea tu espacio de trabajo y empieza desde una base operativa limpia.' },
          { number: '2', title: 'Seleccionar Canadá', body: 'Aplica valores predeterminados del país y supuestos de cumplimiento.' },
          { number: '3', title: 'Elegir plantilla sectorial', body: 'Empieza desde una línea base práctica en lugar de configurar desde cero.' },
          { number: '4', title: 'Configurar impuestos', body: 'Confirma el enrutamiento fiscal, registros y controles financieros.' },
          { number: '5', title: 'Importar datos maestros', body: 'Incorpora clientes, proveedores y registros operativos clave.' },
          { number: '6', title: 'Ejecutar la primera transacción', body: 'Crea la primera factura y valida el recorrido operativo de extremo a extremo.' },
        ],
        note: 'La implementación guiada está disponible cuando tu equipo quiere ayuda con la configuración, revisión del plan contable, importación de datos y formación.',
      },
      cta: {
        title: 'Comprueba si el alcance del producto encaja con tu empresa hoy',
        subtitle: 'Usa precios y recursos para decidir si necesitas configuración autónoma, implementación guiada o una conversación empresarial.',
        primary: { label: 'Ver precios', path: '/pricing' },
        secondary: { label: 'Contactar al equipo', path: '/contact' },
      },
    },
    pricing: {
      heroTitle: 'Precios para operaciones estructuradas y expansión controlada.',
      heroSubtitle:
        'Empieza con un núcleo financiero controlado, amplía hacia operaciones a medida que aumenta la complejidad y pasa a un despliegue personalizado solo cuando sean necesarios una estructura multiubicación, aprobaciones avanzadas, soporte de onboarding, integraciones o revisión de seguridad.',
      packagesTitle: 'Precios públicos para finanzas, operaciones y despliegue guiado',
      packagesSubtitle: 'Precios transparentes en CAD para equipos SMB canadienses que necesitan flujos estructurados hoy y una ruta creíble hacia un control operativo más amplio con el tiempo.',
      launchBadge: 'Facturación anual disponible',
      launchOfferLabel: 'Las suscripciones base anuales incluyen un mes gratis cuando se facturan por año.',
      launchOfferNote: 'El precio de nómina sigue siendo por uso, y la Implementación guiada está disponible cuando se necesita un despliegue más estructurado.',
      popularLabel: 'Buen ajuste para 10-50 empleados',
      priceSuffixMonthly: '/mes',
      billedMonthlyLabel: 'Facturación mensual',
      billedAnnuallyLabel: 'Facturación anual',
      fromLabel: 'Desde',
      customLabel: 'Personalizado',
      includesLabel: 'Incluye',
      entitiesIncludedLabel: 'Alcance comercial',
      usersIncludedLabel: 'Usuarios incluidos',
      billingToggle: {
        monthly: 'Mensual',
        annual: 'Anual',
        annualBadge: '1 mes gratis',
        helper: 'La facturación anual cambia solo el plazo de la suscripción base. La nómina mantiene una cuota base más el número de empleados.',
      },
      pricingNote:
        'Todos los precios están en CAD. La nómina es un complemento separado. Los planes están diseñados para operaciones estructuradas, flujos controlados, auditabilidad y diseño de producto consciente de la seguridad sin forzar demasiado pronto un alcance empresarial. ZANVROX ayuda a organizar flujos financieros, de nómina y fiscales, pero no sustituye el asesoramiento contable, legal ni fiscal.',
      tiers: [
        {
          slug: 'finance-core',
          name: 'Núcleo financiero',
          summary: 'Para empresas que necesitan una base financiera disciplinada con contabilidad, facturación, gastos, informes y una ruta clara de configuración autónoma.',
          entitiesLabel: 'Alcance de empresa única',
          usersLabel: 'Hasta 3 usuarios',
          monthly: {
            kind: 'fixed',
            amount: 179,
            note: 'Incluye guía de configuración autónoma, flujos financieros controlados y soporte por correo con respuesta en 48 h.',
          },
          annual: {
            kind: 'fixed',
            amount: 179,
            badge: '1 mes gratis',
            note: 'Facturado anualmente a CAD 1,969 por la suscripción base.',
            secondaryNote: 'La nómina y un alcance operativo más amplio siguen siendo componentes separados cuando se necesitan.',
          },
          included: [
            'Flujos contables',
            'Facturación',
            'Captura de gastos',
            'Informes financieros',
            'Guía de configuración autónoma',
            'Soporte por correo (48 h de respuesta)',
          ],
          ctaLabel: 'Revisar Núcleo financiero',
        },
        {
          slug: 'operations',
          name: 'Operaciones',
          isPopular: true,
          summary: 'Para equipos que necesitan finanzas y operaciones trabajando juntas entre inventario, almacén, fundamentos de producción y aprobaciones controladas.',
          entitiesLabel: 'Alcance de empresa única',
          usersLabel: 'Hasta 10 usuarios',
          monthly: {
            kind: 'fixed',
            amount: 649,
            note: 'Incluye soporte prioritario por correo con respuesta en 24 h para equipos con mayor actividad operativa.',
          },
          annual: {
            kind: 'fixed',
            amount: 649,
            badge: '1 mes gratis',
            note: 'Facturado anualmente a CAD 7,139 por la suscripción base.',
            secondaryNote: 'Recomendado cuando operaciones necesita un control más estrecho sobre stock, movimientos de almacén, BOM y flujos de producción.',
          },
          included: [
            'Todo lo incluido en Núcleo financiero',
            'Control de inventario',
            'Flujos de almacén',
            'Producción (BOM)',
            'Aprobaciones y gobernanza',
            'Soporte prioritario por correo (24 h de respuesta)',
          ],
          ctaLabel: 'Revisar Operaciones',
        },
        {
          slug: 'enterprise',
          name: 'Personalizado',
          summary: 'Para equipos con varias ubicaciones que necesitan aprobaciones avanzadas, revisiones de seguridad, onboarding personalizado, integraciones, soporte dedicado o un despliegue más estructurado.',
          entitiesLabel: 'Alcance multiubicación o personalizado',
          usersLabel: 'Alcance de usuarios personalizado',
          monthly: {
            kind: 'custom',
            label: 'Personalizado',
            note: 'Revisión acotada para despliegue multiubicación, configuración guiada, integraciones, necesidades de gobernanza y revisión de seguridad.',
          },
          annual: {
            kind: 'custom',
            label: 'Personalizado',
            note: 'El precio personalizado se acota directamente según la estructura operativa, las necesidades de despliegue y el contexto de implementación.',
          },
          included: [
            'Despliegue multiubicación',
            'Gobernanza avanzada',
            'Integraciones',
            'Ruta de revisión de seguridad',
            'Implementación guiada y soporte de despliegue',
          ],
          ctaLabel: 'Solicitar revisión personalizada',
        },
      ],
      payrollAddon: {
        title: 'Complemento de nómina',
        summary: 'Un precio separado para nómina mantiene comercialmente claro el ERP base mientras preserva el soporte de nómina canadiense para los equipos que lo necesitan.',
        priceLabel: 'CAD 59 / mes + CAD 6 / empleado / mes',
        annualPriceLabel: 'CAD 59 / mes + CAD 6 / empleado / mes',
        monthlyNote: 'Incluye ejecuciones de nómina canadiense, soporte de flujos de remesas, recibos de sueldo, registros y exportaciones para respaldar la revisión de cierre anual e integración contable. Puede aplicar un mínimo mensual durante el despliegue.',
        annualNote: 'El complemento de nómina mantiene la misma estructura de cuota base más empleado cuando se factura anualmente, salvo que se acuerde un alcance distinto.',
        included: [
          'Ejecuciones de nómina canadiense',
          'Soporte de flujos de remesas',
          'Recibos de sueldo',
          'Registros y exportaciones para respaldar revisión',
          'Integración contable',
        ],
        ctaLabel: 'Consultar sobre nómina',
      },
      onboardingPackage: {
        title: 'Implementación guiada',
        summary: 'Configuración guiada opcional de pago único para equipos que quieren alineación operativa, despliegue asistido y un inicio de implementación más estructurado.',
        priceLabel: 'CAD 3,500 a 7,500 pago único',
        included: [
          'Configuración guiada del sistema',
          'Revisión de alineación operativa',
          'Revisión del plan contable',
          'Configuración de impuestos',
          'Guía para importación de datos',
          'Sesión de formación para despliegue asistido',
        ],
        note: 'Opcional. Los planes estándar pueden empezar igualmente con configuración autónoma cuando un despliegue más ligero es suficiente.',
        ctaLabel: 'Solicitar configuración guiada',
      },
      supportTiers: {
        title: 'Estructura de soporte',
        subtitle: 'El soporte se expresa públicamente para que los equipos puedan evaluar cobertura operativa, expectativas de respuesta y postura de despliegue desde el principio.',
        items: [
          { name: 'Núcleo financiero', body: 'Soporte por correo con tiempo de respuesta de 48 h.' },
          { name: 'Operaciones', body: 'Soporte prioritario por correo con tiempo de respuesta de 24 h.' },
          { name: 'Personalizado', body: 'Soporte para despliegue guiado, canal directo y conversación de implementación acotada.' },
        ],
      },
      comparison: {
        title: 'Comparación de planes',
        subtitle: 'Usa esto para decidir si necesitas control financiero estructurado, operaciones conectadas o un despliegue empresarial personalizado.',
        featureLabel: 'Capacidad',
        rows: [
          { label: 'Contabilidad', values: [true, true, true] },
          { label: 'Facturación', values: [true, true, true] },
          { label: 'Gastos', values: [true, true, true] },
          { label: 'Informes financieros', values: [true, true, true] },
          { label: 'Inventario', values: [false, true, true] },
          { label: 'Almacén', values: [false, true, true] },
          { label: 'Producción (BOM)', values: [false, true, true] },
          { label: 'Aprobaciones y gobernanza', values: [false, true, true] },
          { label: 'Despliegue multiubicación', values: [false, false, true] },
          { label: 'Aprobaciones avanzadas', values: [false, true, true] },
          { label: 'Integraciones', values: [false, false, true] },
          { label: 'Nivel de soporte', values: ['Correo / 48 h', 'Correo prioritario / 24 h', 'Canal directo'] },
          { label: 'Asistencia de incorporación', values: ['Configuración autónoma', 'Configuración autónoma', 'Incluida'] },
          { label: 'Usuarios incluidos', values: ['3', '10', 'Personalizado'] },
        ],
        notesTitle: 'Notas comerciales',
        notes: [
          'La nómina es un complemento separado.',
          'La Implementación guiada es opcional y tiene precio aparte para equipos que quieren un despliegue más estructurado.',
          'Personalizado es la ruta para alcance multiubicación, integraciones, revisión de seguridad y contexto de implementación guiada.',
          'El modelo comercial está diseñado para preservar la transparencia mientras respalda flujos controlados y auditabilidad a medida que aumentan los requisitos.',
        ],
        annualNote: 'Los planes base anuales incluyen un mes gratis.',
      },
      faq: {
        title: 'Preguntas frecuentes sobre precios',
        subtitle: 'Respuestas para equipos que quieren autoevaluarse antes de una llamada.',
        items: [
          {
            question: '¿Necesito una demo antes de poder empezar?',
            answer: 'No. La ruta prevista es autoevaluación primero: ver el resumen, explorar el producto, revisar precios y usar el espacio de evaluación en navegador antes de solicitar una sesión guiada.',
          },
          {
            question: '¿La nómina está incluida en los planes ERP base?',
            answer: 'No. La nómina se vende como complemento separado con una cuota mensual base más precio por empleado.',
          },
          {
            question: '¿La Implementación guiada es obligatoria?',
            answer: 'No. Es opcional. Núcleo financiero y Operaciones pueden empezar con configuración autónoma, mientras que la Implementación guiada está disponible para equipos que quieren un despliegue más estructurado.',
          },
          {
            question: '¿Qué soporte incluye cada plan?',
            answer: 'Núcleo financiero incluye soporte por correo en 48 h, Operaciones incluye soporte prioritario por correo en 24 h y Personalizado incluye conversación de despliegue guiado más un canal directo de soporte.',
          },
        ],
      },
      ctaPrimary: { label: 'Abrir espacio de evaluación', path: '/resources#demo-environment' },
      ctaSecondary: { label: 'Contactar para despliegue personalizado', path: '/contact' },
    },
    resources: {
      heroTitle: 'Recursos para evaluación de producto, revisión de seguridad y planificación de despliegue.',
      heroSubtitle: 'Usa estos materiales públicos para revisar encaje de producto, postura de seguridad y opciones de evaluación antes de solicitar una conversación más profunda.',
      sections: [
        {
          title: 'Resumen del producto y recursos de evaluación',
          description: 'Revisa el resumen del producto, cobertura de flujos y modelo de incorporación antes de invertir tiempo en una evaluación más profunda.',
          cta: 'Revisar producto',
          path: '/product',
        },
        {
          title: 'Resumen de seguridad',
          description: 'Revisa aislamiento entre organizaciones, controles de acceso, subprocesadores y limitaciones actuales de seguridad en un solo resumen público.',
          cta: 'Revisar seguridad',
          path: '/security',
        },
        {
          title: 'Espacio de evaluación y revisión guiada del producto',
          description: 'Empieza con el espacio de evaluación compartido para una revisión inicial y contacta al equipo si necesitas una conversación de producto más estructurada.',
          cta: 'Abrir espacio de evaluación',
          path: '/resources#demo-environment',
        },
        {
          title: 'Contacto y documentación adicional',
          description: 'Usa la ruta de contacto para consultas de seguridad o cumplimiento, solicitudes de revisión guiada o mayor detalle de evaluación.',
          cta: 'Contactar al equipo',
          path: '/contact',
        },
      ],
      demoEnvironment: {
        title: 'Espacio de evaluación',
        subtitle: 'Un espacio basado en navegador para revisión inicial del producto con datos ficticios de muestra.',
        accessTitle: 'Acceso compartido de evaluación',
        accessIntro: 'El acceso compartido está disponible para revisión temprana del producto. Los equipos que necesiten una evaluación más profunda o más estructurada pueden contactar a ZANVROX.',
        emailLabel: 'Usuario del espacio',
        emailValue: 'Use your work email',
        passwordLabel: 'Código de acceso',
        passwordValue: 'Set during signup',
        note: 'No requiere instalación. Este espacio es solo para evaluación, usa datos ficticios y no está pensado para datos reales de empresa, empleados, clientes, nómina o finanzas.',
        guidance: [
          'Usa el espacio para una revisión inicial de navegación, cobertura de flujos y encaje general del producto.',
          'Trata el entorno como una superficie compartida de evaluación y no como un espacio de producción, piloto o migración de datos.',
          'Para una revisión más profunda, preguntas de seguridad y cumplimiento o documentación adicional, usa la ruta de contacto después de la evaluación inicial.',
        ],
        cta: { label: 'Abrir espacio de evaluación', path: '/resources#demo-environment' },
      },
      sitemap: {
        title: 'Materiales de evaluación',
        subtitle: 'El sitio público es intencionalmente compacto y está centrado en los materiales más útiles durante la evaluación inicial.',
        items: [
          'Resumen del producto y cobertura de flujos',
          'Precios públicos y modelo de incorporación',
          'Resumen de seguridad y postura actual de control',
          'Espacio de evaluación con datos ficticios',
          'Ruta de contacto para revisión guiada y preguntas de seguimiento',
          'Información legal sobre términos y privacidad',
        ],
      },
      design: {
        title: 'Cómo usar estos recursos',
        subtitle: 'Una ruta simple de evaluación para equipos que quieren revisar primero el encaje del producto e involucrar al equipo solo cuando se necesita más detalle.',
        directionTitle: 'Revisión inicial del producto',
        componentsTitle: 'Revisión de seguridad y cumplimiento',
        statesTitle: 'Cuándo contactar al equipo',
        direction: [
          'Empieza por Producto, Precios y Recursos para entender alcance, postura de incorporación y encaje comercial.',
          'Usa el espacio de evaluación para una revisión práctica temprana solo con datos ficticios.',
          'Trata los materiales públicos como una capa inicial de calificación antes de solicitar una conversación más profunda.',
        ],
        components: [
          'Usa el Resumen de seguridad para revisar aislamiento entre organizaciones, control de acceso, subprocesadores y limitaciones actuales.',
          'Usa la ruta de contacto para consultas de seguridad y cumplimiento o para solicitar documentación adicional.',
          'Mantén las preguntas de evaluación vinculadas al alcance y a las afirmaciones publicadas actualmente.',
        ],
        states: [
          'Solicita una revisión guiada del producto cuando tu equipo tenga preguntas concretas sobre flujos o despliegue.',
          'Contacta al equipo si necesitas más detalle que el ofrecido por los materiales públicos de evaluación.',
          'Usa la ruta de contacto existente para solicitar un resumen de seguridad y seguimiento de seguridad y cumplimiento.',
        ],
      },
    },
    security: {
      heroTitle: 'Seguridad y arquitectura por diseño.',
      heroSubtitle: 'Límites entre organizaciones, acceso de mínimo privilegio y comportamiento transaccional auditable.',
      overview: {
        title: 'Resumen de seguridad',
        subtitle: 'Un resumen conservador de los controles visibles actualmente en el producto y en el flujo de entrega.',
        description:
          'ZANVROX está construido alrededor del aislamiento entre organizaciones, acceso por roles y tratamiento reforzado desde servidor para operaciones sensibles. Las declaraciones públicas de seguridad se limitan a controles que hoy están implementados y evitan de forma intencionada afirmaciones de certificación o cobertura que todavía no existen.',
        bullets: [
          'La postura de seguridad se centra en acceso de mínimo privilegio, alcance por organización y comportamiento operativo auditable.',
          'Las áreas sensibles pueden requerir autenticación más fuerte antes de conceder acceso.',
          'La infraestructura y la entrega dependen de proveedores gestionados de plataforma en lugar de operaciones de servidor autogestionadas.',
        ],
      },
      matrix: {
        title: 'Matriz de controles',
        subtitle: 'Cada declaración de control está vinculada a un mecanismo de implementación.',
      },
      controls: [
        { control: 'Aislamiento entre organizaciones', support: 'Políticas PostgreSQL RLS delimitadas por org_id en tablas operativas.' },
        { control: 'Control de acceso', support: 'Pertenencia a la organización y rutas de escritura limitadas por rol para operaciones críticas.' },
        { control: 'Trazabilidad de cambios', support: 'Identificadores a nivel de transacción, marcas de tiempo y registros de confirmación de presentación.' },
        { control: 'Aplicación desde servidor', support: 'Acciones contables y fiscales críticas ejecutadas a través de controles SQL/Edge.' },
      ],
      sections: [
        {
          title: 'Control de acceso y autenticación',
          items: [
            'El control de acceso basado en roles se aplica mediante pertenencia a la organización, permisos por módulo y rutas de escritura limitadas por rol.',
            'La MFA está disponible mediante factores TOTP con aplicación autenticadora.',
            'Las áreas sensibles del ERP pueden requerir autenticación reforzada en AAL2 antes de conceder acceso.',
          ],
        },
        {
          title: 'Aislamiento de datos',
          items: [
            'El aislamiento a nivel de organización se delimita por identificadores de organización y políticas de seguridad de base de datos.',
            'Las lecturas y escrituras operativas están vinculadas al contexto activo de la organización.',
            'La separación de datos es lógica dentro del entorno compartido de la aplicación y no se basa en pilas de aplicación por cliente.',
          ],
        },
        {
          title: 'Alojamiento e infraestructura',
          items: [
            'Los servicios backend se gestionan a través de Supabase.',
            'El frontend público se entrega a través de Vercel.',
            'El cifrado en tránsito usa HTTPS/TLS.',
            'La infraestructura subyacente en la nube es gestionada por el proveedor en lugar de ser operada directamente por ZANVROX.',
          ],
        },
        {
          title: 'Seguridad operativa',
          items: [
            'Las puertas de publicación incluyen linting, pruebas unitarias, pruebas web, builds y scripts de validación antes de tomar decisiones de despliegue.',
            'La cobertura Playwright E2E y las comprobaciones smoke alojadas se usan para validar flujos críticos.',
            'La supervisión de dependencias incluye npm audit en CI para revisar paquetes de alta severidad.',
            'Los registros de aplicación se sanean para reducir la exposición accidental de correos, tokens y otros campos sensibles.',
          ],
        },
      ],
      subprocessors: {
        title: 'Subprocesadores',
        subtitle: 'Resumen público actual de los proveedores externos usados para operar el servicio.',
        items: [
          {
            name: 'Supabase',
            support: 'Plataforma backend gestionada para base de datos, autenticación, almacenamiento y flujos del lado del servidor.',
          },
          {
            name: 'Vercel',
            support: 'Alojamiento y entrega frontend gestionados para la experiencia web pública.',
          },
          {
            name: 'Resend',
            support: 'Entrega transaccional de correo para comunicación limitada y enrutamiento de oportunidades del sitio web.',
          },
        ],
        note: 'Estos proveedores se usan solo cuando son necesarios para la operación del servicio, la entrega o la comunicación transaccional.',
      },
      disclosures: {
        title: 'Transparencia y limitaciones actuales',
        subtitle: 'Declaraciones conservadoras que reflejan los controles disponibles actualmente.',
        items: [
          'Sin afirmaciones de presentación automática: solo soporte de flujo preparado para portal.',
          'Sin feature flags ocultos para capacidades públicas.',
          'Comportamiento de producción respaldado por registros auditables y snapshots.',
          'La MFA depende actualmente de TOTP con aplicación autenticadora y no es resistente al phishing.',
          'La autenticación reforzada se aplica en rutas sensibles en lugar de imponerse como requisito global para cada sesión.',
          'WebAuthn y la autenticación basada en passkeys aún no están disponibles.',
        ],
      },
      cta: {
        title: 'Contacto de seguridad',
        subtitle: 'Usa la ruta de contacto existente para solicitudes de resumen de seguridad o seguimiento de seguridad y cumplimiento.',
        primary: { label: 'Solicitar resumen de seguridad', path: '/contact' },
        secondary: { label: 'Contactar por consultas de seguridad y cumplimiento', path: '/contact' },
      },
    },
    about: {
      heroKicker: 'Acerca de ZANVROX',
      heroTitle: 'Un ERP práctico posicionado para un despliegue creíble, no para teatralidad empresarial.',
      heroSubtitle:
        'ZANVROX se presenta como un ERP moderno para equipos pyme canadienses que quieren un control operativo más estricto, menos sistemas desconectados y una ruta de soporte más clara.',
      heroPrimaryCta: { label: 'Explorar producto', path: '/product' },
      heroSecondaryCta: { label: 'Contactar al equipo', path: '/contact' },
      heroPreview: {
        title: 'Resumen de posicionamiento',
        type: 'reports',
        caption: 'Control operativo frente a la dispersión del software',
        callouts: [
          { status: 'ready', text: 'Postura de soporte clara' },
          { status: 'ready', text: 'Ruta de evaluación orientada al producto' },
        ],
      },
      principles: {
        title: 'Tres principios detrás del sitio',
        subtitle: 'El posicionamiento público está optimizado para una realidad operativa liderada por fundadores sin rebajar los estándares del producto.',
        items: [
          { title: 'Claridad', body: 'Expresar qué hace el producto, qué soporta y dónde todavía se requiere revisión.' },
          { title: 'Control', body: 'Centrarse en auditabilidad, gobernanza y visibilidad operativa en lugar de exageración SaaS inflada.' },
          { title: 'Despliegue práctico', body: 'Hacer viable la configuración autónoma manteniendo ayuda experta opcional cuando la complejidad aumenta.' },
        ],
      },
      operatingModel: [
        {
          title: 'Construido para equipos pyme canadienses',
          subtitle: 'El sitio público se dirige a empresas que necesitan un control ERP creíble sin la carga de consultoría empresarial desde el primer día.',
          items: [
            'Mejor encaje alrededor de 10-50 empleados',
            'Alto valor cuando finanzas y operaciones están repartidas entre demasiadas herramientas',
            'Ruta clara desde el núcleo financiero hasta operaciones y el complemento de nómina',
          ],
        },
        {
          title: 'Disciplina comercial',
          subtitle: 'El sitio está diseñado para reducir reuniones de baja calidad y hacer explícitas las expectativas antes de la primera conversación.',
          items: [
            'Demo opcional en lugar de un embudo centrado en la demo',
            'Precios públicos con niveles de soporte y expectativas de incorporación',
            'Afirmaciones de seguridad y gobernanza alineadas con la postura real del producto',
          ],
        },
      ],
      cta: {
        title: 'Comprueba si el modelo operativo encaja con tu equipo',
        subtitle: 'Usa Producto, Precios y Recursos para calificar el encaje antes de escribirnos.',
        primary: { label: 'Ver precios', path: '/pricing' },
        secondary: { label: 'Ir a contacto', path: '/contact' },
      },
    },
    contact: {
      heroTitle: 'Contacta al equipo solo cuando necesites ayuda con una pregunta real de evaluación.',
      heroSubtitle:
        'La ruta prevista es resumen del producto, exploración del producto, revisión de precios, evaluación en navegador y después contacto opcional o solicitud de recorrido guiado.',
      conversion: {
        title: 'Flujo de evaluación recomendado',
        subtitle: 'Esto reduce reuniones innecesarias y da mejor contexto cuando alguien finalmente se pone en contacto.',
        cards: [
          { title: 'Ver resumen del producto', body: 'Empieza con el video para entender el modelo operativo y la postura del producto.' },
          { title: 'Explorar funciones', body: 'Usa Producto, Precios y Seguridad para evaluar la plataforma sin una llamada.' },
          { title: 'Abrir el espacio de evaluación', body: 'Valida la interfaz con datos ficticios antes de solicitar una sesión guiada.' },
          { title: 'Solicitar ayuda si hace falta', body: 'Usa los formularios inferiores para una demo opcional o una pregunta concreta sobre el producto.' },
        ],
      },
      supportBlock: {
        title: 'Expectativas de soporte',
        subtitle: 'Todos los flujos de contacto del sitio web llegan a support@zanvrox.com.',
        items: [
          'Núcleo financiero: soporte por correo con tiempo de respuesta de 48 h',
          'Operaciones: soporte prioritario por correo con tiempo de respuesta de 24 h',
          'Empresarial: canal directo de soporte más ayuda de incorporación',
        ],
      },
      pricingContext: {
        title: 'Contexto de precios seleccionado',
        subtitle: 'El contexto de precios permanece unido a tu solicitud para que el seguimiento siga basado en la configuración que seleccionaste.',
        labels: {
          plan: 'Plan',
          billing: 'Facturación',
          payroll: 'Nómina',
          offer: 'Oferta',
          notSelected: 'No seleccionado',
          payrollInterested: 'Complemento de nómina seleccionado',
          payrollNotSelected: 'Sin complemento de nómina seleccionado',
        },
      },
      demoForm: {
        title: 'Solicitar recorrido guiado',
        helper: 'Usa esto después de que tu equipo haya revisado el producto y quiera un recorrido guiado.',
        confirmation: 'Tu solicitud de recorrido guiado se envió correctamente. Haremos seguimiento por correo.',
        submittingCta: 'Enviando...',
        submitError: 'No pudimos enviar tu solicitud. Inténtalo de nuevo.',
        messageHint: 'Opcional. Usa esto para describir tu stack actual, calendario de despliegue o pregunta sobre nómina.',
        fields: {
          name: 'Nombre*',
          company: 'Empresa*',
          email: 'Correo de trabajo*',
          companySize: 'Tamaño de la empresa*',
          interestArea: 'Área de interés*',
          message: 'Mensaje opcional',
          consent:
            'Acepto que ZANVROX me contacte sobre esta solicitud comercial. Solo usamos estos datos para responder a la consulta.',
        },
        placeholders: {
          email: 'nombre@empresa.com',
          companySize: 'Selecciona el tamaño de la empresa',
          interestArea: 'Selecciona el área de interés',
          message: '¿Qué quieres validar en una sesión guiada?',
        },
        options: {
          companySizes: ['1-10 empleados', '10-50 empleados', '50-100 empleados', '100+ empleados'],
          interestAreas: [
            'Núcleo financiero',
            'Operaciones',
            'Complemento de nómina',
            'Implementación guiada',
            'Despliegue empresarial',
            'Integraciones / API',
          ],
        },
        errors: {
          name: 'Introduce tu nombre.',
          company: 'Introduce el nombre de tu empresa.',
          email: 'Introduce un correo de trabajo válido.',
          companySize: 'Selecciona el tamaño de la empresa.',
          interestArea: 'Selecciona un área de interés.',
          message: 'Mantén el mensaje por debajo de 2000 caracteres.',
          consent: 'El consentimiento es obligatorio para enviar este formulario.',
          startedAt: 'Espera un momento antes de enviar.',
          website: 'Se activó la protección antispam.',
        },
        cta: 'Solicitar recorrido guiado',
      },
      briefForm: {
        title: 'Hacer una pregunta sobre el producto',
        helper: 'Usa esto para preguntas sobre encaje del producto, soporte, incorporación, implementación o alcance de nómina.',
        confirmation: 'Tu mensaje se envió correctamente. Responderemos por correo.',
        submittingCta: 'Enviando...',
        submitError: 'No pudimos enviar tu solicitud. Inténtalo de nuevo.',
        messageHint: 'Opcional. Usa esto si quieres describir tu flujo, necesidad de soporte o pregunta de implementación.',
        fields: {
          name: 'Nombre*',
          company: 'Empresa*',
          email: 'Correo de trabajo*',
          companySize: 'Tamaño de la empresa*',
          interestArea: 'Área de interés*',
          message: 'Mensaje opcional',
          consent: 'Acepto recibir el seguimiento solicitado por parte de ZANVROX.',
        },
        placeholders: {
          email: 'nombre@empresa.com',
          companySize: 'Selecciona el tamaño de la empresa',
          interestArea: 'Selecciona el área de interés',
          message: '¿Qué te gustaría aclarar antes de que tu equipo dedique más tiempo a la evaluación?',
        },
        options: {
          companySizes: ['1-10 empleados', '10-50 empleados', '50-100 empleados', '100+ empleados'],
          interestAreas: [
            'Encaje del producto',
            'Precios y soporte',
            'Acceso al entorno de pruebas',
            'Importación de datos',
            'Complemento de nómina',
            'Implementación guiada',
          ],
        },
        errors: {
          name: 'Introduce tu nombre.',
          company: 'Introduce el nombre de tu empresa.',
          email: 'Introduce un correo de trabajo válido.',
          companySize: 'Selecciona el tamaño de la empresa.',
          interestArea: 'Selecciona un área de interés.',
          message: 'Mantén el mensaje por debajo de 2000 caracteres.',
          consent: 'El consentimiento es obligatorio para enviar este formulario.',
          startedAt: 'Espera un momento antes de enviar.',
          website: 'Se activó la protección antispam.',
        },
        cta: 'Enviar pregunta',
      },
    },
    legal: {
      privacy: {
        title: 'Política de privacidad',
        updated: '5 de marzo de 2026',
        updatedLabel: 'Última actualización',
        paragraphs: [
          'ZANVROX recopila información de contacto empresarial enviada a través de este sitio web para evaluación del producto, programación de demos y solicitudes de documentación.',
          'Procesamos los datos enviados únicamente para fines comerciales y de calificación de producto.',
          'Puedes solicitar acceso, corrección o eliminación de los datos enviados escribiendo a support@zanvrox.com.',
        ],
      },
      terms: {
        title: 'Términos del servicio',
        updated: '5 de marzo de 2026',
        updatedLabel: 'Última actualización',
        paragraphs: [
          'Este sitio proporciona información del producto y formularios de captación comercial para la evaluación de ZANVROX ERP.',
          'El contenido del sitio web es informativo y no constituye un compromiso vinculante de producto.',
          'El alcance del producto y las condiciones comerciales se cierran en acuerdos firmados.',
        ],
      },
    },
    notFound: {
      title: 'Página no encontrada',
      subtitle: 'La URL no coincide con la estructura publicada del sitio ZANVROX.',
      cta: 'Ir al inicio',
    },
  },
  footer: {
    companyDescription: 'ERP integrado para equipos pyme canadienses que necesitan finanzas, operaciones, cumplimiento y nómina en una sola plataforma controlada.',
    headquarters: 'Toronto, Ontario, Canadá',
    email: 'support@zanvrox.com',
    sections: [
      {
        title: 'Producto',
        links: [
          { label: 'Resumen del producto', path: '/product' },
          { label: 'Precios', path: '/pricing' },
          { label: 'Recursos', path: '/resources' },
          { label: 'Contacto', path: '/contact' },
        ],
      },
      {
        title: 'Confianza y legal',
        links: [
          { label: 'Seguridad', path: '/security' },
          { label: 'Seguridad / Cumplimiento', path: '/security' },
          { label: 'Solicitar información de seguridad', path: '/contact' },
          { label: 'Privacidad', path: '/legal/privacy' },
          { label: 'Términos', path: '/legal/terms' },
        ],
      },
    ],
    links: [
      { label: 'Producto', path: '/product' },
      { label: 'Precios', path: '/pricing' },
      { label: 'Recursos', path: '/resources' },
      { label: 'Seguridad', path: '/security' },
      { label: 'Acerca de', path: '/about' },
      { label: 'Contacto', path: '/contact' },
      { label: 'Privacidad', path: '/legal/privacy' },
      { label: 'Términos', path: '/legal/terms' },
    ],
  },
  seo: {
    home: {
      title: 'ZANVROX | ERP canadiense para finanzas, operaciones y control',
      description:
        'ERP integrado para equipos pyme canadienses con contabilidad, facturación, inventario, almacén, producción, gobernanza, flujos fiscales y soporte para complemento de nómina.',
      path: '/',
    },
    product: {
      title: 'Producto | ZANVROX',
      description:
        'Explora finanzas, operaciones, cumplimiento canadiense, gobernanza y cobertura del complemento de nómina dentro de la plataforma ERP de ZANVROX.',
      path: '/product',
    },
    security: {
      title: 'Seguridad | ZANVROX',
      description: 'Revisa aislamiento entre organizaciones, controles por rol, aprobaciones, gobernanza y salvaguardas de arquitectura detrás de ZANVROX.',
      path: '/security',
    },
    pricing: {
      title: 'Precios | ZANVROX',
      description:
        'Revisa precios públicos en CAD para Núcleo financiero, Operaciones, despliegue personalizado, el complemento de nómina y la Implementación guiada opcional.',
      path: '/pricing',
    },
    resources: {
      title: 'Recursos | ZANVROX',
      description: 'Usa recursos del producto, guía del espacio de evaluación y material del resumen de seguridad para autoevaluar ZANVROX.',
      path: '/resources',
    },
    about: {
      title: 'Acerca de | ZANVROX',
      description: 'Descubre cómo ZANVROX posiciona finanzas, operaciones, gobernanza y disciplina de despliegue para equipos pyme canadienses.',
      path: '/about',
    },
    contact: {
      title: 'Contacto | ZANVROX',
      description: 'Solicita una demo opcional o plantea una pregunta concreta sobre producto, nómina, incorporación o implementación.',
      path: '/contact',
    },
    privacy: {
      title: 'Política de privacidad | ZANVROX',
      description: 'Política de privacidad del sitio web de ZANVROX y del tratamiento relacionado con oportunidades.',
      path: '/legal/privacy',
    },
    terms: {
      title: 'Términos del servicio | ZANVROX',
      description: 'Términos del servicio que regulan el uso del sitio web y los materiales de ZANVROX.',
      path: '/legal/terms',
    },
  },
}

export default siteContentEs
